/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_1.v:1.1-54.10" *)
module alu_8bit(rs, rt, op, alu_out);
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_1.v:9.12-9.19" *)
  (* unused_bits = "0 1 2 3 4 5 6 7" *)
  wire [7:0] add_out;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_1.v:5.23-5.30" *)
  output [7:0] alu_out;
  wire [7:0] alu_out;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_1.v:11.12-11.19" *)
  (* unused_bits = "0 1 2 3 4 5 6 7" *)
  wire [7:0] mul_out;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_1.v:21.12-21.20" *)
  (* unused_bits = "0 1 2 3 4 5 6 7" *)
  wire [7:0] mux1_out;
  (* hdlname = "mux_layer1[0].mux_add_sub sel" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_1.v:27.17-32.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:2.16-2.19" *)
  (* unused_bits = "0" *)
  wire \mux_layer1[0].mux_add_sub.sel ;
  (* hdlname = "mux_layer1[0].mux_mul_div sel" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_1.v:33.17-38.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:2.16-2.19" *)
  (* unused_bits = "0" *)
  wire \mux_layer1[0].mux_mul_div.sel ;
  (* hdlname = "mux_layer1[1].mux_add_sub sel" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_1.v:27.17-32.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:2.16-2.19" *)
  (* unused_bits = "0" *)
  wire \mux_layer1[1].mux_add_sub.sel ;
  (* hdlname = "mux_layer1[1].mux_mul_div sel" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_1.v:33.17-38.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:2.16-2.19" *)
  (* unused_bits = "0" *)
  wire \mux_layer1[1].mux_mul_div.sel ;
  (* hdlname = "mux_layer1[2].mux_add_sub in0" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_1.v:27.17-32.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:3.16-3.19" *)
  (* unused_bits = "0" *)
  wire \mux_layer1[2].mux_add_sub.in0 ;
  (* hdlname = "mux_layer1[2].mux_add_sub out" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_1.v:27.17-32.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:5.17-5.20" *)
  (* unused_bits = "0" *)
  wire \mux_layer1[2].mux_add_sub.out ;
  (* hdlname = "mux_layer1[2].mux_add_sub sel" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_1.v:27.17-32.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:2.16-2.19" *)
  (* unused_bits = "0" *)
  wire \mux_layer1[2].mux_add_sub.sel ;
  (* hdlname = "mux_layer1[2].mux_mul_div sel" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_1.v:33.17-38.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:2.16-2.19" *)
  (* unused_bits = "0" *)
  wire \mux_layer1[2].mux_mul_div.sel ;
  (* hdlname = "mux_layer1[3].mux_add_sub in0" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_1.v:27.17-32.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:3.16-3.19" *)
  (* unused_bits = "0" *)
  wire \mux_layer1[3].mux_add_sub.in0 ;
  (* hdlname = "mux_layer1[3].mux_add_sub out" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_1.v:27.17-32.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:5.17-5.20" *)
  (* unused_bits = "0" *)
  wire \mux_layer1[3].mux_add_sub.out ;
  (* hdlname = "mux_layer1[3].mux_add_sub sel" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_1.v:27.17-32.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:2.16-2.19" *)
  (* unused_bits = "0" *)
  wire \mux_layer1[3].mux_add_sub.sel ;
  (* hdlname = "mux_layer1[3].mux_mul_div in0" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_1.v:33.17-38.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:3.16-3.19" *)
  (* unused_bits = "0" *)
  wire \mux_layer1[3].mux_mul_div.in0 ;
  (* hdlname = "mux_layer1[3].mux_mul_div sel" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_1.v:33.17-38.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:2.16-2.19" *)
  (* unused_bits = "0" *)
  wire \mux_layer1[3].mux_mul_div.sel ;
  (* hdlname = "mux_layer1[4].mux_add_sub sel" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_1.v:27.17-32.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:2.16-2.19" *)
  (* unused_bits = "0" *)
  wire \mux_layer1[4].mux_add_sub.sel ;
  (* hdlname = "mux_layer1[4].mux_mul_div sel" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_1.v:33.17-38.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:2.16-2.19" *)
  (* unused_bits = "0" *)
  wire \mux_layer1[4].mux_mul_div.sel ;
  (* hdlname = "mux_layer1[5].mux_add_sub sel" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_1.v:27.17-32.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:2.16-2.19" *)
  (* unused_bits = "0" *)
  wire \mux_layer1[5].mux_add_sub.sel ;
  (* hdlname = "mux_layer1[5].mux_mul_div sel" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_1.v:33.17-38.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:2.16-2.19" *)
  (* unused_bits = "0" *)
  wire \mux_layer1[5].mux_mul_div.sel ;
  (* hdlname = "mux_layer1[6].mux_add_sub sel" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_1.v:27.17-32.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:2.16-2.19" *)
  (* unused_bits = "0" *)
  wire \mux_layer1[6].mux_add_sub.sel ;
  (* hdlname = "mux_layer1[6].mux_mul_div sel" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_1.v:33.17-38.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:2.16-2.19" *)
  (* unused_bits = "0" *)
  wire \mux_layer1[6].mux_mul_div.sel ;
  (* hdlname = "mux_layer1[7].mux_add_sub sel" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_1.v:27.17-32.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:2.16-2.19" *)
  (* unused_bits = "0" *)
  wire \mux_layer1[7].mux_add_sub.sel ;
  (* hdlname = "mux_layer1[7].mux_mul_div sel" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_1.v:33.17-38.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:2.16-2.19" *)
  (* unused_bits = "0" *)
  wire \mux_layer1[7].mux_mul_div.sel ;
  (* hdlname = "mux_layer2[0].mux_final out" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_1.v:45.17-50.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:5.17-5.20" *)
  wire \mux_layer2[0].mux_final.out ;
  (* hdlname = "mux_layer2[0].mux_final sel" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_1.v:45.17-50.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:2.16-2.19" *)
  (* unused_bits = "0" *)
  wire \mux_layer2[0].mux_final.sel ;
  (* hdlname = "mux_layer2[1].mux_final out" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_1.v:45.17-50.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:5.17-5.20" *)
  wire \mux_layer2[1].mux_final.out ;
  (* hdlname = "mux_layer2[1].mux_final sel" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_1.v:45.17-50.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:2.16-2.19" *)
  (* unused_bits = "0" *)
  wire \mux_layer2[1].mux_final.sel ;
  (* hdlname = "mux_layer2[2].mux_final in0" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_1.v:45.17-50.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:3.16-3.19" *)
  (* unused_bits = "0" *)
  wire \mux_layer2[2].mux_final.in0 ;
  (* hdlname = "mux_layer2[2].mux_final out" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_1.v:45.17-50.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:5.17-5.20" *)
  wire \mux_layer2[2].mux_final.out ;
  (* hdlname = "mux_layer2[2].mux_final sel" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_1.v:45.17-50.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:2.16-2.19" *)
  (* unused_bits = "0" *)
  wire \mux_layer2[2].mux_final.sel ;
  (* hdlname = "mux_layer2[3].mux_final in0" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_1.v:45.17-50.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:3.16-3.19" *)
  (* unused_bits = "0" *)
  wire \mux_layer2[3].mux_final.in0 ;
  (* hdlname = "mux_layer2[3].mux_final out" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_1.v:45.17-50.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:5.17-5.20" *)
  wire \mux_layer2[3].mux_final.out ;
  (* hdlname = "mux_layer2[3].mux_final sel" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_1.v:45.17-50.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:2.16-2.19" *)
  (* unused_bits = "0" *)
  wire \mux_layer2[3].mux_final.sel ;
  (* hdlname = "mux_layer2[4].mux_final out" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_1.v:45.17-50.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:5.17-5.20" *)
  wire \mux_layer2[4].mux_final.out ;
  (* hdlname = "mux_layer2[4].mux_final sel" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_1.v:45.17-50.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:2.16-2.19" *)
  (* unused_bits = "0" *)
  wire \mux_layer2[4].mux_final.sel ;
  (* hdlname = "mux_layer2[5].mux_final out" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_1.v:45.17-50.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:5.17-5.20" *)
  wire \mux_layer2[5].mux_final.out ;
  (* hdlname = "mux_layer2[5].mux_final sel" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_1.v:45.17-50.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:2.16-2.19" *)
  (* unused_bits = "0" *)
  wire \mux_layer2[5].mux_final.sel ;
  (* hdlname = "mux_layer2[6].mux_final out" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_1.v:45.17-50.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:5.17-5.20" *)
  wire \mux_layer2[6].mux_final.out ;
  (* hdlname = "mux_layer2[6].mux_final sel" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_1.v:45.17-50.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:2.16-2.19" *)
  (* unused_bits = "0" *)
  wire \mux_layer2[6].mux_final.sel ;
  (* hdlname = "mux_layer2[7].mux_final out" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_1.v:45.17-50.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:5.17-5.20" *)
  wire \mux_layer2[7].mux_final.out ;
  (* hdlname = "mux_layer2[7].mux_final sel" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_1.v:45.17-50.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:2.16-2.19" *)
  (* unused_bits = "0" *)
  wire \mux_layer2[7].mux_final.sel ;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_1.v:4.22-4.24" *)
  input [1:0] op;
  wire [1:0] op;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_1.v:2.22-2.24" *)
  input [7:0] rs;
  wire [7:0] rs;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_1.v:3.22-3.24" *)
  input [7:0] rt;
  wire [7:0] rt;
  (* hdlname = "u_adder a" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_1.v:15.7-15.45|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/rca8.v:1.26-1.27" *)
  (* unused_bits = "0 1 2 3 4 5 6 7" *)
  wire [7:0] \u_adder.a ;
  (* hdlname = "u_adder b" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_1.v:15.7-15.45|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/rca8.v:1.41-1.42" *)
  (* unused_bits = "0 1 2 3 4 5 6 7" *)
  wire [7:0] \u_adder.b ;
  (* hdlname = "u_div a" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_1.v:18.8-18.49|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:1.27-1.28" *)
  (* unused_bits = "0 1 2 3 4 5 6 7" *)
  wire [7:0] \u_div.a ;
  (* hdlname = "u_div b" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_1.v:18.8-18.49|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:1.42-1.43" *)
  (* unused_bits = "0 1 2 3 4 5 6 7" *)
  wire [7:0] \u_div.b ;
  (* hdlname = "u_mul a" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_1.v:17.10-17.47|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/amu16.v:1.29-1.30" *)
  (* unused_bits = "0 1 2 3 4 5 6 7" *)
  wire [7:0] \u_mul.a ;
  (* hdlname = "u_mul b" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_1.v:17.10-17.47|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/amu16.v:1.44-1.45" *)
  (* unused_bits = "0 1 2 3 4 5 6 7" *)
  wire [7:0] \u_mul.b ;
  (* hdlname = "u_sub a" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_1.v:16.7-16.44|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/rbs8.v:1.26-1.27" *)
  (* unused_bits = "0 1 2 3 4 5 6 7" *)
  wire [7:0] \u_sub.a ;
  (* hdlname = "u_sub b" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_1.v:16.7-16.44|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/rbs8.v:1.41-1.42" *)
  (* unused_bits = "0 1 2 3 4 5 6 7" *)
  wire [7:0] \u_sub.b ;
  assign add_out[3:2] = { \mux_layer1[3].mux_add_sub.in0 , \mux_layer1[2].mux_add_sub.in0  };
  assign alu_out = 8'h00;
  assign mul_out[3] = \mux_layer1[3].mux_mul_div.in0 ;
  assign mux1_out[3:2] = { \mux_layer1[3].mux_add_sub.out , \mux_layer1[2].mux_add_sub.out  };
  assign \mux_layer1[0].mux_add_sub.sel  = op[0];
  assign \mux_layer1[0].mux_mul_div.sel  = op[0];
  assign \mux_layer1[1].mux_add_sub.sel  = op[0];
  assign \mux_layer1[1].mux_mul_div.sel  = op[0];
  assign \mux_layer1[2].mux_add_sub.sel  = op[0];
  assign \mux_layer1[2].mux_mul_div.sel  = op[0];
  assign \mux_layer1[3].mux_add_sub.sel  = op[0];
  assign \mux_layer1[3].mux_mul_div.sel  = op[0];
  assign \mux_layer1[4].mux_add_sub.sel  = op[0];
  assign \mux_layer1[4].mux_mul_div.sel  = op[0];
  assign \mux_layer1[5].mux_add_sub.sel  = op[0];
  assign \mux_layer1[5].mux_mul_div.sel  = op[0];
  assign \mux_layer1[6].mux_add_sub.sel  = op[0];
  assign \mux_layer1[6].mux_mul_div.sel  = op[0];
  assign \mux_layer1[7].mux_add_sub.sel  = op[0];
  assign \mux_layer1[7].mux_mul_div.sel  = op[0];
  assign \mux_layer2[0].mux_final.out  = 1'h0;
  assign \mux_layer2[0].mux_final.sel  = op[1];
  assign \mux_layer2[1].mux_final.out  = 1'h0;
  assign \mux_layer2[1].mux_final.sel  = op[1];
  assign \mux_layer2[2].mux_final.in0  = \mux_layer1[2].mux_add_sub.out ;
  assign \mux_layer2[2].mux_final.out  = 1'h0;
  assign \mux_layer2[2].mux_final.sel  = op[1];
  assign \mux_layer2[3].mux_final.in0  = \mux_layer1[3].mux_add_sub.out ;
  assign \mux_layer2[3].mux_final.out  = 1'h0;
  assign \mux_layer2[3].mux_final.sel  = op[1];
  assign \mux_layer2[4].mux_final.out  = 1'h0;
  assign \mux_layer2[4].mux_final.sel  = op[1];
  assign \mux_layer2[5].mux_final.out  = 1'h0;
  assign \mux_layer2[5].mux_final.sel  = op[1];
  assign \mux_layer2[6].mux_final.out  = 1'h0;
  assign \mux_layer2[6].mux_final.sel  = op[1];
  assign \mux_layer2[7].mux_final.out  = 1'h0;
  assign \mux_layer2[7].mux_final.sel  = op[1];
  assign \u_adder.a  = rs;
  assign \u_adder.b  = rt;
  assign \u_div.a  = rs;
  assign \u_div.b  = rt;
  assign \u_mul.a  = rs;
  assign \u_mul.b  = rt;
  assign \u_sub.a  = rs;
  assign \u_sub.b  = rt;
endmodule

(* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:1.1-1202.10" *)
module arrdiv(a, b, arrdiv_out);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:1.27-1.28" *)
  input [7:0] a;
  wire [7:0] a;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:35.8-35.36" *)
  wire arrdiv_mux2to10_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:117.8-117.37" *)
  wire arrdiv_mux2to110_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:121.8-121.37" *)
  wire arrdiv_mux2to111_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:125.8-125.37" *)
  wire arrdiv_mux2to112_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:129.8-129.37" *)
  wire arrdiv_mux2to113_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:187.8-187.37" *)
  wire arrdiv_mux2to114_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:191.8-191.37" *)
  wire arrdiv_mux2to115_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:195.8-195.37" *)
  wire arrdiv_mux2to116_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:199.8-199.37" *)
  wire arrdiv_mux2to117_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:203.8-203.37" *)
  wire arrdiv_mux2to118_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:207.8-207.37" *)
  wire arrdiv_mux2to119_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:38.8-38.36" *)
  wire arrdiv_mux2to11_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:211.8-211.37" *)
  wire arrdiv_mux2to120_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:269.8-269.37" *)
  wire arrdiv_mux2to121_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:273.8-273.37" *)
  wire arrdiv_mux2to122_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:277.8-277.37" *)
  wire arrdiv_mux2to123_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:281.8-281.37" *)
  wire arrdiv_mux2to124_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:285.8-285.37" *)
  wire arrdiv_mux2to125_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:289.8-289.37" *)
  wire arrdiv_mux2to126_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:293.8-293.37" *)
  wire arrdiv_mux2to127_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:351.8-351.37" *)
  wire arrdiv_mux2to128_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:355.8-355.37" *)
  wire arrdiv_mux2to129_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:40.8-40.36" *)
  wire arrdiv_mux2to12_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:359.8-359.37" *)
  wire arrdiv_mux2to130_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:363.8-363.37" *)
  wire arrdiv_mux2to131_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:367.8-367.37" *)
  wire arrdiv_mux2to132_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:371.8-371.37" *)
  wire arrdiv_mux2to133_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:375.8-375.37" *)
  wire arrdiv_mux2to134_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:433.8-433.37" *)
  wire arrdiv_mux2to135_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:437.8-437.37" *)
  wire arrdiv_mux2to136_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:441.8-441.37" *)
  wire arrdiv_mux2to137_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:445.8-445.37" *)
  wire arrdiv_mux2to138_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:449.8-449.37" *)
  wire arrdiv_mux2to139_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:42.8-42.36" *)
  wire arrdiv_mux2to13_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:453.8-453.37" *)
  wire arrdiv_mux2to140_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:457.8-457.37" *)
  wire arrdiv_mux2to141_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:515.8-515.37" *)
  wire arrdiv_mux2to142_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:519.8-519.37" *)
  wire arrdiv_mux2to143_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:523.8-523.37" *)
  wire arrdiv_mux2to144_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:527.8-527.37" *)
  wire arrdiv_mux2to145_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:531.8-531.37" *)
  wire arrdiv_mux2to146_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:535.8-535.37" *)
  wire arrdiv_mux2to147_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:539.8-539.37" *)
  wire arrdiv_mux2to148_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:44.8-44.36" *)
  wire arrdiv_mux2to14_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:46.8-46.36" *)
  wire arrdiv_mux2to15_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:48.8-48.36" *)
  wire arrdiv_mux2to16_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:105.8-105.36" *)
  wire arrdiv_mux2to17_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:109.8-109.36" *)
  wire arrdiv_mux2to18_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:113.8-113.36" *)
  wire arrdiv_mux2to19_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:50.8-50.19" *)
  wire arrdiv_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:132.8-132.19" *)
  wire arrdiv_not1;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:214.8-214.19" *)
  wire arrdiv_not2;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:296.8-296.19" *)
  wire arrdiv_not3;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:378.8-378.19" *)
  wire arrdiv_not4;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:460.8-460.19" *)
  wire arrdiv_not5;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:542.8-542.19" *)
  wire arrdiv_not6;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:596.8-596.19" *)
  wire arrdiv_not7;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:1.58-1.68" *)
  output [7:0] arrdiv_out;
  wire [7:0] arrdiv_out;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:1.42-1.43" *)
  input [7:0] b;
  wire [7:0] b;
  sky130_fd_sc_hd__clkinv_1 _136_ (
    .A(b[1]),
    .Y(_066_)
  );
  sky130_fd_sc_hd__clkinv_1 _137_ (
    .A(b[3]),
    .Y(_067_)
  );
  sky130_fd_sc_hd__clkinv_1 _138_ (
    .A(b[7]),
    .Y(_068_)
  );
  sky130_fd_sc_hd__clkinv_1 _139_ (
    .A(b[0]),
    .Y(_069_)
  );
  sky130_fd_sc_hd__nor2_1 _140_ (
    .A(b[6]),
    .B(b[7]),
    .Y(_070_)
  );
  sky130_fd_sc_hd__nor3_1 _141_ (
    .A(b[5]),
    .B(b[6]),
    .C(b[7]),
    .Y(_071_)
  );
  sky130_fd_sc_hd__or4_1 _142_ (
    .A(b[4]),
    .B(b[5]),
    .C(b[6]),
    .D(b[7]),
    .X(_072_)
  );
  sky130_fd_sc_hd__or3_1 _143_ (
    .A(b[2]),
    .B(b[3]),
    .C(_072_),
    .X(_073_)
  );
  sky130_fd_sc_hd__nor4_1 _144_ (
    .A(b[1]),
    .B(b[2]),
    .C(b[3]),
    .D(_072_),
    .Y(_074_)
  );
  sky130_fd_sc_hd__o21a_1 _145_ (
    .A1(a[7]),
    .A2(_069_),
    .B1(_074_),
    .X(arrdiv_mux2to10_mux2to1_not0)
  );
  sky130_fd_sc_hd__nor2_1 _146_ (
    .A(a[6]),
    .B(_069_),
    .Y(_075_)
  );
  sky130_fd_sc_hd__nor2_1 _147_ (
    .A(b[1]),
    .B(_075_),
    .Y(_076_)
  );
  sky130_fd_sc_hd__and3_1 _148_ (
    .A(a[7]),
    .B(_069_),
    .C(_074_),
    .X(_077_)
  );
  sky130_fd_sc_hd__a21boi_0 _149_ (
    .A1(b[0]),
    .A2(_074_),
    .B1_N(a[7]),
    .Y(_078_)
  );
  sky130_fd_sc_hd__nor2_1 _150_ (
    .A(_076_),
    .B(_078_),
    .Y(_079_)
  );
  sky130_fd_sc_hd__a21o_1 _151_ (
    .A1(b[1]),
    .A2(_075_),
    .B1(_073_),
    .X(_080_)
  );
  sky130_fd_sc_hd__nor2_1 _152_ (
    .A(_079_),
    .B(_080_),
    .Y(arrdiv_mux2to110_mux2to1_not0)
  );
  sky130_fd_sc_hd__a21oi_1 _153_ (
    .A1(_078_),
    .A2(_080_),
    .B1(_077_),
    .Y(_081_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _154_ (
    .A(b[2]),
    .SLEEP(_081_),
    .X(_082_)
  );
  sky130_fd_sc_hd__o31ai_1 _155_ (
    .A1(_069_),
    .A2(_073_),
    .A3(_079_),
    .B1(a[6]),
    .Y(_083_)
  );
  sky130_fd_sc_hd__xnor2_1 _156_ (
    .A(b[1]),
    .B(_083_),
    .Y(_084_)
  );
  sky130_fd_sc_hd__nor2_1 _157_ (
    .A(a[5]),
    .B(_069_),
    .Y(_085_)
  );
  sky130_fd_sc_hd__maj3_1 _158_ (
    .A(b[1]),
    .B(_083_),
    .C(_085_),
    .X(_086_)
  );
  sky130_fd_sc_hd__a211o_1 _159_ (
    .A1(b[2]),
    .A2(_081_),
    .B1(_072_),
    .C1(b[3]),
    .X(_087_)
  );
  sky130_fd_sc_hd__a21oi_1 _160_ (
    .A1(_082_),
    .A2(_086_),
    .B1(_087_),
    .Y(arrdiv_mux2to114_mux2to1_not0)
  );
  sky130_fd_sc_hd__o21bai_1 _161_ (
    .A1(_081_),
    .A2(arrdiv_mux2to114_mux2to1_not0),
    .B1_N(_077_),
    .Y(_088_)
  );
  sky130_fd_sc_hd__nand2_1 _162_ (
    .A(_067_),
    .B(_088_),
    .Y(_089_)
  );
  sky130_fd_sc_hd__xnor2_1 _163_ (
    .A(_084_),
    .B(_085_),
    .Y(_090_)
  );
  sky130_fd_sc_hd__mux2i_1 _164_ (
    .A0(_083_),
    .A1(_090_),
    .S(arrdiv_mux2to114_mux2to1_not0),
    .Y(_091_)
  );
  sky130_fd_sc_hd__clkinv_1 _165_ (
    .A(_091_),
    .Y(_092_)
  );
  sky130_fd_sc_hd__xnor2_1 _166_ (
    .A(b[2]),
    .B(_091_),
    .Y(_093_)
  );
  sky130_fd_sc_hd__a211oi_1 _167_ (
    .A1(_082_),
    .A2(_086_),
    .B1(_087_),
    .C1(_069_),
    .Y(_094_)
  );
  sky130_fd_sc_hd__xnor2_1 _168_ (
    .A(a[5]),
    .B(_094_),
    .Y(_095_)
  );
  sky130_fd_sc_hd__xnor2_1 _169_ (
    .A(b[1]),
    .B(_095_),
    .Y(_096_)
  );
  sky130_fd_sc_hd__nor2_1 _170_ (
    .A(a[4]),
    .B(_069_),
    .Y(_097_)
  );
  sky130_fd_sc_hd__maj3_1 _171_ (
    .A(b[1]),
    .B(_095_),
    .C(_097_),
    .X(_098_)
  );
  sky130_fd_sc_hd__maj3_1 _172_ (
    .A(b[2]),
    .B(_092_),
    .C(_098_),
    .X(_099_)
  );
  sky130_fd_sc_hd__o21bai_1 _173_ (
    .A1(_067_),
    .A2(_088_),
    .B1_N(_072_),
    .Y(_100_)
  );
  sky130_fd_sc_hd__a21o_1 _174_ (
    .A1(_089_),
    .A2(_099_),
    .B1(_100_),
    .X(_101_)
  );
  sky130_fd_sc_hd__clkinv_1 _175_ (
    .A(_101_),
    .Y(arrdiv_mux2to121_mux2to1_not0)
  );
  sky130_fd_sc_hd__a21oi_1 _176_ (
    .A1(_088_),
    .A2(_101_),
    .B1(_077_),
    .Y(_102_)
  );
  sky130_fd_sc_hd__nor2_1 _177_ (
    .A(b[4]),
    .B(_102_),
    .Y(_103_)
  );
  sky130_fd_sc_hd__xnor2_1 _178_ (
    .A(_093_),
    .B(_098_),
    .Y(_104_)
  );
  sky130_fd_sc_hd__mux2i_1 _179_ (
    .A0(_091_),
    .A1(_104_),
    .S(arrdiv_mux2to121_mux2to1_not0),
    .Y(_105_)
  );
  sky130_fd_sc_hd__xnor2_1 _180_ (
    .A(b[3]),
    .B(_105_),
    .Y(_106_)
  );
  sky130_fd_sc_hd__clkinv_1 _181_ (
    .A(_106_),
    .Y(_107_)
  );
  sky130_fd_sc_hd__xnor2_1 _182_ (
    .A(_096_),
    .B(_097_),
    .Y(_108_)
  );
  sky130_fd_sc_hd__mux2i_1 _183_ (
    .A0(_095_),
    .A1(_108_),
    .S(arrdiv_mux2to121_mux2to1_not0),
    .Y(_109_)
  );
  sky130_fd_sc_hd__clkinv_1 _184_ (
    .A(_109_),
    .Y(_110_)
  );
  sky130_fd_sc_hd__xnor2_1 _185_ (
    .A(b[2]),
    .B(_109_),
    .Y(_111_)
  );
  sky130_fd_sc_hd__a211oi_1 _186_ (
    .A1(_089_),
    .A2(_099_),
    .B1(_100_),
    .C1(_069_),
    .Y(_112_)
  );
  sky130_fd_sc_hd__xnor2_1 _187_ (
    .A(a[4]),
    .B(_112_),
    .Y(_113_)
  );
  sky130_fd_sc_hd__xnor2_1 _188_ (
    .A(b[1]),
    .B(_113_),
    .Y(_114_)
  );
  sky130_fd_sc_hd__nor2_1 _189_ (
    .A(a[3]),
    .B(_069_),
    .Y(_115_)
  );
  sky130_fd_sc_hd__maj3_1 _190_ (
    .A(b[1]),
    .B(_113_),
    .C(_115_),
    .X(_116_)
  );
  sky130_fd_sc_hd__maj3_1 _191_ (
    .A(b[2]),
    .B(_110_),
    .C(_116_),
    .X(_117_)
  );
  sky130_fd_sc_hd__a22o_1 _192_ (
    .A1(b[4]),
    .A2(_102_),
    .B1(_105_),
    .B2(b[3]),
    .X(_118_)
  );
  sky130_fd_sc_hd__a21oi_1 _193_ (
    .A1(_107_),
    .A2(_117_),
    .B1(_118_),
    .Y(_119_)
  );
  sky130_fd_sc_hd__o21ai_0 _194_ (
    .A1(_103_),
    .A2(_119_),
    .B1(_071_),
    .Y(_120_)
  );
  sky130_fd_sc_hd__clkinv_1 _195_ (
    .A(_120_),
    .Y(arrdiv_mux2to128_mux2to1_not0)
  );
  sky130_fd_sc_hd__a31oi_1 _196_ (
    .A1(_088_),
    .A2(_101_),
    .A3(_120_),
    .B1(_077_),
    .Y(_121_)
  );
  sky130_fd_sc_hd__nor2_1 _197_ (
    .A(b[5]),
    .B(_121_),
    .Y(_122_)
  );
  sky130_fd_sc_hd__xnor2_1 _198_ (
    .A(_107_),
    .B(_117_),
    .Y(_123_)
  );
  sky130_fd_sc_hd__nand2_1 _199_ (
    .A(_105_),
    .B(_120_),
    .Y(_124_)
  );
  sky130_fd_sc_hd__o21ai_0 _200_ (
    .A1(_120_),
    .A2(_123_),
    .B1(_124_),
    .Y(_125_)
  );
  sky130_fd_sc_hd__xnor2_1 _201_ (
    .A(b[4]),
    .B(_125_),
    .Y(_126_)
  );
  sky130_fd_sc_hd__clkinv_1 _202_ (
    .A(_126_),
    .Y(_127_)
  );
  sky130_fd_sc_hd__xnor2_1 _203_ (
    .A(_111_),
    .B(_116_),
    .Y(_128_)
  );
  sky130_fd_sc_hd__mux2i_1 _204_ (
    .A0(_128_),
    .A1(_109_),
    .S(_120_),
    .Y(_129_)
  );
  sky130_fd_sc_hd__xnor2_1 _205_ (
    .A(_067_),
    .B(_129_),
    .Y(_130_)
  );
  sky130_fd_sc_hd__xnor2_1 _206_ (
    .A(_114_),
    .B(_115_),
    .Y(_131_)
  );
  sky130_fd_sc_hd__mux2_1 _207_ (
    .A0(_131_),
    .A1(_113_),
    .S(_120_),
    .X(_132_)
  );
  sky130_fd_sc_hd__xor2_1 _208_ (
    .A(b[2]),
    .B(_132_),
    .X(_133_)
  );
  sky130_fd_sc_hd__o211ai_1 _209_ (
    .A1(_103_),
    .A2(_119_),
    .B1(b[0]),
    .C1(_071_),
    .Y(_134_)
  );
  sky130_fd_sc_hd__xor2_1 _210_ (
    .A(a[3]),
    .B(_134_),
    .X(_135_)
  );
  sky130_fd_sc_hd__xnor2_1 _211_ (
    .A(_066_),
    .B(_135_),
    .Y(_000_)
  );
  sky130_fd_sc_hd__nor2_1 _212_ (
    .A(a[2]),
    .B(_069_),
    .Y(_001_)
  );
  sky130_fd_sc_hd__maj3_1 _213_ (
    .A(b[1]),
    .B(_135_),
    .C(_001_),
    .X(_002_)
  );
  sky130_fd_sc_hd__and2_0 _214_ (
    .A(_133_),
    .B(_002_),
    .X(_003_)
  );
  sky130_fd_sc_hd__maj3_1 _215_ (
    .A(b[2]),
    .B(_132_),
    .C(_002_),
    .X(_004_)
  );
  sky130_fd_sc_hd__maj3_1 _216_ (
    .A(b[3]),
    .B(_129_),
    .C(_004_),
    .X(_005_)
  );
  sky130_fd_sc_hd__a22o_1 _217_ (
    .A1(b[5]),
    .A2(_121_),
    .B1(_125_),
    .B2(b[4]),
    .X(_006_)
  );
  sky130_fd_sc_hd__a21oi_1 _218_ (
    .A1(_127_),
    .A2(_005_),
    .B1(_006_),
    .Y(_007_)
  );
  sky130_fd_sc_hd__o21ai_0 _219_ (
    .A1(_122_),
    .A2(_007_),
    .B1(_070_),
    .Y(_008_)
  );
  sky130_fd_sc_hd__clkinv_1 _220_ (
    .A(_008_),
    .Y(arrdiv_mux2to135_mux2to1_not0)
  );
  sky130_fd_sc_hd__nor2_1 _221_ (
    .A(_121_),
    .B(arrdiv_mux2to135_mux2to1_not0),
    .Y(_009_)
  );
  sky130_fd_sc_hd__nor2_1 _222_ (
    .A(_077_),
    .B(_009_),
    .Y(_010_)
  );
  sky130_fd_sc_hd__nor2_1 _223_ (
    .A(b[6]),
    .B(_010_),
    .Y(_011_)
  );
  sky130_fd_sc_hd__xnor2_1 _224_ (
    .A(_127_),
    .B(_005_),
    .Y(_012_)
  );
  sky130_fd_sc_hd__nand2_1 _225_ (
    .A(_125_),
    .B(_008_),
    .Y(_013_)
  );
  sky130_fd_sc_hd__o21ai_0 _226_ (
    .A1(_008_),
    .A2(_012_),
    .B1(_013_),
    .Y(_014_)
  );
  sky130_fd_sc_hd__xnor2_1 _227_ (
    .A(b[5]),
    .B(_014_),
    .Y(_015_)
  );
  sky130_fd_sc_hd__clkinv_1 _228_ (
    .A(_015_),
    .Y(_016_)
  );
  sky130_fd_sc_hd__xnor2_1 _229_ (
    .A(_130_),
    .B(_004_),
    .Y(_017_)
  );
  sky130_fd_sc_hd__nand2_1 _230_ (
    .A(_129_),
    .B(_008_),
    .Y(_018_)
  );
  sky130_fd_sc_hd__o21ai_0 _231_ (
    .A1(_008_),
    .A2(_017_),
    .B1(_018_),
    .Y(_019_)
  );
  sky130_fd_sc_hd__xor2_1 _232_ (
    .A(b[4]),
    .B(_019_),
    .X(_020_)
  );
  sky130_fd_sc_hd__nor2_1 _233_ (
    .A(_133_),
    .B(_002_),
    .Y(_021_)
  );
  sky130_fd_sc_hd__nand2_1 _234_ (
    .A(_132_),
    .B(_008_),
    .Y(_022_)
  );
  sky130_fd_sc_hd__o31ai_1 _235_ (
    .A1(_003_),
    .A2(_008_),
    .A3(_021_),
    .B1(_022_),
    .Y(_023_)
  );
  sky130_fd_sc_hd__xnor2_1 _236_ (
    .A(b[3]),
    .B(_023_),
    .Y(_024_)
  );
  sky130_fd_sc_hd__xnor2_1 _237_ (
    .A(_000_),
    .B(_001_),
    .Y(_025_)
  );
  sky130_fd_sc_hd__nand2_1 _238_ (
    .A(_135_),
    .B(_008_),
    .Y(_026_)
  );
  sky130_fd_sc_hd__o21ai_0 _239_ (
    .A1(_008_),
    .A2(_025_),
    .B1(_026_),
    .Y(_027_)
  );
  sky130_fd_sc_hd__xnor2_1 _240_ (
    .A(b[2]),
    .B(_027_),
    .Y(_028_)
  );
  sky130_fd_sc_hd__o211ai_1 _241_ (
    .A1(_122_),
    .A2(_007_),
    .B1(b[0]),
    .C1(_070_),
    .Y(_029_)
  );
  sky130_fd_sc_hd__xor2_1 _242_ (
    .A(a[2]),
    .B(_029_),
    .X(_030_)
  );
  sky130_fd_sc_hd__xnor2_1 _243_ (
    .A(b[1]),
    .B(_030_),
    .Y(_031_)
  );
  sky130_fd_sc_hd__nor2_1 _244_ (
    .A(a[1]),
    .B(_069_),
    .Y(_032_)
  );
  sky130_fd_sc_hd__nand2b_1 _245_ (
    .A_N(a[1]),
    .B(b[0]),
    .Y(_033_)
  );
  sky130_fd_sc_hd__maj3_1 _246_ (
    .A(b[1]),
    .B(_030_),
    .C(_032_),
    .X(_034_)
  );
  sky130_fd_sc_hd__maj3_1 _247_ (
    .A(b[2]),
    .B(_027_),
    .C(_034_),
    .X(_035_)
  );
  sky130_fd_sc_hd__maj3_1 _248_ (
    .A(b[3]),
    .B(_023_),
    .C(_035_),
    .X(_036_)
  );
  sky130_fd_sc_hd__maj3_1 _249_ (
    .A(b[4]),
    .B(_019_),
    .C(_036_),
    .X(_037_)
  );
  sky130_fd_sc_hd__a22o_1 _250_ (
    .A1(b[6]),
    .A2(_010_),
    .B1(_014_),
    .B2(b[5]),
    .X(_038_)
  );
  sky130_fd_sc_hd__a21oi_1 _251_ (
    .A1(_016_),
    .A2(_037_),
    .B1(_038_),
    .Y(_039_)
  );
  sky130_fd_sc_hd__o21ai_0 _252_ (
    .A1(_011_),
    .A2(_039_),
    .B1(_068_),
    .Y(_040_)
  );
  sky130_fd_sc_hd__clkinv_1 _253_ (
    .A(_040_),
    .Y(arrdiv_mux2to142_mux2to1_not0)
  );
  sky130_fd_sc_hd__a21oi_1 _254_ (
    .A1(_009_),
    .A2(_040_),
    .B1(_077_),
    .Y(_041_)
  );
  sky130_fd_sc_hd__o211ai_1 _255_ (
    .A1(_011_),
    .A2(_039_),
    .B1(_068_),
    .C1(b[0]),
    .Y(_042_)
  );
  sky130_fd_sc_hd__a2bb2oi_1 _256_ (
    .A1_N(_033_),
    .A2_N(_040_),
    .B1(_042_),
    .B2(a[1]),
    .Y(_043_)
  );
  sky130_fd_sc_hd__nor3_1 _257_ (
    .A(_066_),
    .B(a[0]),
    .C(_069_),
    .Y(_044_)
  );
  sky130_fd_sc_hd__o21ai_0 _258_ (
    .A1(a[0]),
    .A2(_069_),
    .B1(_066_),
    .Y(_045_)
  );
  sky130_fd_sc_hd__xnor2_1 _259_ (
    .A(_031_),
    .B(_032_),
    .Y(_046_)
  );
  sky130_fd_sc_hd__mux2_1 _260_ (
    .A0(_046_),
    .A1(_030_),
    .S(_040_),
    .X(_047_)
  );
  sky130_fd_sc_hd__o221ai_1 _261_ (
    .A1(_043_),
    .A2(_044_),
    .B1(_047_),
    .B2(b[2]),
    .C1(_045_),
    .Y(_048_)
  );
  sky130_fd_sc_hd__xnor2_1 _262_ (
    .A(_028_),
    .B(_034_),
    .Y(_049_)
  );
  sky130_fd_sc_hd__mux2_1 _263_ (
    .A0(_049_),
    .A1(_027_),
    .S(_040_),
    .X(_050_)
  );
  sky130_fd_sc_hd__a22oi_1 _264_ (
    .A1(b[2]),
    .A2(_047_),
    .B1(_050_),
    .B2(b[3]),
    .Y(_051_)
  );
  sky130_fd_sc_hd__xnor2_1 _265_ (
    .A(_024_),
    .B(_035_),
    .Y(_052_)
  );
  sky130_fd_sc_hd__mux2_1 _266_ (
    .A0(_052_),
    .A1(_023_),
    .S(_040_),
    .X(_053_)
  );
  sky130_fd_sc_hd__o22ai_1 _267_ (
    .A1(b[3]),
    .A2(_050_),
    .B1(_053_),
    .B2(b[4]),
    .Y(_054_)
  );
  sky130_fd_sc_hd__a21o_1 _268_ (
    .A1(_048_),
    .A2(_051_),
    .B1(_054_),
    .X(_055_)
  );
  sky130_fd_sc_hd__xnor2_1 _269_ (
    .A(_020_),
    .B(_036_),
    .Y(_056_)
  );
  sky130_fd_sc_hd__nand2_1 _270_ (
    .A(_019_),
    .B(_040_),
    .Y(_057_)
  );
  sky130_fd_sc_hd__o21ai_0 _271_ (
    .A1(_040_),
    .A2(_056_),
    .B1(_057_),
    .Y(_058_)
  );
  sky130_fd_sc_hd__a22oi_1 _272_ (
    .A1(b[4]),
    .A2(_053_),
    .B1(_058_),
    .B2(b[5]),
    .Y(_059_)
  );
  sky130_fd_sc_hd__xnor2_1 _273_ (
    .A(_016_),
    .B(_037_),
    .Y(_060_)
  );
  sky130_fd_sc_hd__nand2_1 _274_ (
    .A(_014_),
    .B(_040_),
    .Y(_061_)
  );
  sky130_fd_sc_hd__o21ai_0 _275_ (
    .A1(_040_),
    .A2(_060_),
    .B1(_061_),
    .Y(_062_)
  );
  sky130_fd_sc_hd__o22ai_1 _276_ (
    .A1(b[5]),
    .A2(_058_),
    .B1(_062_),
    .B2(b[6]),
    .Y(_063_)
  );
  sky130_fd_sc_hd__a21oi_1 _277_ (
    .A1(_055_),
    .A2(_059_),
    .B1(_063_),
    .Y(_064_)
  );
  sky130_fd_sc_hd__a22o_1 _278_ (
    .A1(b[7]),
    .A2(_041_),
    .B1(_062_),
    .B2(b[6]),
    .X(_065_)
  );
  sky130_fd_sc_hd__o22ai_1 _279_ (
    .A1(b[7]),
    .A2(_041_),
    .B1(_064_),
    .B2(_065_),
    .Y(arrdiv_not7)
  );
  assign arrdiv_mux2to111_mux2to1_not0 = arrdiv_mux2to110_mux2to1_not0;
  assign arrdiv_mux2to112_mux2to1_not0 = arrdiv_mux2to110_mux2to1_not0;
  assign arrdiv_mux2to113_mux2to1_not0 = arrdiv_mux2to110_mux2to1_not0;
  assign arrdiv_mux2to115_mux2to1_not0 = arrdiv_mux2to114_mux2to1_not0;
  assign arrdiv_mux2to116_mux2to1_not0 = arrdiv_mux2to114_mux2to1_not0;
  assign arrdiv_mux2to117_mux2to1_not0 = arrdiv_mux2to114_mux2to1_not0;
  assign arrdiv_mux2to118_mux2to1_not0 = arrdiv_mux2to114_mux2to1_not0;
  assign arrdiv_mux2to119_mux2to1_not0 = arrdiv_mux2to114_mux2to1_not0;
  assign arrdiv_mux2to11_mux2to1_not0 = arrdiv_mux2to10_mux2to1_not0;
  assign arrdiv_mux2to120_mux2to1_not0 = arrdiv_mux2to114_mux2to1_not0;
  assign arrdiv_mux2to122_mux2to1_not0 = arrdiv_mux2to121_mux2to1_not0;
  assign arrdiv_mux2to123_mux2to1_not0 = arrdiv_mux2to121_mux2to1_not0;
  assign arrdiv_mux2to124_mux2to1_not0 = arrdiv_mux2to121_mux2to1_not0;
  assign arrdiv_mux2to125_mux2to1_not0 = arrdiv_mux2to121_mux2to1_not0;
  assign arrdiv_mux2to126_mux2to1_not0 = arrdiv_mux2to121_mux2to1_not0;
  assign arrdiv_mux2to127_mux2to1_not0 = arrdiv_mux2to121_mux2to1_not0;
  assign arrdiv_mux2to129_mux2to1_not0 = arrdiv_mux2to128_mux2to1_not0;
  assign arrdiv_mux2to12_mux2to1_not0 = arrdiv_mux2to10_mux2to1_not0;
  assign arrdiv_mux2to130_mux2to1_not0 = arrdiv_mux2to128_mux2to1_not0;
  assign arrdiv_mux2to131_mux2to1_not0 = arrdiv_mux2to128_mux2to1_not0;
  assign arrdiv_mux2to132_mux2to1_not0 = arrdiv_mux2to128_mux2to1_not0;
  assign arrdiv_mux2to133_mux2to1_not0 = arrdiv_mux2to128_mux2to1_not0;
  assign arrdiv_mux2to134_mux2to1_not0 = arrdiv_mux2to128_mux2to1_not0;
  assign arrdiv_mux2to136_mux2to1_not0 = arrdiv_mux2to135_mux2to1_not0;
  assign arrdiv_mux2to137_mux2to1_not0 = arrdiv_mux2to135_mux2to1_not0;
  assign arrdiv_mux2to138_mux2to1_not0 = arrdiv_mux2to135_mux2to1_not0;
  assign arrdiv_mux2to139_mux2to1_not0 = arrdiv_mux2to135_mux2to1_not0;
  assign arrdiv_mux2to13_mux2to1_not0 = arrdiv_mux2to10_mux2to1_not0;
  assign arrdiv_mux2to140_mux2to1_not0 = arrdiv_mux2to135_mux2to1_not0;
  assign arrdiv_mux2to141_mux2to1_not0 = arrdiv_mux2to135_mux2to1_not0;
  assign arrdiv_mux2to143_mux2to1_not0 = arrdiv_mux2to142_mux2to1_not0;
  assign arrdiv_mux2to144_mux2to1_not0 = arrdiv_mux2to142_mux2to1_not0;
  assign arrdiv_mux2to145_mux2to1_not0 = arrdiv_mux2to142_mux2to1_not0;
  assign arrdiv_mux2to146_mux2to1_not0 = arrdiv_mux2to142_mux2to1_not0;
  assign arrdiv_mux2to147_mux2to1_not0 = arrdiv_mux2to142_mux2to1_not0;
  assign arrdiv_mux2to148_mux2to1_not0 = arrdiv_mux2to142_mux2to1_not0;
  assign arrdiv_mux2to14_mux2to1_not0 = arrdiv_mux2to10_mux2to1_not0;
  assign arrdiv_mux2to15_mux2to1_not0 = arrdiv_mux2to10_mux2to1_not0;
  assign arrdiv_mux2to16_mux2to1_not0 = arrdiv_mux2to10_mux2to1_not0;
  assign arrdiv_mux2to17_mux2to1_not0 = arrdiv_mux2to110_mux2to1_not0;
  assign arrdiv_mux2to18_mux2to1_not0 = arrdiv_mux2to110_mux2to1_not0;
  assign arrdiv_mux2to19_mux2to1_not0 = arrdiv_mux2to110_mux2to1_not0;
  assign arrdiv_not0 = arrdiv_mux2to10_mux2to1_not0;
  assign arrdiv_not1 = arrdiv_mux2to110_mux2to1_not0;
  assign arrdiv_not2 = arrdiv_mux2to114_mux2to1_not0;
  assign arrdiv_not3 = arrdiv_mux2to121_mux2to1_not0;
  assign arrdiv_not4 = arrdiv_mux2to128_mux2to1_not0;
  assign arrdiv_not5 = arrdiv_mux2to135_mux2to1_not0;
  assign arrdiv_not6 = arrdiv_mux2to142_mux2to1_not0;
  assign arrdiv_out = { arrdiv_mux2to10_mux2to1_not0, arrdiv_mux2to110_mux2to1_not0, arrdiv_mux2to114_mux2to1_not0, arrdiv_mux2to121_mux2to1_not0, arrdiv_mux2to128_mux2to1_not0, arrdiv_mux2to135_mux2to1_not0, arrdiv_mux2to142_mux2to1_not0, arrdiv_not7 };
endmodule

(* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:1.1-23.10" *)
module mux2to1(sel, in0, in1, out);
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:3.16-3.19" *)
  input in0;
  wire in0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:4.16-4.19" *)
  input in1;
  wire in1;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:5.17-5.20" *)
  output out;
  wire out;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:2.16-2.19" *)
  input sel;
  wire sel;
  sky130_fd_sc_hd__mux2_1 _0_ (
    .A0(in0),
    .A1(in1),
    .S(sel),
    .X(out)
  );
endmodule

(* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/amu16.v:1.1-660.10" *)
module u_arrmul(a, b, u_arrmul_out);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/amu16.v:1.29-1.30" *)
  input [7:0] a;
  wire [7:0] a;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/amu16.v:1.44-1.45" *)
  input [7:0] b;
  wire [7:0] b;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/amu16.v:2.8-2.23" *)
  wire u_arrmul_and0_0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/amu16.v:283.8-283.30" *)
  wire u_arrmul_fa1_7_fa_xor1;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/amu16.v:289.8-289.30" *)
  wire u_arrmul_fa2_7_fa_xor1;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/amu16.v:295.8-295.30" *)
  wire u_arrmul_fa3_7_fa_xor1;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/amu16.v:301.8-301.30" *)
  wire u_arrmul_fa4_7_fa_xor1;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/amu16.v:307.8-307.30" *)
  wire u_arrmul_fa5_7_fa_xor1;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/amu16.v:313.8-313.30" *)
  wire u_arrmul_fa6_7_fa_xor1;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/amu16.v:321.8-321.29" *)
  wire u_arrmul_fa7_7_fa_or0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/amu16.v:319.8-319.30" *)
  wire u_arrmul_fa7_7_fa_xor1;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/amu16.v:11.8-11.30" *)
  wire u_arrmul_ha0_1_ha_xor0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/amu16.v:53.8-53.30" *)
  wire u_arrmul_ha0_2_ha_xor0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/amu16.v:98.8-98.30" *)
  wire u_arrmul_ha0_3_ha_xor0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/amu16.v:143.8-143.30" *)
  wire u_arrmul_ha0_4_ha_xor0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/amu16.v:188.8-188.30" *)
  wire u_arrmul_ha0_5_ha_xor0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/amu16.v:233.8-233.30" *)
  wire u_arrmul_ha0_6_ha_xor0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/amu16.v:278.8-278.30" *)
  wire u_arrmul_ha0_7_ha_xor0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/amu16.v:1.61-1.73" *)
  output [15:0] u_arrmul_out;
  wire [15:0] u_arrmul_out;
  sky130_fd_sc_hd__and2_0 _198_ (
    .A(a[0]),
    .B(b[0]),
    .X(u_arrmul_and0_0)
  );
  sky130_fd_sc_hd__nand4_1 _199_ (
    .A(a[0]),
    .B(b[0]),
    .C(a[1]),
    .D(b[1]),
    .Y(_137_)
  );
  sky130_fd_sc_hd__a22oi_1 _200_ (
    .A1(b[0]),
    .A2(a[1]),
    .B1(b[1]),
    .B2(a[0]),
    .Y(_138_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _201_ (
    .A(_137_),
    .SLEEP(_138_),
    .X(u_arrmul_ha0_1_ha_xor0)
  );
  sky130_fd_sc_hd__nand2_1 _202_ (
    .A(a[0]),
    .B(b[2]),
    .Y(_139_)
  );
  sky130_fd_sc_hd__and4_1 _203_ (
    .A(b[0]),
    .B(a[1]),
    .C(a[2]),
    .D(b[1]),
    .X(_140_)
  );
  sky130_fd_sc_hd__a22oi_1 _204_ (
    .A1(b[0]),
    .A2(a[2]),
    .B1(b[1]),
    .B2(a[1]),
    .Y(_141_)
  );
  sky130_fd_sc_hd__or3_1 _205_ (
    .A(_137_),
    .B(_140_),
    .C(_141_),
    .X(_142_)
  );
  sky130_fd_sc_hd__o21ai_0 _206_ (
    .A1(_140_),
    .A2(_141_),
    .B1(_137_),
    .Y(_143_)
  );
  sky130_fd_sc_hd__and3b_1 _207_ (
    .A_N(_139_),
    .B(_142_),
    .C(_143_),
    .X(_144_)
  );
  sky130_fd_sc_hd__a21boi_0 _208_ (
    .A1(_142_),
    .A2(_143_),
    .B1_N(_139_),
    .Y(_145_)
  );
  sky130_fd_sc_hd__nor2_1 _209_ (
    .A(_144_),
    .B(_145_),
    .Y(u_arrmul_ha0_2_ha_xor0)
  );
  sky130_fd_sc_hd__nand2_1 _210_ (
    .A(a[1]),
    .B(b[2]),
    .Y(_146_)
  );
  sky130_fd_sc_hd__clkinv_1 _211_ (
    .A(_146_),
    .Y(_147_)
  );
  sky130_fd_sc_hd__o2111ai_1 _212_ (
    .A1(a[0]),
    .A2(a[2]),
    .B1(b[1]),
    .C1(b[0]),
    .D1(a[1]),
    .Y(_148_)
  );
  sky130_fd_sc_hd__nand2_1 _213_ (
    .A(a[2]),
    .B(b[1]),
    .Y(_149_)
  );
  sky130_fd_sc_hd__nand2_1 _214_ (
    .A(b[0]),
    .B(a[3]),
    .Y(_150_)
  );
  sky130_fd_sc_hd__xor2_1 _215_ (
    .A(_149_),
    .B(_150_),
    .X(_151_)
  );
  sky130_fd_sc_hd__xnor2_1 _216_ (
    .A(_148_),
    .B(_151_),
    .Y(_152_)
  );
  sky130_fd_sc_hd__xnor3_1 _217_ (
    .A(_144_),
    .B(_146_),
    .C(_152_),
    .X(_153_)
  );
  sky130_fd_sc_hd__nand3_1 _218_ (
    .A(a[0]),
    .B(b[3]),
    .C(_153_),
    .Y(_154_)
  );
  sky130_fd_sc_hd__a21oi_1 _219_ (
    .A1(a[0]),
    .A2(b[3]),
    .B1(_153_),
    .Y(_155_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _220_ (
    .A(_154_),
    .SLEEP(_155_),
    .X(u_arrmul_ha0_3_ha_xor0)
  );
  sky130_fd_sc_hd__nand2_1 _221_ (
    .A(a[0]),
    .B(b[4]),
    .Y(_156_)
  );
  sky130_fd_sc_hd__nand2_1 _222_ (
    .A(a[1]),
    .B(b[3]),
    .Y(_157_)
  );
  sky130_fd_sc_hd__maj3_1 _223_ (
    .A(_144_),
    .B(_147_),
    .C(_152_),
    .X(_158_)
  );
  sky130_fd_sc_hd__nand2_1 _224_ (
    .A(a[2]),
    .B(b[2]),
    .Y(_159_)
  );
  sky130_fd_sc_hd__maj3_1 _225_ (
    .A(_148_),
    .B(_149_),
    .C(_150_),
    .X(_160_)
  );
  sky130_fd_sc_hd__nand2_1 _226_ (
    .A(a[3]),
    .B(b[1]),
    .Y(_161_)
  );
  sky130_fd_sc_hd__nand2_1 _227_ (
    .A(b[0]),
    .B(a[4]),
    .Y(_162_)
  );
  sky130_fd_sc_hd__xor2_1 _228_ (
    .A(_161_),
    .B(_162_),
    .X(_163_)
  );
  sky130_fd_sc_hd__xnor2_1 _229_ (
    .A(_160_),
    .B(_163_),
    .Y(_164_)
  );
  sky130_fd_sc_hd__nor2b_1 _230_ (
    .A(_159_),
    .B_N(_164_),
    .Y(_165_)
  );
  sky130_fd_sc_hd__xnor2_1 _231_ (
    .A(_159_),
    .B(_164_),
    .Y(_166_)
  );
  sky130_fd_sc_hd__xnor2_1 _232_ (
    .A(_158_),
    .B(_166_),
    .Y(_167_)
  );
  sky130_fd_sc_hd__xor3_1 _233_ (
    .A(_154_),
    .B(_157_),
    .C(_167_),
    .X(_168_)
  );
  sky130_fd_sc_hd__nor2_1 _234_ (
    .A(_156_),
    .B(_168_),
    .Y(_169_)
  );
  sky130_fd_sc_hd__xor2_1 _235_ (
    .A(_156_),
    .B(_168_),
    .X(u_arrmul_ha0_4_ha_xor0)
  );
  sky130_fd_sc_hd__nand2_1 _236_ (
    .A(a[0]),
    .B(b[5]),
    .Y(_170_)
  );
  sky130_fd_sc_hd__nand2_1 _237_ (
    .A(a[1]),
    .B(b[4]),
    .Y(_171_)
  );
  sky130_fd_sc_hd__clkinv_1 _238_ (
    .A(_171_),
    .Y(_172_)
  );
  sky130_fd_sc_hd__maj3_1 _239_ (
    .A(_154_),
    .B(_157_),
    .C(_167_),
    .X(_173_)
  );
  sky130_fd_sc_hd__nand2_1 _240_ (
    .A(a[2]),
    .B(b[3]),
    .Y(_174_)
  );
  sky130_fd_sc_hd__a21oi_1 _241_ (
    .A1(_158_),
    .A2(_166_),
    .B1(_165_),
    .Y(_175_)
  );
  sky130_fd_sc_hd__nand2_1 _242_ (
    .A(a[3]),
    .B(b[2]),
    .Y(_176_)
  );
  sky130_fd_sc_hd__maj3_1 _243_ (
    .A(_160_),
    .B(_161_),
    .C(_162_),
    .X(_177_)
  );
  sky130_fd_sc_hd__nand2_1 _244_ (
    .A(a[4]),
    .B(b[1]),
    .Y(_178_)
  );
  sky130_fd_sc_hd__nand2_1 _245_ (
    .A(b[0]),
    .B(a[5]),
    .Y(_179_)
  );
  sky130_fd_sc_hd__xor2_1 _246_ (
    .A(_178_),
    .B(_179_),
    .X(_180_)
  );
  sky130_fd_sc_hd__xnor2_1 _247_ (
    .A(_177_),
    .B(_180_),
    .Y(_181_)
  );
  sky130_fd_sc_hd__nand3_1 _248_ (
    .A(a[3]),
    .B(b[2]),
    .C(_181_),
    .Y(_182_)
  );
  sky130_fd_sc_hd__xor2_1 _249_ (
    .A(_176_),
    .B(_181_),
    .X(_183_)
  );
  sky130_fd_sc_hd__xnor2_1 _250_ (
    .A(_175_),
    .B(_183_),
    .Y(_184_)
  );
  sky130_fd_sc_hd__xnor3_1 _251_ (
    .A(_173_),
    .B(_174_),
    .C(_184_),
    .X(_185_)
  );
  sky130_fd_sc_hd__xnor3_1 _252_ (
    .A(_169_),
    .B(_172_),
    .C(_185_),
    .X(_186_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _253_ (
    .A(_170_),
    .SLEEP(_186_),
    .X(_187_)
  );
  sky130_fd_sc_hd__xor2_1 _254_ (
    .A(_170_),
    .B(_186_),
    .X(u_arrmul_ha0_5_ha_xor0)
  );
  sky130_fd_sc_hd__nand2_1 _255_ (
    .A(a[0]),
    .B(b[6]),
    .Y(_188_)
  );
  sky130_fd_sc_hd__nand2_1 _256_ (
    .A(a[1]),
    .B(b[5]),
    .Y(_189_)
  );
  sky130_fd_sc_hd__maj3_1 _257_ (
    .A(_169_),
    .B(_172_),
    .C(_185_),
    .X(_190_)
  );
  sky130_fd_sc_hd__and2_0 _258_ (
    .A(a[2]),
    .B(b[4]),
    .X(_191_)
  );
  sky130_fd_sc_hd__maj3_1 _259_ (
    .A(_173_),
    .B(_174_),
    .C(_184_),
    .X(_192_)
  );
  sky130_fd_sc_hd__nand2_1 _260_ (
    .A(a[3]),
    .B(b[3]),
    .Y(_193_)
  );
  sky130_fd_sc_hd__o21a_1 _261_ (
    .A1(_175_),
    .A2(_183_),
    .B1(_182_),
    .X(_194_)
  );
  sky130_fd_sc_hd__nand2_1 _262_ (
    .A(a[4]),
    .B(b[2]),
    .Y(_195_)
  );
  sky130_fd_sc_hd__maj3_1 _263_ (
    .A(_177_),
    .B(_178_),
    .C(_179_),
    .X(_196_)
  );
  sky130_fd_sc_hd__nand2_1 _264_ (
    .A(a[5]),
    .B(b[1]),
    .Y(_197_)
  );
  sky130_fd_sc_hd__nand2_1 _265_ (
    .A(b[0]),
    .B(a[6]),
    .Y(_000_)
  );
  sky130_fd_sc_hd__xor2_1 _266_ (
    .A(_197_),
    .B(_000_),
    .X(_001_)
  );
  sky130_fd_sc_hd__xnor2_1 _267_ (
    .A(_196_),
    .B(_001_),
    .Y(_002_)
  );
  sky130_fd_sc_hd__nand3_1 _268_ (
    .A(a[4]),
    .B(b[2]),
    .C(_002_),
    .Y(_003_)
  );
  sky130_fd_sc_hd__xor2_1 _269_ (
    .A(_195_),
    .B(_002_),
    .X(_004_)
  );
  sky130_fd_sc_hd__xnor2_1 _270_ (
    .A(_194_),
    .B(_004_),
    .Y(_005_)
  );
  sky130_fd_sc_hd__xnor3_1 _271_ (
    .A(_192_),
    .B(_193_),
    .C(_005_),
    .X(_006_)
  );
  sky130_fd_sc_hd__xnor3_1 _272_ (
    .A(_190_),
    .B(_191_),
    .C(_006_),
    .X(_007_)
  );
  sky130_fd_sc_hd__xor3_1 _273_ (
    .A(_187_),
    .B(_189_),
    .C(_007_),
    .X(_008_)
  );
  sky130_fd_sc_hd__nor2_1 _274_ (
    .A(_188_),
    .B(_008_),
    .Y(_009_)
  );
  sky130_fd_sc_hd__xor2_1 _275_ (
    .A(_188_),
    .B(_008_),
    .X(u_arrmul_ha0_6_ha_xor0)
  );
  sky130_fd_sc_hd__nand2_1 _276_ (
    .A(a[0]),
    .B(b[7]),
    .Y(_010_)
  );
  sky130_fd_sc_hd__and2_0 _277_ (
    .A(a[1]),
    .B(b[6]),
    .X(_011_)
  );
  sky130_fd_sc_hd__maj3_1 _278_ (
    .A(_187_),
    .B(_189_),
    .C(_007_),
    .X(_012_)
  );
  sky130_fd_sc_hd__nand2_1 _279_ (
    .A(a[2]),
    .B(b[5]),
    .Y(_013_)
  );
  sky130_fd_sc_hd__maj3_1 _280_ (
    .A(_190_),
    .B(_191_),
    .C(_006_),
    .X(_014_)
  );
  sky130_fd_sc_hd__and2_0 _281_ (
    .A(a[3]),
    .B(b[4]),
    .X(_015_)
  );
  sky130_fd_sc_hd__maj3_1 _282_ (
    .A(_192_),
    .B(_193_),
    .C(_005_),
    .X(_016_)
  );
  sky130_fd_sc_hd__nand2_1 _283_ (
    .A(a[4]),
    .B(b[3]),
    .Y(_017_)
  );
  sky130_fd_sc_hd__o21a_1 _284_ (
    .A1(_194_),
    .A2(_004_),
    .B1(_003_),
    .X(_018_)
  );
  sky130_fd_sc_hd__nand2_1 _285_ (
    .A(a[5]),
    .B(b[2]),
    .Y(_019_)
  );
  sky130_fd_sc_hd__maj3_1 _286_ (
    .A(_196_),
    .B(_197_),
    .C(_000_),
    .X(_020_)
  );
  sky130_fd_sc_hd__nand2_1 _287_ (
    .A(a[6]),
    .B(b[1]),
    .Y(_021_)
  );
  sky130_fd_sc_hd__nand2_1 _288_ (
    .A(b[0]),
    .B(a[7]),
    .Y(_022_)
  );
  sky130_fd_sc_hd__xor2_1 _289_ (
    .A(_021_),
    .B(_022_),
    .X(_023_)
  );
  sky130_fd_sc_hd__xnor2_1 _290_ (
    .A(_020_),
    .B(_023_),
    .Y(_024_)
  );
  sky130_fd_sc_hd__nand3_1 _291_ (
    .A(a[5]),
    .B(b[2]),
    .C(_024_),
    .Y(_025_)
  );
  sky130_fd_sc_hd__xor2_1 _292_ (
    .A(_019_),
    .B(_024_),
    .X(_026_)
  );
  sky130_fd_sc_hd__xnor2_1 _293_ (
    .A(_018_),
    .B(_026_),
    .Y(_027_)
  );
  sky130_fd_sc_hd__xnor3_1 _294_ (
    .A(_016_),
    .B(_017_),
    .C(_027_),
    .X(_028_)
  );
  sky130_fd_sc_hd__xnor3_1 _295_ (
    .A(_014_),
    .B(_015_),
    .C(_028_),
    .X(_029_)
  );
  sky130_fd_sc_hd__xnor3_1 _296_ (
    .A(_012_),
    .B(_013_),
    .C(_029_),
    .X(_030_)
  );
  sky130_fd_sc_hd__xnor3_1 _297_ (
    .A(_009_),
    .B(_011_),
    .C(_030_),
    .X(_031_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _298_ (
    .A(_010_),
    .SLEEP(_031_),
    .X(_032_)
  );
  sky130_fd_sc_hd__xor2_1 _299_ (
    .A(_010_),
    .B(_031_),
    .X(u_arrmul_ha0_7_ha_xor0)
  );
  sky130_fd_sc_hd__nand2_1 _300_ (
    .A(a[1]),
    .B(b[7]),
    .Y(_033_)
  );
  sky130_fd_sc_hd__maj3_1 _301_ (
    .A(_009_),
    .B(_011_),
    .C(_030_),
    .X(_034_)
  );
  sky130_fd_sc_hd__and2_0 _302_ (
    .A(a[2]),
    .B(b[6]),
    .X(_035_)
  );
  sky130_fd_sc_hd__maj3_1 _303_ (
    .A(_012_),
    .B(_013_),
    .C(_029_),
    .X(_036_)
  );
  sky130_fd_sc_hd__nand2_1 _304_ (
    .A(a[3]),
    .B(b[5]),
    .Y(_037_)
  );
  sky130_fd_sc_hd__maj3_1 _305_ (
    .A(_014_),
    .B(_015_),
    .C(_028_),
    .X(_038_)
  );
  sky130_fd_sc_hd__and2_0 _306_ (
    .A(a[4]),
    .B(b[4]),
    .X(_039_)
  );
  sky130_fd_sc_hd__maj3_1 _307_ (
    .A(_016_),
    .B(_017_),
    .C(_027_),
    .X(_040_)
  );
  sky130_fd_sc_hd__nand2_1 _308_ (
    .A(a[5]),
    .B(b[3]),
    .Y(_041_)
  );
  sky130_fd_sc_hd__o21a_1 _309_ (
    .A1(_018_),
    .A2(_026_),
    .B1(_025_),
    .X(_042_)
  );
  sky130_fd_sc_hd__nand2_1 _310_ (
    .A(a[6]),
    .B(b[2]),
    .Y(_043_)
  );
  sky130_fd_sc_hd__nand2_1 _311_ (
    .A(a[7]),
    .B(b[1]),
    .Y(_044_)
  );
  sky130_fd_sc_hd__maj3_1 _312_ (
    .A(_020_),
    .B(_021_),
    .C(_022_),
    .X(_045_)
  );
  sky130_fd_sc_hd__nor2_1 _313_ (
    .A(_044_),
    .B(_045_),
    .Y(_046_)
  );
  sky130_fd_sc_hd__xnor2_1 _314_ (
    .A(_044_),
    .B(_045_),
    .Y(_047_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _315_ (
    .A(_043_),
    .SLEEP(_047_),
    .X(_048_)
  );
  sky130_fd_sc_hd__and2_0 _316_ (
    .A(_043_),
    .B(_047_),
    .X(_049_)
  );
  sky130_fd_sc_hd__xnor2_1 _317_ (
    .A(_043_),
    .B(_047_),
    .Y(_050_)
  );
  sky130_fd_sc_hd__xnor2_1 _318_ (
    .A(_042_),
    .B(_050_),
    .Y(_051_)
  );
  sky130_fd_sc_hd__xnor3_1 _319_ (
    .A(_040_),
    .B(_041_),
    .C(_051_),
    .X(_052_)
  );
  sky130_fd_sc_hd__xnor3_1 _320_ (
    .A(_038_),
    .B(_039_),
    .C(_052_),
    .X(_053_)
  );
  sky130_fd_sc_hd__xnor3_1 _321_ (
    .A(_036_),
    .B(_037_),
    .C(_053_),
    .X(_054_)
  );
  sky130_fd_sc_hd__xnor3_1 _322_ (
    .A(_034_),
    .B(_035_),
    .C(_054_),
    .X(_055_)
  );
  sky130_fd_sc_hd__xor2_1 _323_ (
    .A(_033_),
    .B(_055_),
    .X(_056_)
  );
  sky130_fd_sc_hd__xnor2_1 _324_ (
    .A(_032_),
    .B(_056_),
    .Y(u_arrmul_fa1_7_fa_xor1)
  );
  sky130_fd_sc_hd__maj3_1 _325_ (
    .A(_032_),
    .B(_033_),
    .C(_055_),
    .X(_057_)
  );
  sky130_fd_sc_hd__nand2_1 _326_ (
    .A(a[2]),
    .B(b[7]),
    .Y(_058_)
  );
  sky130_fd_sc_hd__maj3_1 _327_ (
    .A(_034_),
    .B(_035_),
    .C(_054_),
    .X(_059_)
  );
  sky130_fd_sc_hd__and2_0 _328_ (
    .A(a[3]),
    .B(b[6]),
    .X(_060_)
  );
  sky130_fd_sc_hd__maj3_1 _329_ (
    .A(_036_),
    .B(_037_),
    .C(_053_),
    .X(_061_)
  );
  sky130_fd_sc_hd__nand2_1 _330_ (
    .A(a[4]),
    .B(b[5]),
    .Y(_062_)
  );
  sky130_fd_sc_hd__maj3_1 _331_ (
    .A(_038_),
    .B(_039_),
    .C(_052_),
    .X(_063_)
  );
  sky130_fd_sc_hd__and2_0 _332_ (
    .A(a[5]),
    .B(b[4]),
    .X(_064_)
  );
  sky130_fd_sc_hd__maj3_1 _333_ (
    .A(_040_),
    .B(_041_),
    .C(_051_),
    .X(_065_)
  );
  sky130_fd_sc_hd__nand2_1 _334_ (
    .A(a[6]),
    .B(b[3]),
    .Y(_066_)
  );
  sky130_fd_sc_hd__o21ai_0 _335_ (
    .A1(_042_),
    .A2(_049_),
    .B1(_048_),
    .Y(_067_)
  );
  sky130_fd_sc_hd__and2_0 _336_ (
    .A(a[7]),
    .B(b[2]),
    .X(_068_)
  );
  sky130_fd_sc_hd__xnor2_1 _337_ (
    .A(_046_),
    .B(_068_),
    .Y(_069_)
  );
  sky130_fd_sc_hd__xor2_1 _338_ (
    .A(_067_),
    .B(_069_),
    .X(_070_)
  );
  sky130_fd_sc_hd__xnor3_1 _339_ (
    .A(_065_),
    .B(_066_),
    .C(_070_),
    .X(_071_)
  );
  sky130_fd_sc_hd__xnor3_1 _340_ (
    .A(_063_),
    .B(_064_),
    .C(_071_),
    .X(_072_)
  );
  sky130_fd_sc_hd__xnor3_1 _341_ (
    .A(_061_),
    .B(_062_),
    .C(_072_),
    .X(_073_)
  );
  sky130_fd_sc_hd__xnor3_1 _342_ (
    .A(_059_),
    .B(_060_),
    .C(_073_),
    .X(_074_)
  );
  sky130_fd_sc_hd__xor2_1 _343_ (
    .A(_058_),
    .B(_074_),
    .X(_075_)
  );
  sky130_fd_sc_hd__xnor2_1 _344_ (
    .A(_057_),
    .B(_075_),
    .Y(u_arrmul_fa2_7_fa_xor1)
  );
  sky130_fd_sc_hd__maj3_1 _345_ (
    .A(_057_),
    .B(_058_),
    .C(_074_),
    .X(_076_)
  );
  sky130_fd_sc_hd__nand2_1 _346_ (
    .A(a[3]),
    .B(b[7]),
    .Y(_077_)
  );
  sky130_fd_sc_hd__maj3_1 _347_ (
    .A(_059_),
    .B(_060_),
    .C(_073_),
    .X(_078_)
  );
  sky130_fd_sc_hd__nand2_1 _348_ (
    .A(a[4]),
    .B(b[6]),
    .Y(_079_)
  );
  sky130_fd_sc_hd__clkinv_1 _349_ (
    .A(_079_),
    .Y(_080_)
  );
  sky130_fd_sc_hd__maj3_1 _350_ (
    .A(_061_),
    .B(_062_),
    .C(_072_),
    .X(_081_)
  );
  sky130_fd_sc_hd__nand2_1 _351_ (
    .A(a[5]),
    .B(b[5]),
    .Y(_082_)
  );
  sky130_fd_sc_hd__maj3_1 _352_ (
    .A(_063_),
    .B(_064_),
    .C(_071_),
    .X(_083_)
  );
  sky130_fd_sc_hd__and2_0 _353_ (
    .A(a[6]),
    .B(b[4]),
    .X(_084_)
  );
  sky130_fd_sc_hd__maj3_1 _354_ (
    .A(_065_),
    .B(_066_),
    .C(_070_),
    .X(_085_)
  );
  sky130_fd_sc_hd__nand2_1 _355_ (
    .A(a[7]),
    .B(b[3]),
    .Y(_086_)
  );
  sky130_fd_sc_hd__maj3_1 _356_ (
    .A(_046_),
    .B(_067_),
    .C(_068_),
    .X(_087_)
  );
  sky130_fd_sc_hd__clkinv_1 _357_ (
    .A(_087_),
    .Y(_088_)
  );
  sky130_fd_sc_hd__xnor2_1 _358_ (
    .A(_086_),
    .B(_087_),
    .Y(_089_)
  );
  sky130_fd_sc_hd__xnor2_1 _359_ (
    .A(_085_),
    .B(_089_),
    .Y(_090_)
  );
  sky130_fd_sc_hd__xnor3_1 _360_ (
    .A(_083_),
    .B(_084_),
    .C(_090_),
    .X(_091_)
  );
  sky130_fd_sc_hd__xnor3_1 _361_ (
    .A(_081_),
    .B(_082_),
    .C(_091_),
    .X(_092_)
  );
  sky130_fd_sc_hd__xnor3_1 _362_ (
    .A(_078_),
    .B(_080_),
    .C(_092_),
    .X(_093_)
  );
  sky130_fd_sc_hd__xor2_1 _363_ (
    .A(_077_),
    .B(_093_),
    .X(_094_)
  );
  sky130_fd_sc_hd__xnor2_1 _364_ (
    .A(_076_),
    .B(_094_),
    .Y(u_arrmul_fa3_7_fa_xor1)
  );
  sky130_fd_sc_hd__maj3_1 _365_ (
    .A(_076_),
    .B(_077_),
    .C(_093_),
    .X(_095_)
  );
  sky130_fd_sc_hd__nand2_1 _366_ (
    .A(a[4]),
    .B(b[7]),
    .Y(_096_)
  );
  sky130_fd_sc_hd__maj3_1 _367_ (
    .A(_078_),
    .B(_080_),
    .C(_092_),
    .X(_097_)
  );
  sky130_fd_sc_hd__and2_0 _368_ (
    .A(a[5]),
    .B(b[6]),
    .X(_098_)
  );
  sky130_fd_sc_hd__maj3_1 _369_ (
    .A(_081_),
    .B(_082_),
    .C(_091_),
    .X(_099_)
  );
  sky130_fd_sc_hd__nand2_1 _370_ (
    .A(a[6]),
    .B(b[5]),
    .Y(_100_)
  );
  sky130_fd_sc_hd__maj3_1 _371_ (
    .A(_083_),
    .B(_084_),
    .C(_090_),
    .X(_101_)
  );
  sky130_fd_sc_hd__nand2_1 _372_ (
    .A(a[7]),
    .B(b[4]),
    .Y(_102_)
  );
  sky130_fd_sc_hd__maj3_1 _373_ (
    .A(_085_),
    .B(_086_),
    .C(_088_),
    .X(_103_)
  );
  sky130_fd_sc_hd__nor2_1 _374_ (
    .A(_102_),
    .B(_103_),
    .Y(_104_)
  );
  sky130_fd_sc_hd__xor2_1 _375_ (
    .A(_102_),
    .B(_103_),
    .X(_105_)
  );
  sky130_fd_sc_hd__xnor2_1 _376_ (
    .A(_101_),
    .B(_105_),
    .Y(_106_)
  );
  sky130_fd_sc_hd__xnor3_1 _377_ (
    .A(_099_),
    .B(_100_),
    .C(_106_),
    .X(_107_)
  );
  sky130_fd_sc_hd__xnor3_1 _378_ (
    .A(_097_),
    .B(_098_),
    .C(_107_),
    .X(_108_)
  );
  sky130_fd_sc_hd__xor2_1 _379_ (
    .A(_096_),
    .B(_108_),
    .X(_109_)
  );
  sky130_fd_sc_hd__xnor2_1 _380_ (
    .A(_095_),
    .B(_109_),
    .Y(u_arrmul_fa4_7_fa_xor1)
  );
  sky130_fd_sc_hd__maj3_1 _381_ (
    .A(_095_),
    .B(_096_),
    .C(_108_),
    .X(_110_)
  );
  sky130_fd_sc_hd__nand2_1 _382_ (
    .A(a[5]),
    .B(b[7]),
    .Y(_111_)
  );
  sky130_fd_sc_hd__maj3_1 _383_ (
    .A(_097_),
    .B(_098_),
    .C(_107_),
    .X(_112_)
  );
  sky130_fd_sc_hd__and2_0 _384_ (
    .A(a[6]),
    .B(b[6]),
    .X(_113_)
  );
  sky130_fd_sc_hd__maj3_1 _385_ (
    .A(_099_),
    .B(_100_),
    .C(_106_),
    .X(_114_)
  );
  sky130_fd_sc_hd__nand2_1 _386_ (
    .A(a[7]),
    .B(b[5]),
    .Y(_115_)
  );
  sky130_fd_sc_hd__a21o_1 _387_ (
    .A1(_101_),
    .A2(_105_),
    .B1(_104_),
    .X(_116_)
  );
  sky130_fd_sc_hd__clkinv_1 _388_ (
    .A(_116_),
    .Y(_117_)
  );
  sky130_fd_sc_hd__xnor2_1 _389_ (
    .A(_115_),
    .B(_116_),
    .Y(_118_)
  );
  sky130_fd_sc_hd__xnor2_1 _390_ (
    .A(_114_),
    .B(_118_),
    .Y(_119_)
  );
  sky130_fd_sc_hd__xnor3_1 _391_ (
    .A(_112_),
    .B(_113_),
    .C(_119_),
    .X(_120_)
  );
  sky130_fd_sc_hd__xor2_1 _392_ (
    .A(_111_),
    .B(_120_),
    .X(_121_)
  );
  sky130_fd_sc_hd__xnor2_1 _393_ (
    .A(_110_),
    .B(_121_),
    .Y(u_arrmul_fa5_7_fa_xor1)
  );
  sky130_fd_sc_hd__maj3_1 _394_ (
    .A(_110_),
    .B(_111_),
    .C(_120_),
    .X(_122_)
  );
  sky130_fd_sc_hd__nand2_1 _395_ (
    .A(a[6]),
    .B(b[7]),
    .Y(_123_)
  );
  sky130_fd_sc_hd__maj3_1 _396_ (
    .A(_112_),
    .B(_113_),
    .C(_119_),
    .X(_124_)
  );
  sky130_fd_sc_hd__nand2_1 _397_ (
    .A(a[7]),
    .B(b[6]),
    .Y(_125_)
  );
  sky130_fd_sc_hd__maj3_1 _398_ (
    .A(_114_),
    .B(_115_),
    .C(_117_),
    .X(_126_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _399_ (
    .A(_125_),
    .SLEEP(_126_),
    .X(_127_)
  );
  sky130_fd_sc_hd__xnor2_1 _400_ (
    .A(_125_),
    .B(_126_),
    .Y(_128_)
  );
  sky130_fd_sc_hd__nand2b_1 _401_ (
    .A_N(_128_),
    .B(_124_),
    .Y(_129_)
  );
  sky130_fd_sc_hd__xor2_1 _402_ (
    .A(_124_),
    .B(_128_),
    .X(_130_)
  );
  sky130_fd_sc_hd__xor2_1 _403_ (
    .A(_123_),
    .B(_130_),
    .X(_131_)
  );
  sky130_fd_sc_hd__xnor2_1 _404_ (
    .A(_122_),
    .B(_131_),
    .Y(u_arrmul_fa6_7_fa_xor1)
  );
  sky130_fd_sc_hd__maj3_1 _405_ (
    .A(_122_),
    .B(_123_),
    .C(_130_),
    .X(_132_)
  );
  sky130_fd_sc_hd__nand2_1 _406_ (
    .A(a[7]),
    .B(b[7]),
    .Y(_133_)
  );
  sky130_fd_sc_hd__nand2_1 _407_ (
    .A(_127_),
    .B(_129_),
    .Y(_134_)
  );
  sky130_fd_sc_hd__a21o_1 _408_ (
    .A1(_127_),
    .A2(_129_),
    .B1(_133_),
    .X(_135_)
  );
  sky130_fd_sc_hd__and3_1 _409_ (
    .A(_127_),
    .B(_129_),
    .C(_133_),
    .X(_136_)
  );
  sky130_fd_sc_hd__xor3_1 _410_ (
    .A(_132_),
    .B(_133_),
    .C(_134_),
    .X(u_arrmul_fa7_7_fa_xor1)
  );
  sky130_fd_sc_hd__o21ai_0 _411_ (
    .A1(_132_),
    .A2(_136_),
    .B1(_135_),
    .Y(u_arrmul_fa7_7_fa_or0)
  );
  assign u_arrmul_out = { u_arrmul_fa7_7_fa_or0, u_arrmul_fa7_7_fa_xor1, u_arrmul_fa6_7_fa_xor1, u_arrmul_fa5_7_fa_xor1, u_arrmul_fa4_7_fa_xor1, u_arrmul_fa3_7_fa_xor1, u_arrmul_fa2_7_fa_xor1, u_arrmul_fa1_7_fa_xor1, u_arrmul_ha0_7_ha_xor0, u_arrmul_ha0_6_ha_xor0, u_arrmul_ha0_5_ha_xor0, u_arrmul_ha0_4_ha_xor0, u_arrmul_ha0_3_ha_xor0, u_arrmul_ha0_2_ha_xor0, u_arrmul_ha0_1_ha_xor0, u_arrmul_and0_0 };
endmodule

(* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/rbs8.v:1.1-117.10" *)
module u_rbs(a, b, u_rbs_out);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/rbs8.v:1.26-1.27" *)
  input [7:0] a;
  wire [7:0] a;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/rbs8.v:1.41-1.42" *)
  input [7:0] b;
  wire [7:0] b;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/rbs8.v:8.8-8.25" *)
  wire u_rbs_fs1_fs_xor1;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/rbs8.v:15.8-15.25" *)
  wire u_rbs_fs2_fs_xor1;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/rbs8.v:22.8-22.25" *)
  wire u_rbs_fs3_fs_xor1;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/rbs8.v:29.8-29.25" *)
  wire u_rbs_fs4_fs_xor1;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/rbs8.v:36.8-36.25" *)
  wire u_rbs_fs5_fs_xor1;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/rbs8.v:43.8-43.25" *)
  wire u_rbs_fs6_fs_xor1;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/rbs8.v:53.8-53.24" *)
  wire u_rbs_fs7_fs_or0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/rbs8.v:50.8-50.25" *)
  wire u_rbs_fs7_fs_xor1;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/rbs8.v:2.8-2.24" *)
  wire u_rbs_hs_hs_xor0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/rbs8.v:1.57-1.66" *)
  output [8:0] u_rbs_out;
  wire [8:0] u_rbs_out;
  sky130_fd_sc_hd__clkinv_1 _21_ (
    .A(a[1]),
    .Y(_00_)
  );
  sky130_fd_sc_hd__clkinv_1 _22_ (
    .A(a[2]),
    .Y(_01_)
  );
  sky130_fd_sc_hd__clkinv_1 _23_ (
    .A(a[3]),
    .Y(_02_)
  );
  sky130_fd_sc_hd__clkinv_1 _24_ (
    .A(a[4]),
    .Y(_03_)
  );
  sky130_fd_sc_hd__clkinv_1 _25_ (
    .A(a[5]),
    .Y(_04_)
  );
  sky130_fd_sc_hd__clkinv_1 _26_ (
    .A(a[6]),
    .Y(_05_)
  );
  sky130_fd_sc_hd__clkinv_1 _27_ (
    .A(a[7]),
    .Y(_06_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _28_ (
    .A(b[0]),
    .SLEEP(a[0]),
    .X(_07_)
  );
  sky130_fd_sc_hd__xor2_1 _29_ (
    .A(a[0]),
    .B(b[0]),
    .X(u_rbs_hs_hs_xor0)
  );
  sky130_fd_sc_hd__xnor2_1 _30_ (
    .A(a[1]),
    .B(b[1]),
    .Y(_08_)
  );
  sky130_fd_sc_hd__xnor2_1 _31_ (
    .A(_07_),
    .B(_08_),
    .Y(u_rbs_fs1_fs_xor1)
  );
  sky130_fd_sc_hd__maj3_1 _32_ (
    .A(_00_),
    .B(b[1]),
    .C(_07_),
    .X(_09_)
  );
  sky130_fd_sc_hd__xnor2_1 _33_ (
    .A(a[2]),
    .B(b[2]),
    .Y(_10_)
  );
  sky130_fd_sc_hd__xnor2_1 _34_ (
    .A(_09_),
    .B(_10_),
    .Y(u_rbs_fs2_fs_xor1)
  );
  sky130_fd_sc_hd__maj3_1 _35_ (
    .A(_01_),
    .B(b[2]),
    .C(_09_),
    .X(_11_)
  );
  sky130_fd_sc_hd__xnor2_1 _36_ (
    .A(a[3]),
    .B(b[3]),
    .Y(_12_)
  );
  sky130_fd_sc_hd__xnor2_1 _37_ (
    .A(_11_),
    .B(_12_),
    .Y(u_rbs_fs3_fs_xor1)
  );
  sky130_fd_sc_hd__maj3_1 _38_ (
    .A(_02_),
    .B(b[3]),
    .C(_11_),
    .X(_13_)
  );
  sky130_fd_sc_hd__xnor2_1 _39_ (
    .A(a[4]),
    .B(b[4]),
    .Y(_14_)
  );
  sky130_fd_sc_hd__xnor2_1 _40_ (
    .A(_13_),
    .B(_14_),
    .Y(u_rbs_fs4_fs_xor1)
  );
  sky130_fd_sc_hd__maj3_1 _41_ (
    .A(_03_),
    .B(b[4]),
    .C(_13_),
    .X(_15_)
  );
  sky130_fd_sc_hd__xnor2_1 _42_ (
    .A(a[5]),
    .B(b[5]),
    .Y(_16_)
  );
  sky130_fd_sc_hd__xnor2_1 _43_ (
    .A(_15_),
    .B(_16_),
    .Y(u_rbs_fs5_fs_xor1)
  );
  sky130_fd_sc_hd__maj3_1 _44_ (
    .A(_04_),
    .B(b[5]),
    .C(_15_),
    .X(_17_)
  );
  sky130_fd_sc_hd__xnor2_1 _45_ (
    .A(a[6]),
    .B(b[6]),
    .Y(_18_)
  );
  sky130_fd_sc_hd__xnor2_1 _46_ (
    .A(_17_),
    .B(_18_),
    .Y(u_rbs_fs6_fs_xor1)
  );
  sky130_fd_sc_hd__maj3_1 _47_ (
    .A(_05_),
    .B(b[6]),
    .C(_17_),
    .X(_19_)
  );
  sky130_fd_sc_hd__xnor2_1 _48_ (
    .A(a[7]),
    .B(b[7]),
    .Y(_20_)
  );
  sky130_fd_sc_hd__xnor2_1 _49_ (
    .A(_19_),
    .B(_20_),
    .Y(u_rbs_fs7_fs_xor1)
  );
  sky130_fd_sc_hd__maj3_1 _50_ (
    .A(_06_),
    .B(b[7]),
    .C(_19_),
    .X(u_rbs_fs7_fs_or0)
  );
  assign u_rbs_out = { u_rbs_fs7_fs_or0, u_rbs_fs7_fs_xor1, u_rbs_fs6_fs_xor1, u_rbs_fs5_fs_xor1, u_rbs_fs4_fs_xor1, u_rbs_fs3_fs_xor1, u_rbs_fs2_fs_xor1, u_rbs_fs1_fs_xor1, u_rbs_hs_hs_xor0 };
endmodule

(* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/rca8.v:1.1-87.10" *)
module u_rca(a, b, u_rca_out);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/rca8.v:1.26-1.27" *)
  input [7:0] a;
  wire [7:0] a;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/rca8.v:1.41-1.42" *)
  input [7:0] b;
  wire [7:0] b;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/rca8.v:6.8-6.25" *)
  wire u_rca_fa1_fa_xor1;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/rca8.v:11.8-11.25" *)
  wire u_rca_fa2_fa_xor1;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/rca8.v:16.8-16.25" *)
  wire u_rca_fa3_fa_xor1;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/rca8.v:21.8-21.25" *)
  wire u_rca_fa4_fa_xor1;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/rca8.v:26.8-26.25" *)
  wire u_rca_fa5_fa_xor1;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/rca8.v:31.8-31.25" *)
  wire u_rca_fa6_fa_xor1;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/rca8.v:38.8-38.24" *)
  wire u_rca_fa7_fa_or0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/rca8.v:36.8-36.25" *)
  wire u_rca_fa7_fa_xor1;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/rca8.v:2.8-2.24" *)
  wire u_rca_ha_ha_xor0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/rca8.v:1.57-1.66" *)
  output [8:0] u_rca_out;
  wire [8:0] u_rca_out;
  sky130_fd_sc_hd__nand2_1 _16_ (
    .A(a[0]),
    .B(b[0]),
    .Y(_00_)
  );
  sky130_fd_sc_hd__xor2_1 _17_ (
    .A(a[0]),
    .B(b[0]),
    .X(u_rca_ha_ha_xor0)
  );
  sky130_fd_sc_hd__nand2_1 _18_ (
    .A(a[1]),
    .B(b[1]),
    .Y(_01_)
  );
  sky130_fd_sc_hd__nor2_1 _19_ (
    .A(a[1]),
    .B(b[1]),
    .Y(_02_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _20_ (
    .A(_01_),
    .SLEEP(_02_),
    .X(_03_)
  );
  sky130_fd_sc_hd__xnor2_1 _21_ (
    .A(_00_),
    .B(_03_),
    .Y(u_rca_fa1_fa_xor1)
  );
  sky130_fd_sc_hd__o21ai_0 _22_ (
    .A1(_00_),
    .A2(_02_),
    .B1(_01_),
    .Y(_04_)
  );
  sky130_fd_sc_hd__xnor2_1 _23_ (
    .A(a[2]),
    .B(b[2]),
    .Y(_05_)
  );
  sky130_fd_sc_hd__xnor2_1 _24_ (
    .A(_04_),
    .B(_05_),
    .Y(u_rca_fa2_fa_xor1)
  );
  sky130_fd_sc_hd__maj3_1 _25_ (
    .A(a[2]),
    .B(b[2]),
    .C(_04_),
    .X(_06_)
  );
  sky130_fd_sc_hd__xnor2_1 _26_ (
    .A(a[3]),
    .B(b[3]),
    .Y(_07_)
  );
  sky130_fd_sc_hd__xnor2_1 _27_ (
    .A(_06_),
    .B(_07_),
    .Y(u_rca_fa3_fa_xor1)
  );
  sky130_fd_sc_hd__maj3_1 _28_ (
    .A(a[3]),
    .B(b[3]),
    .C(_06_),
    .X(_08_)
  );
  sky130_fd_sc_hd__xnor2_1 _29_ (
    .A(a[4]),
    .B(b[4]),
    .Y(_09_)
  );
  sky130_fd_sc_hd__xnor2_1 _30_ (
    .A(_08_),
    .B(_09_),
    .Y(u_rca_fa4_fa_xor1)
  );
  sky130_fd_sc_hd__maj3_1 _31_ (
    .A(a[4]),
    .B(b[4]),
    .C(_08_),
    .X(_10_)
  );
  sky130_fd_sc_hd__xnor2_1 _32_ (
    .A(a[5]),
    .B(b[5]),
    .Y(_11_)
  );
  sky130_fd_sc_hd__xnor2_1 _33_ (
    .A(_10_),
    .B(_11_),
    .Y(u_rca_fa5_fa_xor1)
  );
  sky130_fd_sc_hd__maj3_1 _34_ (
    .A(a[5]),
    .B(b[5]),
    .C(_10_),
    .X(_12_)
  );
  sky130_fd_sc_hd__xnor2_1 _35_ (
    .A(a[6]),
    .B(b[6]),
    .Y(_13_)
  );
  sky130_fd_sc_hd__xnor2_1 _36_ (
    .A(_12_),
    .B(_13_),
    .Y(u_rca_fa6_fa_xor1)
  );
  sky130_fd_sc_hd__maj3_1 _37_ (
    .A(a[6]),
    .B(b[6]),
    .C(_12_),
    .X(_14_)
  );
  sky130_fd_sc_hd__xnor2_1 _38_ (
    .A(a[7]),
    .B(b[7]),
    .Y(_15_)
  );
  sky130_fd_sc_hd__xnor2_1 _39_ (
    .A(_14_),
    .B(_15_),
    .Y(u_rca_fa7_fa_xor1)
  );
  sky130_fd_sc_hd__maj3_1 _40_ (
    .A(a[7]),
    .B(b[7]),
    .C(_14_),
    .X(u_rca_fa7_fa_or0)
  );
  assign u_rca_out = { u_rca_fa7_fa_or0, u_rca_fa7_fa_xor1, u_rca_fa6_fa_xor1, u_rca_fa5_fa_xor1, u_rca_fa4_fa_xor1, u_rca_fa3_fa_xor1, u_rca_fa2_fa_xor1, u_rca_fa1_fa_xor1, u_rca_ha_ha_xor0 };
endmodule
