/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_2.v:1.1-54.10" *)
module alu_8bit(rs, rt, op, alu_out);
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_2.v:9.12-9.19" *)
  (* unused_bits = "0 1 2 3 4 5 6 7" *)
  wire [7:0] add_out;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_2.v:5.23-5.30" *)
  output [7:0] alu_out;
  wire [7:0] alu_out;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_2.v:11.12-11.19" *)
  (* unused_bits = "0 1 2 3 4 5 6 7" *)
  wire [7:0] mul_out;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_2.v:21.12-21.20" *)
  (* unused_bits = "0 1 2 3 4 5 6 7" *)
  wire [7:0] mux1_out;
  (* hdlname = "mux_layer1[0].mux_add_sub sel" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_2.v:27.17-32.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:2.16-2.19" *)
  (* unused_bits = "0" *)
  wire \mux_layer1[0].mux_add_sub.sel ;
  (* hdlname = "mux_layer1[0].mux_mul_div sel" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_2.v:33.17-38.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:2.16-2.19" *)
  (* unused_bits = "0" *)
  wire \mux_layer1[0].mux_mul_div.sel ;
  (* hdlname = "mux_layer1[1].mux_add_sub sel" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_2.v:27.17-32.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:2.16-2.19" *)
  (* unused_bits = "0" *)
  wire \mux_layer1[1].mux_add_sub.sel ;
  (* hdlname = "mux_layer1[1].mux_mul_div sel" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_2.v:33.17-38.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:2.16-2.19" *)
  (* unused_bits = "0" *)
  wire \mux_layer1[1].mux_mul_div.sel ;
  (* hdlname = "mux_layer1[2].mux_add_sub in0" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_2.v:27.17-32.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:3.16-3.19" *)
  (* unused_bits = "0" *)
  wire \mux_layer1[2].mux_add_sub.in0 ;
  (* hdlname = "mux_layer1[2].mux_add_sub out" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_2.v:27.17-32.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:5.17-5.20" *)
  (* unused_bits = "0" *)
  wire \mux_layer1[2].mux_add_sub.out ;
  (* hdlname = "mux_layer1[2].mux_add_sub sel" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_2.v:27.17-32.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:2.16-2.19" *)
  (* unused_bits = "0" *)
  wire \mux_layer1[2].mux_add_sub.sel ;
  (* hdlname = "mux_layer1[2].mux_mul_div sel" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_2.v:33.17-38.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:2.16-2.19" *)
  (* unused_bits = "0" *)
  wire \mux_layer1[2].mux_mul_div.sel ;
  (* hdlname = "mux_layer1[3].mux_add_sub in0" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_2.v:27.17-32.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:3.16-3.19" *)
  (* unused_bits = "0" *)
  wire \mux_layer1[3].mux_add_sub.in0 ;
  (* hdlname = "mux_layer1[3].mux_add_sub out" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_2.v:27.17-32.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:5.17-5.20" *)
  (* unused_bits = "0" *)
  wire \mux_layer1[3].mux_add_sub.out ;
  (* hdlname = "mux_layer1[3].mux_add_sub sel" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_2.v:27.17-32.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:2.16-2.19" *)
  (* unused_bits = "0" *)
  wire \mux_layer1[3].mux_add_sub.sel ;
  (* hdlname = "mux_layer1[3].mux_mul_div in0" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_2.v:33.17-38.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:3.16-3.19" *)
  (* unused_bits = "0" *)
  wire \mux_layer1[3].mux_mul_div.in0 ;
  (* hdlname = "mux_layer1[3].mux_mul_div sel" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_2.v:33.17-38.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:2.16-2.19" *)
  (* unused_bits = "0" *)
  wire \mux_layer1[3].mux_mul_div.sel ;
  (* hdlname = "mux_layer1[4].mux_add_sub sel" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_2.v:27.17-32.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:2.16-2.19" *)
  (* unused_bits = "0" *)
  wire \mux_layer1[4].mux_add_sub.sel ;
  (* hdlname = "mux_layer1[4].mux_mul_div sel" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_2.v:33.17-38.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:2.16-2.19" *)
  (* unused_bits = "0" *)
  wire \mux_layer1[4].mux_mul_div.sel ;
  (* hdlname = "mux_layer1[5].mux_add_sub sel" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_2.v:27.17-32.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:2.16-2.19" *)
  (* unused_bits = "0" *)
  wire \mux_layer1[5].mux_add_sub.sel ;
  (* hdlname = "mux_layer1[5].mux_mul_div sel" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_2.v:33.17-38.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:2.16-2.19" *)
  (* unused_bits = "0" *)
  wire \mux_layer1[5].mux_mul_div.sel ;
  (* hdlname = "mux_layer1[6].mux_add_sub sel" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_2.v:27.17-32.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:2.16-2.19" *)
  (* unused_bits = "0" *)
  wire \mux_layer1[6].mux_add_sub.sel ;
  (* hdlname = "mux_layer1[6].mux_mul_div sel" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_2.v:33.17-38.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:2.16-2.19" *)
  (* unused_bits = "0" *)
  wire \mux_layer1[6].mux_mul_div.sel ;
  (* hdlname = "mux_layer1[7].mux_add_sub sel" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_2.v:27.17-32.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:2.16-2.19" *)
  (* unused_bits = "0" *)
  wire \mux_layer1[7].mux_add_sub.sel ;
  (* hdlname = "mux_layer1[7].mux_mul_div sel" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_2.v:33.17-38.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:2.16-2.19" *)
  (* unused_bits = "0" *)
  wire \mux_layer1[7].mux_mul_div.sel ;
  (* hdlname = "mux_layer2[0].mux_final out" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_2.v:45.17-50.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:5.17-5.20" *)
  wire \mux_layer2[0].mux_final.out ;
  (* hdlname = "mux_layer2[0].mux_final sel" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_2.v:45.17-50.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:2.16-2.19" *)
  (* unused_bits = "0" *)
  wire \mux_layer2[0].mux_final.sel ;
  (* hdlname = "mux_layer2[1].mux_final out" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_2.v:45.17-50.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:5.17-5.20" *)
  wire \mux_layer2[1].mux_final.out ;
  (* hdlname = "mux_layer2[1].mux_final sel" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_2.v:45.17-50.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:2.16-2.19" *)
  (* unused_bits = "0" *)
  wire \mux_layer2[1].mux_final.sel ;
  (* hdlname = "mux_layer2[2].mux_final in0" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_2.v:45.17-50.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:3.16-3.19" *)
  (* unused_bits = "0" *)
  wire \mux_layer2[2].mux_final.in0 ;
  (* hdlname = "mux_layer2[2].mux_final out" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_2.v:45.17-50.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:5.17-5.20" *)
  wire \mux_layer2[2].mux_final.out ;
  (* hdlname = "mux_layer2[2].mux_final sel" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_2.v:45.17-50.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:2.16-2.19" *)
  (* unused_bits = "0" *)
  wire \mux_layer2[2].mux_final.sel ;
  (* hdlname = "mux_layer2[3].mux_final in0" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_2.v:45.17-50.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:3.16-3.19" *)
  (* unused_bits = "0" *)
  wire \mux_layer2[3].mux_final.in0 ;
  (* hdlname = "mux_layer2[3].mux_final out" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_2.v:45.17-50.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:5.17-5.20" *)
  wire \mux_layer2[3].mux_final.out ;
  (* hdlname = "mux_layer2[3].mux_final sel" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_2.v:45.17-50.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:2.16-2.19" *)
  (* unused_bits = "0" *)
  wire \mux_layer2[3].mux_final.sel ;
  (* hdlname = "mux_layer2[4].mux_final out" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_2.v:45.17-50.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:5.17-5.20" *)
  wire \mux_layer2[4].mux_final.out ;
  (* hdlname = "mux_layer2[4].mux_final sel" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_2.v:45.17-50.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:2.16-2.19" *)
  (* unused_bits = "0" *)
  wire \mux_layer2[4].mux_final.sel ;
  (* hdlname = "mux_layer2[5].mux_final out" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_2.v:45.17-50.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:5.17-5.20" *)
  wire \mux_layer2[5].mux_final.out ;
  (* hdlname = "mux_layer2[5].mux_final sel" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_2.v:45.17-50.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:2.16-2.19" *)
  (* unused_bits = "0" *)
  wire \mux_layer2[5].mux_final.sel ;
  (* hdlname = "mux_layer2[6].mux_final out" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_2.v:45.17-50.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:5.17-5.20" *)
  wire \mux_layer2[6].mux_final.out ;
  (* hdlname = "mux_layer2[6].mux_final sel" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_2.v:45.17-50.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:2.16-2.19" *)
  (* unused_bits = "0" *)
  wire \mux_layer2[6].mux_final.sel ;
  (* hdlname = "mux_layer2[7].mux_final out" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_2.v:45.17-50.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:5.17-5.20" *)
  wire \mux_layer2[7].mux_final.out ;
  (* hdlname = "mux_layer2[7].mux_final sel" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_2.v:45.17-50.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:2.16-2.19" *)
  (* unused_bits = "0" *)
  wire \mux_layer2[7].mux_final.sel ;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_2.v:4.22-4.24" *)
  input [1:0] op;
  wire [1:0] op;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_2.v:2.22-2.24" *)
  input [7:0] rs;
  wire [7:0] rs;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_2.v:3.22-3.24" *)
  input [7:0] rt;
  wire [7:0] rt;
  (* hdlname = "u_adder a" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_2.v:15.7-15.45|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/cla8.v:1.26-1.27" *)
  (* unused_bits = "0 1 2 3 4 5 6 7" *)
  wire [7:0] \u_adder.a ;
  (* hdlname = "u_adder b" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_2.v:15.7-15.45|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/cla8.v:1.41-1.42" *)
  (* unused_bits = "0 1 2 3 4 5 6 7" *)
  wire [7:0] \u_adder.b ;
  (* hdlname = "u_div a" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_2.v:18.8-18.49|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:1.27-1.28" *)
  (* unused_bits = "0 1 2 3 4 5 6 7" *)
  wire [7:0] \u_div.a ;
  (* hdlname = "u_div b" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_2.v:18.8-18.49|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:1.42-1.43" *)
  (* unused_bits = "0 1 2 3 4 5 6 7" *)
  wire [7:0] \u_div.b ;
  (* hdlname = "u_mul a" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_2.v:17.15-17.52|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/wmu16.v:1.34-1.35" *)
  (* unused_bits = "0 1 2 3 4 5 6 7" *)
  wire [7:0] \u_mul.a ;
  (* hdlname = "u_mul b" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_2.v:17.15-17.52|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/wmu16.v:1.49-1.50" *)
  (* unused_bits = "0 1 2 3 4 5 6 7" *)
  wire [7:0] \u_mul.b ;
  (* hdlname = "u_sub a" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_2.v:16.7-16.44|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/rcs8.v:1.26-1.27" *)
  (* unused_bits = "0 1 2 3 4 5 6 7" *)
  wire [7:0] \u_sub.a ;
  (* hdlname = "u_sub b" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_2.v:16.7-16.44|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/rcs8.v:1.41-1.42" *)
  (* unused_bits = "0 1 2 3 4 5 6 7" *)
  wire [7:0] \u_sub.b ;
  assign add_out[3:2] = { \mux_layer1[3].mux_add_sub.in0 , \mux_layer1[2].mux_add_sub.in0  };
  assign alu_out = 8'h00;
  assign mul_out[3] = \mux_layer1[3].mux_mul_div.in0 ;
  assign mux1_out[3:2] = { \mux_layer1[3].mux_add_sub.out , \mux_layer1[2].mux_add_sub.out  };
  assign \mux_layer1[0].mux_add_sub.sel  = op[0];
  assign \mux_layer1[0].mux_mul_div.sel  = op[0];
  assign \mux_layer1[1].mux_add_sub.sel  = op[0];
  assign \mux_layer1[1].mux_mul_div.sel  = op[0];
  assign \mux_layer1[2].mux_add_sub.sel  = op[0];
  assign \mux_layer1[2].mux_mul_div.sel  = op[0];
  assign \mux_layer1[3].mux_add_sub.sel  = op[0];
  assign \mux_layer1[3].mux_mul_div.sel  = op[0];
  assign \mux_layer1[4].mux_add_sub.sel  = op[0];
  assign \mux_layer1[4].mux_mul_div.sel  = op[0];
  assign \mux_layer1[5].mux_add_sub.sel  = op[0];
  assign \mux_layer1[5].mux_mul_div.sel  = op[0];
  assign \mux_layer1[6].mux_add_sub.sel  = op[0];
  assign \mux_layer1[6].mux_mul_div.sel  = op[0];
  assign \mux_layer1[7].mux_add_sub.sel  = op[0];
  assign \mux_layer1[7].mux_mul_div.sel  = op[0];
  assign \mux_layer2[0].mux_final.out  = 1'h0;
  assign \mux_layer2[0].mux_final.sel  = op[1];
  assign \mux_layer2[1].mux_final.out  = 1'h0;
  assign \mux_layer2[1].mux_final.sel  = op[1];
  assign \mux_layer2[2].mux_final.in0  = \mux_layer1[2].mux_add_sub.out ;
  assign \mux_layer2[2].mux_final.out  = 1'h0;
  assign \mux_layer2[2].mux_final.sel  = op[1];
  assign \mux_layer2[3].mux_final.in0  = \mux_layer1[3].mux_add_sub.out ;
  assign \mux_layer2[3].mux_final.out  = 1'h0;
  assign \mux_layer2[3].mux_final.sel  = op[1];
  assign \mux_layer2[4].mux_final.out  = 1'h0;
  assign \mux_layer2[4].mux_final.sel  = op[1];
  assign \mux_layer2[5].mux_final.out  = 1'h0;
  assign \mux_layer2[5].mux_final.sel  = op[1];
  assign \mux_layer2[6].mux_final.out  = 1'h0;
  assign \mux_layer2[6].mux_final.sel  = op[1];
  assign \mux_layer2[7].mux_final.out  = 1'h0;
  assign \mux_layer2[7].mux_final.sel  = op[1];
  assign \u_adder.a  = rs;
  assign \u_adder.b  = rt;
  assign \u_div.a  = rs;
  assign \u_div.b  = rt;
  assign \u_mul.a  = rs;
  assign \u_mul.b  = rt;
  assign \u_sub.a  = rs;
  assign \u_sub.b  = rt;
endmodule

(* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:1.1-1202.10" *)
module arrdiv(a, b, arrdiv_out);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:1.27-1.28" *)
  input [7:0] a;
  wire [7:0] a;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:35.8-35.36" *)
  wire arrdiv_mux2to10_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:117.8-117.37" *)
  wire arrdiv_mux2to110_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:121.8-121.37" *)
  wire arrdiv_mux2to111_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:125.8-125.37" *)
  wire arrdiv_mux2to112_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:129.8-129.37" *)
  wire arrdiv_mux2to113_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:187.8-187.37" *)
  wire arrdiv_mux2to114_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:191.8-191.37" *)
  wire arrdiv_mux2to115_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:195.8-195.37" *)
  wire arrdiv_mux2to116_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:199.8-199.37" *)
  wire arrdiv_mux2to117_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:203.8-203.37" *)
  wire arrdiv_mux2to118_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:207.8-207.37" *)
  wire arrdiv_mux2to119_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:38.8-38.36" *)
  wire arrdiv_mux2to11_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:211.8-211.37" *)
  wire arrdiv_mux2to120_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:269.8-269.37" *)
  wire arrdiv_mux2to121_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:273.8-273.37" *)
  wire arrdiv_mux2to122_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:277.8-277.37" *)
  wire arrdiv_mux2to123_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:281.8-281.37" *)
  wire arrdiv_mux2to124_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:285.8-285.37" *)
  wire arrdiv_mux2to125_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:289.8-289.37" *)
  wire arrdiv_mux2to126_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:293.8-293.37" *)
  wire arrdiv_mux2to127_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:351.8-351.37" *)
  wire arrdiv_mux2to128_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:355.8-355.37" *)
  wire arrdiv_mux2to129_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:40.8-40.36" *)
  wire arrdiv_mux2to12_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:359.8-359.37" *)
  wire arrdiv_mux2to130_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:363.8-363.37" *)
  wire arrdiv_mux2to131_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:367.8-367.37" *)
  wire arrdiv_mux2to132_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:371.8-371.37" *)
  wire arrdiv_mux2to133_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:375.8-375.37" *)
  wire arrdiv_mux2to134_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:433.8-433.37" *)
  wire arrdiv_mux2to135_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:437.8-437.37" *)
  wire arrdiv_mux2to136_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:441.8-441.37" *)
  wire arrdiv_mux2to137_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:445.8-445.37" *)
  wire arrdiv_mux2to138_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:449.8-449.37" *)
  wire arrdiv_mux2to139_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:42.8-42.36" *)
  wire arrdiv_mux2to13_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:453.8-453.37" *)
  wire arrdiv_mux2to140_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:457.8-457.37" *)
  wire arrdiv_mux2to141_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:515.8-515.37" *)
  wire arrdiv_mux2to142_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:519.8-519.37" *)
  wire arrdiv_mux2to143_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:523.8-523.37" *)
  wire arrdiv_mux2to144_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:527.8-527.37" *)
  wire arrdiv_mux2to145_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:531.8-531.37" *)
  wire arrdiv_mux2to146_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:535.8-535.37" *)
  wire arrdiv_mux2to147_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:539.8-539.37" *)
  wire arrdiv_mux2to148_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:44.8-44.36" *)
  wire arrdiv_mux2to14_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:46.8-46.36" *)
  wire arrdiv_mux2to15_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:48.8-48.36" *)
  wire arrdiv_mux2to16_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:105.8-105.36" *)
  wire arrdiv_mux2to17_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:109.8-109.36" *)
  wire arrdiv_mux2to18_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:113.8-113.36" *)
  wire arrdiv_mux2to19_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:50.8-50.19" *)
  wire arrdiv_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:132.8-132.19" *)
  wire arrdiv_not1;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:214.8-214.19" *)
  wire arrdiv_not2;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:296.8-296.19" *)
  wire arrdiv_not3;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:378.8-378.19" *)
  wire arrdiv_not4;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:460.8-460.19" *)
  wire arrdiv_not5;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:542.8-542.19" *)
  wire arrdiv_not6;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:596.8-596.19" *)
  wire arrdiv_not7;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:1.58-1.68" *)
  output [7:0] arrdiv_out;
  wire [7:0] arrdiv_out;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:1.42-1.43" *)
  input [7:0] b;
  wire [7:0] b;
  sky130_fd_sc_hd__clkinv_1 _136_ (
    .A(b[1]),
    .Y(_066_)
  );
  sky130_fd_sc_hd__clkinv_1 _137_ (
    .A(b[3]),
    .Y(_067_)
  );
  sky130_fd_sc_hd__clkinv_1 _138_ (
    .A(b[7]),
    .Y(_068_)
  );
  sky130_fd_sc_hd__clkinv_1 _139_ (
    .A(b[0]),
    .Y(_069_)
  );
  sky130_fd_sc_hd__nor2_1 _140_ (
    .A(b[6]),
    .B(b[7]),
    .Y(_070_)
  );
  sky130_fd_sc_hd__nor3_1 _141_ (
    .A(b[5]),
    .B(b[6]),
    .C(b[7]),
    .Y(_071_)
  );
  sky130_fd_sc_hd__or4_1 _142_ (
    .A(b[4]),
    .B(b[5]),
    .C(b[6]),
    .D(b[7]),
    .X(_072_)
  );
  sky130_fd_sc_hd__or3_1 _143_ (
    .A(b[2]),
    .B(b[3]),
    .C(_072_),
    .X(_073_)
  );
  sky130_fd_sc_hd__nor4_1 _144_ (
    .A(b[1]),
    .B(b[2]),
    .C(b[3]),
    .D(_072_),
    .Y(_074_)
  );
  sky130_fd_sc_hd__o21a_1 _145_ (
    .A1(a[7]),
    .A2(_069_),
    .B1(_074_),
    .X(arrdiv_mux2to10_mux2to1_not0)
  );
  sky130_fd_sc_hd__nor2_1 _146_ (
    .A(a[6]),
    .B(_069_),
    .Y(_075_)
  );
  sky130_fd_sc_hd__nor2_1 _147_ (
    .A(b[1]),
    .B(_075_),
    .Y(_076_)
  );
  sky130_fd_sc_hd__and3_1 _148_ (
    .A(a[7]),
    .B(_069_),
    .C(_074_),
    .X(_077_)
  );
  sky130_fd_sc_hd__a21boi_0 _149_ (
    .A1(b[0]),
    .A2(_074_),
    .B1_N(a[7]),
    .Y(_078_)
  );
  sky130_fd_sc_hd__nor2_1 _150_ (
    .A(_076_),
    .B(_078_),
    .Y(_079_)
  );
  sky130_fd_sc_hd__a21o_1 _151_ (
    .A1(b[1]),
    .A2(_075_),
    .B1(_073_),
    .X(_080_)
  );
  sky130_fd_sc_hd__nor2_1 _152_ (
    .A(_079_),
    .B(_080_),
    .Y(arrdiv_mux2to110_mux2to1_not0)
  );
  sky130_fd_sc_hd__a21oi_1 _153_ (
    .A1(_078_),
    .A2(_080_),
    .B1(_077_),
    .Y(_081_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _154_ (
    .A(b[2]),
    .SLEEP(_081_),
    .X(_082_)
  );
  sky130_fd_sc_hd__o31ai_1 _155_ (
    .A1(_069_),
    .A2(_073_),
    .A3(_079_),
    .B1(a[6]),
    .Y(_083_)
  );
  sky130_fd_sc_hd__xnor2_1 _156_ (
    .A(b[1]),
    .B(_083_),
    .Y(_084_)
  );
  sky130_fd_sc_hd__nor2_1 _157_ (
    .A(a[5]),
    .B(_069_),
    .Y(_085_)
  );
  sky130_fd_sc_hd__maj3_1 _158_ (
    .A(b[1]),
    .B(_083_),
    .C(_085_),
    .X(_086_)
  );
  sky130_fd_sc_hd__a211o_1 _159_ (
    .A1(b[2]),
    .A2(_081_),
    .B1(_072_),
    .C1(b[3]),
    .X(_087_)
  );
  sky130_fd_sc_hd__a21oi_1 _160_ (
    .A1(_082_),
    .A2(_086_),
    .B1(_087_),
    .Y(arrdiv_mux2to114_mux2to1_not0)
  );
  sky130_fd_sc_hd__o21bai_1 _161_ (
    .A1(_081_),
    .A2(arrdiv_mux2to114_mux2to1_not0),
    .B1_N(_077_),
    .Y(_088_)
  );
  sky130_fd_sc_hd__nand2_1 _162_ (
    .A(_067_),
    .B(_088_),
    .Y(_089_)
  );
  sky130_fd_sc_hd__xnor2_1 _163_ (
    .A(_084_),
    .B(_085_),
    .Y(_090_)
  );
  sky130_fd_sc_hd__mux2i_1 _164_ (
    .A0(_083_),
    .A1(_090_),
    .S(arrdiv_mux2to114_mux2to1_not0),
    .Y(_091_)
  );
  sky130_fd_sc_hd__clkinv_1 _165_ (
    .A(_091_),
    .Y(_092_)
  );
  sky130_fd_sc_hd__xnor2_1 _166_ (
    .A(b[2]),
    .B(_091_),
    .Y(_093_)
  );
  sky130_fd_sc_hd__a211oi_1 _167_ (
    .A1(_082_),
    .A2(_086_),
    .B1(_087_),
    .C1(_069_),
    .Y(_094_)
  );
  sky130_fd_sc_hd__xnor2_1 _168_ (
    .A(a[5]),
    .B(_094_),
    .Y(_095_)
  );
  sky130_fd_sc_hd__xnor2_1 _169_ (
    .A(b[1]),
    .B(_095_),
    .Y(_096_)
  );
  sky130_fd_sc_hd__nor2_1 _170_ (
    .A(a[4]),
    .B(_069_),
    .Y(_097_)
  );
  sky130_fd_sc_hd__maj3_1 _171_ (
    .A(b[1]),
    .B(_095_),
    .C(_097_),
    .X(_098_)
  );
  sky130_fd_sc_hd__maj3_1 _172_ (
    .A(b[2]),
    .B(_092_),
    .C(_098_),
    .X(_099_)
  );
  sky130_fd_sc_hd__o21bai_1 _173_ (
    .A1(_067_),
    .A2(_088_),
    .B1_N(_072_),
    .Y(_100_)
  );
  sky130_fd_sc_hd__a21o_1 _174_ (
    .A1(_089_),
    .A2(_099_),
    .B1(_100_),
    .X(_101_)
  );
  sky130_fd_sc_hd__clkinv_1 _175_ (
    .A(_101_),
    .Y(arrdiv_mux2to121_mux2to1_not0)
  );
  sky130_fd_sc_hd__a21oi_1 _176_ (
    .A1(_088_),
    .A2(_101_),
    .B1(_077_),
    .Y(_102_)
  );
  sky130_fd_sc_hd__nor2_1 _177_ (
    .A(b[4]),
    .B(_102_),
    .Y(_103_)
  );
  sky130_fd_sc_hd__xnor2_1 _178_ (
    .A(_093_),
    .B(_098_),
    .Y(_104_)
  );
  sky130_fd_sc_hd__mux2i_1 _179_ (
    .A0(_091_),
    .A1(_104_),
    .S(arrdiv_mux2to121_mux2to1_not0),
    .Y(_105_)
  );
  sky130_fd_sc_hd__xnor2_1 _180_ (
    .A(b[3]),
    .B(_105_),
    .Y(_106_)
  );
  sky130_fd_sc_hd__clkinv_1 _181_ (
    .A(_106_),
    .Y(_107_)
  );
  sky130_fd_sc_hd__xnor2_1 _182_ (
    .A(_096_),
    .B(_097_),
    .Y(_108_)
  );
  sky130_fd_sc_hd__mux2i_1 _183_ (
    .A0(_095_),
    .A1(_108_),
    .S(arrdiv_mux2to121_mux2to1_not0),
    .Y(_109_)
  );
  sky130_fd_sc_hd__clkinv_1 _184_ (
    .A(_109_),
    .Y(_110_)
  );
  sky130_fd_sc_hd__xnor2_1 _185_ (
    .A(b[2]),
    .B(_109_),
    .Y(_111_)
  );
  sky130_fd_sc_hd__a211oi_1 _186_ (
    .A1(_089_),
    .A2(_099_),
    .B1(_100_),
    .C1(_069_),
    .Y(_112_)
  );
  sky130_fd_sc_hd__xnor2_1 _187_ (
    .A(a[4]),
    .B(_112_),
    .Y(_113_)
  );
  sky130_fd_sc_hd__xnor2_1 _188_ (
    .A(b[1]),
    .B(_113_),
    .Y(_114_)
  );
  sky130_fd_sc_hd__nor2_1 _189_ (
    .A(a[3]),
    .B(_069_),
    .Y(_115_)
  );
  sky130_fd_sc_hd__maj3_1 _190_ (
    .A(b[1]),
    .B(_113_),
    .C(_115_),
    .X(_116_)
  );
  sky130_fd_sc_hd__maj3_1 _191_ (
    .A(b[2]),
    .B(_110_),
    .C(_116_),
    .X(_117_)
  );
  sky130_fd_sc_hd__a22o_1 _192_ (
    .A1(b[4]),
    .A2(_102_),
    .B1(_105_),
    .B2(b[3]),
    .X(_118_)
  );
  sky130_fd_sc_hd__a21oi_1 _193_ (
    .A1(_107_),
    .A2(_117_),
    .B1(_118_),
    .Y(_119_)
  );
  sky130_fd_sc_hd__o21ai_0 _194_ (
    .A1(_103_),
    .A2(_119_),
    .B1(_071_),
    .Y(_120_)
  );
  sky130_fd_sc_hd__clkinv_1 _195_ (
    .A(_120_),
    .Y(arrdiv_mux2to128_mux2to1_not0)
  );
  sky130_fd_sc_hd__a31oi_1 _196_ (
    .A1(_088_),
    .A2(_101_),
    .A3(_120_),
    .B1(_077_),
    .Y(_121_)
  );
  sky130_fd_sc_hd__nor2_1 _197_ (
    .A(b[5]),
    .B(_121_),
    .Y(_122_)
  );
  sky130_fd_sc_hd__xnor2_1 _198_ (
    .A(_107_),
    .B(_117_),
    .Y(_123_)
  );
  sky130_fd_sc_hd__nand2_1 _199_ (
    .A(_105_),
    .B(_120_),
    .Y(_124_)
  );
  sky130_fd_sc_hd__o21ai_0 _200_ (
    .A1(_120_),
    .A2(_123_),
    .B1(_124_),
    .Y(_125_)
  );
  sky130_fd_sc_hd__xnor2_1 _201_ (
    .A(b[4]),
    .B(_125_),
    .Y(_126_)
  );
  sky130_fd_sc_hd__clkinv_1 _202_ (
    .A(_126_),
    .Y(_127_)
  );
  sky130_fd_sc_hd__xnor2_1 _203_ (
    .A(_111_),
    .B(_116_),
    .Y(_128_)
  );
  sky130_fd_sc_hd__mux2i_1 _204_ (
    .A0(_128_),
    .A1(_109_),
    .S(_120_),
    .Y(_129_)
  );
  sky130_fd_sc_hd__xnor2_1 _205_ (
    .A(_067_),
    .B(_129_),
    .Y(_130_)
  );
  sky130_fd_sc_hd__xnor2_1 _206_ (
    .A(_114_),
    .B(_115_),
    .Y(_131_)
  );
  sky130_fd_sc_hd__mux2_1 _207_ (
    .A0(_131_),
    .A1(_113_),
    .S(_120_),
    .X(_132_)
  );
  sky130_fd_sc_hd__xor2_1 _208_ (
    .A(b[2]),
    .B(_132_),
    .X(_133_)
  );
  sky130_fd_sc_hd__o211ai_1 _209_ (
    .A1(_103_),
    .A2(_119_),
    .B1(b[0]),
    .C1(_071_),
    .Y(_134_)
  );
  sky130_fd_sc_hd__xor2_1 _210_ (
    .A(a[3]),
    .B(_134_),
    .X(_135_)
  );
  sky130_fd_sc_hd__xnor2_1 _211_ (
    .A(_066_),
    .B(_135_),
    .Y(_000_)
  );
  sky130_fd_sc_hd__nor2_1 _212_ (
    .A(a[2]),
    .B(_069_),
    .Y(_001_)
  );
  sky130_fd_sc_hd__maj3_1 _213_ (
    .A(b[1]),
    .B(_135_),
    .C(_001_),
    .X(_002_)
  );
  sky130_fd_sc_hd__and2_0 _214_ (
    .A(_133_),
    .B(_002_),
    .X(_003_)
  );
  sky130_fd_sc_hd__maj3_1 _215_ (
    .A(b[2]),
    .B(_132_),
    .C(_002_),
    .X(_004_)
  );
  sky130_fd_sc_hd__maj3_1 _216_ (
    .A(b[3]),
    .B(_129_),
    .C(_004_),
    .X(_005_)
  );
  sky130_fd_sc_hd__a22o_1 _217_ (
    .A1(b[5]),
    .A2(_121_),
    .B1(_125_),
    .B2(b[4]),
    .X(_006_)
  );
  sky130_fd_sc_hd__a21oi_1 _218_ (
    .A1(_127_),
    .A2(_005_),
    .B1(_006_),
    .Y(_007_)
  );
  sky130_fd_sc_hd__o21ai_0 _219_ (
    .A1(_122_),
    .A2(_007_),
    .B1(_070_),
    .Y(_008_)
  );
  sky130_fd_sc_hd__clkinv_1 _220_ (
    .A(_008_),
    .Y(arrdiv_mux2to135_mux2to1_not0)
  );
  sky130_fd_sc_hd__nor2_1 _221_ (
    .A(_121_),
    .B(arrdiv_mux2to135_mux2to1_not0),
    .Y(_009_)
  );
  sky130_fd_sc_hd__nor2_1 _222_ (
    .A(_077_),
    .B(_009_),
    .Y(_010_)
  );
  sky130_fd_sc_hd__nor2_1 _223_ (
    .A(b[6]),
    .B(_010_),
    .Y(_011_)
  );
  sky130_fd_sc_hd__xnor2_1 _224_ (
    .A(_127_),
    .B(_005_),
    .Y(_012_)
  );
  sky130_fd_sc_hd__nand2_1 _225_ (
    .A(_125_),
    .B(_008_),
    .Y(_013_)
  );
  sky130_fd_sc_hd__o21ai_0 _226_ (
    .A1(_008_),
    .A2(_012_),
    .B1(_013_),
    .Y(_014_)
  );
  sky130_fd_sc_hd__xnor2_1 _227_ (
    .A(b[5]),
    .B(_014_),
    .Y(_015_)
  );
  sky130_fd_sc_hd__clkinv_1 _228_ (
    .A(_015_),
    .Y(_016_)
  );
  sky130_fd_sc_hd__xnor2_1 _229_ (
    .A(_130_),
    .B(_004_),
    .Y(_017_)
  );
  sky130_fd_sc_hd__nand2_1 _230_ (
    .A(_129_),
    .B(_008_),
    .Y(_018_)
  );
  sky130_fd_sc_hd__o21ai_0 _231_ (
    .A1(_008_),
    .A2(_017_),
    .B1(_018_),
    .Y(_019_)
  );
  sky130_fd_sc_hd__xor2_1 _232_ (
    .A(b[4]),
    .B(_019_),
    .X(_020_)
  );
  sky130_fd_sc_hd__nor2_1 _233_ (
    .A(_133_),
    .B(_002_),
    .Y(_021_)
  );
  sky130_fd_sc_hd__nand2_1 _234_ (
    .A(_132_),
    .B(_008_),
    .Y(_022_)
  );
  sky130_fd_sc_hd__o31ai_1 _235_ (
    .A1(_003_),
    .A2(_008_),
    .A3(_021_),
    .B1(_022_),
    .Y(_023_)
  );
  sky130_fd_sc_hd__xnor2_1 _236_ (
    .A(b[3]),
    .B(_023_),
    .Y(_024_)
  );
  sky130_fd_sc_hd__xnor2_1 _237_ (
    .A(_000_),
    .B(_001_),
    .Y(_025_)
  );
  sky130_fd_sc_hd__nand2_1 _238_ (
    .A(_135_),
    .B(_008_),
    .Y(_026_)
  );
  sky130_fd_sc_hd__o21ai_0 _239_ (
    .A1(_008_),
    .A2(_025_),
    .B1(_026_),
    .Y(_027_)
  );
  sky130_fd_sc_hd__xnor2_1 _240_ (
    .A(b[2]),
    .B(_027_),
    .Y(_028_)
  );
  sky130_fd_sc_hd__o211ai_1 _241_ (
    .A1(_122_),
    .A2(_007_),
    .B1(b[0]),
    .C1(_070_),
    .Y(_029_)
  );
  sky130_fd_sc_hd__xor2_1 _242_ (
    .A(a[2]),
    .B(_029_),
    .X(_030_)
  );
  sky130_fd_sc_hd__xnor2_1 _243_ (
    .A(b[1]),
    .B(_030_),
    .Y(_031_)
  );
  sky130_fd_sc_hd__nor2_1 _244_ (
    .A(a[1]),
    .B(_069_),
    .Y(_032_)
  );
  sky130_fd_sc_hd__nand2b_1 _245_ (
    .A_N(a[1]),
    .B(b[0]),
    .Y(_033_)
  );
  sky130_fd_sc_hd__maj3_1 _246_ (
    .A(b[1]),
    .B(_030_),
    .C(_032_),
    .X(_034_)
  );
  sky130_fd_sc_hd__maj3_1 _247_ (
    .A(b[2]),
    .B(_027_),
    .C(_034_),
    .X(_035_)
  );
  sky130_fd_sc_hd__maj3_1 _248_ (
    .A(b[3]),
    .B(_023_),
    .C(_035_),
    .X(_036_)
  );
  sky130_fd_sc_hd__maj3_1 _249_ (
    .A(b[4]),
    .B(_019_),
    .C(_036_),
    .X(_037_)
  );
  sky130_fd_sc_hd__a22o_1 _250_ (
    .A1(b[6]),
    .A2(_010_),
    .B1(_014_),
    .B2(b[5]),
    .X(_038_)
  );
  sky130_fd_sc_hd__a21oi_1 _251_ (
    .A1(_016_),
    .A2(_037_),
    .B1(_038_),
    .Y(_039_)
  );
  sky130_fd_sc_hd__o21ai_0 _252_ (
    .A1(_011_),
    .A2(_039_),
    .B1(_068_),
    .Y(_040_)
  );
  sky130_fd_sc_hd__clkinv_1 _253_ (
    .A(_040_),
    .Y(arrdiv_mux2to142_mux2to1_not0)
  );
  sky130_fd_sc_hd__a21oi_1 _254_ (
    .A1(_009_),
    .A2(_040_),
    .B1(_077_),
    .Y(_041_)
  );
  sky130_fd_sc_hd__o211ai_1 _255_ (
    .A1(_011_),
    .A2(_039_),
    .B1(_068_),
    .C1(b[0]),
    .Y(_042_)
  );
  sky130_fd_sc_hd__a2bb2oi_1 _256_ (
    .A1_N(_033_),
    .A2_N(_040_),
    .B1(_042_),
    .B2(a[1]),
    .Y(_043_)
  );
  sky130_fd_sc_hd__nor3_1 _257_ (
    .A(_066_),
    .B(a[0]),
    .C(_069_),
    .Y(_044_)
  );
  sky130_fd_sc_hd__o21ai_0 _258_ (
    .A1(a[0]),
    .A2(_069_),
    .B1(_066_),
    .Y(_045_)
  );
  sky130_fd_sc_hd__xnor2_1 _259_ (
    .A(_031_),
    .B(_032_),
    .Y(_046_)
  );
  sky130_fd_sc_hd__mux2_1 _260_ (
    .A0(_046_),
    .A1(_030_),
    .S(_040_),
    .X(_047_)
  );
  sky130_fd_sc_hd__o221ai_1 _261_ (
    .A1(_043_),
    .A2(_044_),
    .B1(_047_),
    .B2(b[2]),
    .C1(_045_),
    .Y(_048_)
  );
  sky130_fd_sc_hd__xnor2_1 _262_ (
    .A(_028_),
    .B(_034_),
    .Y(_049_)
  );
  sky130_fd_sc_hd__mux2_1 _263_ (
    .A0(_049_),
    .A1(_027_),
    .S(_040_),
    .X(_050_)
  );
  sky130_fd_sc_hd__a22oi_1 _264_ (
    .A1(b[2]),
    .A2(_047_),
    .B1(_050_),
    .B2(b[3]),
    .Y(_051_)
  );
  sky130_fd_sc_hd__xnor2_1 _265_ (
    .A(_024_),
    .B(_035_),
    .Y(_052_)
  );
  sky130_fd_sc_hd__mux2_1 _266_ (
    .A0(_052_),
    .A1(_023_),
    .S(_040_),
    .X(_053_)
  );
  sky130_fd_sc_hd__o22ai_1 _267_ (
    .A1(b[3]),
    .A2(_050_),
    .B1(_053_),
    .B2(b[4]),
    .Y(_054_)
  );
  sky130_fd_sc_hd__a21o_1 _268_ (
    .A1(_048_),
    .A2(_051_),
    .B1(_054_),
    .X(_055_)
  );
  sky130_fd_sc_hd__xnor2_1 _269_ (
    .A(_020_),
    .B(_036_),
    .Y(_056_)
  );
  sky130_fd_sc_hd__nand2_1 _270_ (
    .A(_019_),
    .B(_040_),
    .Y(_057_)
  );
  sky130_fd_sc_hd__o21ai_0 _271_ (
    .A1(_040_),
    .A2(_056_),
    .B1(_057_),
    .Y(_058_)
  );
  sky130_fd_sc_hd__a22oi_1 _272_ (
    .A1(b[4]),
    .A2(_053_),
    .B1(_058_),
    .B2(b[5]),
    .Y(_059_)
  );
  sky130_fd_sc_hd__xnor2_1 _273_ (
    .A(_016_),
    .B(_037_),
    .Y(_060_)
  );
  sky130_fd_sc_hd__nand2_1 _274_ (
    .A(_014_),
    .B(_040_),
    .Y(_061_)
  );
  sky130_fd_sc_hd__o21ai_0 _275_ (
    .A1(_040_),
    .A2(_060_),
    .B1(_061_),
    .Y(_062_)
  );
  sky130_fd_sc_hd__o22ai_1 _276_ (
    .A1(b[5]),
    .A2(_058_),
    .B1(_062_),
    .B2(b[6]),
    .Y(_063_)
  );
  sky130_fd_sc_hd__a21oi_1 _277_ (
    .A1(_055_),
    .A2(_059_),
    .B1(_063_),
    .Y(_064_)
  );
  sky130_fd_sc_hd__a22o_1 _278_ (
    .A1(b[7]),
    .A2(_041_),
    .B1(_062_),
    .B2(b[6]),
    .X(_065_)
  );
  sky130_fd_sc_hd__o22ai_1 _279_ (
    .A1(b[7]),
    .A2(_041_),
    .B1(_064_),
    .B2(_065_),
    .Y(arrdiv_not7)
  );
  assign arrdiv_mux2to111_mux2to1_not0 = arrdiv_mux2to110_mux2to1_not0;
  assign arrdiv_mux2to112_mux2to1_not0 = arrdiv_mux2to110_mux2to1_not0;
  assign arrdiv_mux2to113_mux2to1_not0 = arrdiv_mux2to110_mux2to1_not0;
  assign arrdiv_mux2to115_mux2to1_not0 = arrdiv_mux2to114_mux2to1_not0;
  assign arrdiv_mux2to116_mux2to1_not0 = arrdiv_mux2to114_mux2to1_not0;
  assign arrdiv_mux2to117_mux2to1_not0 = arrdiv_mux2to114_mux2to1_not0;
  assign arrdiv_mux2to118_mux2to1_not0 = arrdiv_mux2to114_mux2to1_not0;
  assign arrdiv_mux2to119_mux2to1_not0 = arrdiv_mux2to114_mux2to1_not0;
  assign arrdiv_mux2to11_mux2to1_not0 = arrdiv_mux2to10_mux2to1_not0;
  assign arrdiv_mux2to120_mux2to1_not0 = arrdiv_mux2to114_mux2to1_not0;
  assign arrdiv_mux2to122_mux2to1_not0 = arrdiv_mux2to121_mux2to1_not0;
  assign arrdiv_mux2to123_mux2to1_not0 = arrdiv_mux2to121_mux2to1_not0;
  assign arrdiv_mux2to124_mux2to1_not0 = arrdiv_mux2to121_mux2to1_not0;
  assign arrdiv_mux2to125_mux2to1_not0 = arrdiv_mux2to121_mux2to1_not0;
  assign arrdiv_mux2to126_mux2to1_not0 = arrdiv_mux2to121_mux2to1_not0;
  assign arrdiv_mux2to127_mux2to1_not0 = arrdiv_mux2to121_mux2to1_not0;
  assign arrdiv_mux2to129_mux2to1_not0 = arrdiv_mux2to128_mux2to1_not0;
  assign arrdiv_mux2to12_mux2to1_not0 = arrdiv_mux2to10_mux2to1_not0;
  assign arrdiv_mux2to130_mux2to1_not0 = arrdiv_mux2to128_mux2to1_not0;
  assign arrdiv_mux2to131_mux2to1_not0 = arrdiv_mux2to128_mux2to1_not0;
  assign arrdiv_mux2to132_mux2to1_not0 = arrdiv_mux2to128_mux2to1_not0;
  assign arrdiv_mux2to133_mux2to1_not0 = arrdiv_mux2to128_mux2to1_not0;
  assign arrdiv_mux2to134_mux2to1_not0 = arrdiv_mux2to128_mux2to1_not0;
  assign arrdiv_mux2to136_mux2to1_not0 = arrdiv_mux2to135_mux2to1_not0;
  assign arrdiv_mux2to137_mux2to1_not0 = arrdiv_mux2to135_mux2to1_not0;
  assign arrdiv_mux2to138_mux2to1_not0 = arrdiv_mux2to135_mux2to1_not0;
  assign arrdiv_mux2to139_mux2to1_not0 = arrdiv_mux2to135_mux2to1_not0;
  assign arrdiv_mux2to13_mux2to1_not0 = arrdiv_mux2to10_mux2to1_not0;
  assign arrdiv_mux2to140_mux2to1_not0 = arrdiv_mux2to135_mux2to1_not0;
  assign arrdiv_mux2to141_mux2to1_not0 = arrdiv_mux2to135_mux2to1_not0;
  assign arrdiv_mux2to143_mux2to1_not0 = arrdiv_mux2to142_mux2to1_not0;
  assign arrdiv_mux2to144_mux2to1_not0 = arrdiv_mux2to142_mux2to1_not0;
  assign arrdiv_mux2to145_mux2to1_not0 = arrdiv_mux2to142_mux2to1_not0;
  assign arrdiv_mux2to146_mux2to1_not0 = arrdiv_mux2to142_mux2to1_not0;
  assign arrdiv_mux2to147_mux2to1_not0 = arrdiv_mux2to142_mux2to1_not0;
  assign arrdiv_mux2to148_mux2to1_not0 = arrdiv_mux2to142_mux2to1_not0;
  assign arrdiv_mux2to14_mux2to1_not0 = arrdiv_mux2to10_mux2to1_not0;
  assign arrdiv_mux2to15_mux2to1_not0 = arrdiv_mux2to10_mux2to1_not0;
  assign arrdiv_mux2to16_mux2to1_not0 = arrdiv_mux2to10_mux2to1_not0;
  assign arrdiv_mux2to17_mux2to1_not0 = arrdiv_mux2to110_mux2to1_not0;
  assign arrdiv_mux2to18_mux2to1_not0 = arrdiv_mux2to110_mux2to1_not0;
  assign arrdiv_mux2to19_mux2to1_not0 = arrdiv_mux2to110_mux2to1_not0;
  assign arrdiv_not0 = arrdiv_mux2to10_mux2to1_not0;
  assign arrdiv_not1 = arrdiv_mux2to110_mux2to1_not0;
  assign arrdiv_not2 = arrdiv_mux2to114_mux2to1_not0;
  assign arrdiv_not3 = arrdiv_mux2to121_mux2to1_not0;
  assign arrdiv_not4 = arrdiv_mux2to128_mux2to1_not0;
  assign arrdiv_not5 = arrdiv_mux2to135_mux2to1_not0;
  assign arrdiv_not6 = arrdiv_mux2to142_mux2to1_not0;
  assign arrdiv_out = { arrdiv_mux2to10_mux2to1_not0, arrdiv_mux2to110_mux2to1_not0, arrdiv_mux2to114_mux2to1_not0, arrdiv_mux2to121_mux2to1_not0, arrdiv_mux2to128_mux2to1_not0, arrdiv_mux2to135_mux2to1_not0, arrdiv_mux2to142_mux2to1_not0, arrdiv_not7 };
endmodule

(* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:1.1-23.10" *)
module mux2to1(sel, in0, in1, out);
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:3.16-3.19" *)
  input in0;
  wire in0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:4.16-4.19" *)
  input in1;
  wire in1;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:5.17-5.20" *)
  output out;
  wire out;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:2.16-2.19" *)
  input sel;
  wire sel;
  sky130_fd_sc_hd__mux2_1 _0_ (
    .A0(in0),
    .A1(in1),
    .S(sel),
    .X(out)
  );
endmodule

(* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/cla8.v:1.1-171.10" *)
module u_cla(a, b, u_cla_out);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/cla8.v:1.26-1.27" *)
  input [7:0] a;
  wire [7:0] a;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/cla8.v:1.41-1.42" *)
  input [7:0] b;
  wire [7:0] b;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/cla8.v:80.8-80.24" *)
  wire u_cla_or1_3_3_15;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/cla8.v:1.57-1.66" *)
  output [8:0] u_cla_out;
  wire [8:0] u_cla_out;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/cla8.v:4.8-4.37" *)
  wire u_cla_pg_logic0_pg_logic_xor0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/cla8.v:8.8-8.18" *)
  wire u_cla_xor1;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/cla8.v:14.8-14.18" *)
  wire u_cla_xor2;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/cla8.v:24.8-24.18" *)
  wire u_cla_xor3;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/cla8.v:38.8-38.18" *)
  wire u_cla_xor4;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/cla8.v:44.8-44.18" *)
  wire u_cla_xor5;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/cla8.v:53.8-53.18" *)
  wire u_cla_xor6;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/cla8.v:66.8-66.18" *)
  wire u_cla_xor7;
  sky130_fd_sc_hd__nand2_1 _24_ (
    .A(a[0]),
    .B(b[0]),
    .Y(_00_)
  );
  sky130_fd_sc_hd__xor2_1 _25_ (
    .A(a[0]),
    .B(b[0]),
    .X(u_cla_pg_logic0_pg_logic_xor0)
  );
  sky130_fd_sc_hd__nand2_1 _26_ (
    .A(a[1]),
    .B(b[1]),
    .Y(_01_)
  );
  sky130_fd_sc_hd__nor2_1 _27_ (
    .A(a[1]),
    .B(b[1]),
    .Y(_02_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _28_ (
    .A(_01_),
    .SLEEP(_02_),
    .X(_03_)
  );
  sky130_fd_sc_hd__xnor2_1 _29_ (
    .A(_00_),
    .B(_03_),
    .Y(u_cla_xor1)
  );
  sky130_fd_sc_hd__o21ai_0 _30_ (
    .A1(_00_),
    .A2(_02_),
    .B1(_01_),
    .Y(_04_)
  );
  sky130_fd_sc_hd__xnor2_1 _31_ (
    .A(a[2]),
    .B(b[2]),
    .Y(_05_)
  );
  sky130_fd_sc_hd__xnor2_1 _32_ (
    .A(_04_),
    .B(_05_),
    .Y(u_cla_xor2)
  );
  sky130_fd_sc_hd__maj3_1 _33_ (
    .A(a[2]),
    .B(b[2]),
    .C(_04_),
    .X(_06_)
  );
  sky130_fd_sc_hd__xnor2_1 _34_ (
    .A(a[3]),
    .B(b[3]),
    .Y(_07_)
  );
  sky130_fd_sc_hd__xnor2_1 _35_ (
    .A(_06_),
    .B(_07_),
    .Y(u_cla_xor3)
  );
  sky130_fd_sc_hd__maj3_1 _36_ (
    .A(a[3]),
    .B(b[3]),
    .C(_06_),
    .X(_08_)
  );
  sky130_fd_sc_hd__xnor2_1 _37_ (
    .A(a[4]),
    .B(b[4]),
    .Y(_09_)
  );
  sky130_fd_sc_hd__xnor2_1 _38_ (
    .A(_08_),
    .B(_09_),
    .Y(u_cla_xor4)
  );
  sky130_fd_sc_hd__o21ai_0 _39_ (
    .A1(a[4]),
    .A2(b[4]),
    .B1(_08_),
    .Y(_10_)
  );
  sky130_fd_sc_hd__maj3_1 _40_ (
    .A(a[4]),
    .B(b[4]),
    .C(_08_),
    .X(_11_)
  );
  sky130_fd_sc_hd__xnor2_1 _41_ (
    .A(a[5]),
    .B(b[5]),
    .Y(_12_)
  );
  sky130_fd_sc_hd__xnor2_1 _42_ (
    .A(_11_),
    .B(_12_),
    .Y(u_cla_xor5)
  );
  sky130_fd_sc_hd__maj3_1 _43_ (
    .A(a[5]),
    .B(b[5]),
    .C(_11_),
    .X(_13_)
  );
  sky130_fd_sc_hd__xnor2_1 _44_ (
    .A(a[6]),
    .B(b[6]),
    .Y(_14_)
  );
  sky130_fd_sc_hd__xnor2_1 _45_ (
    .A(_13_),
    .B(_14_),
    .Y(u_cla_xor6)
  );
  sky130_fd_sc_hd__maj3_1 _46_ (
    .A(a[6]),
    .B(b[6]),
    .C(_13_),
    .X(_15_)
  );
  sky130_fd_sc_hd__nand2_1 _47_ (
    .A(a[7]),
    .B(b[7]),
    .Y(_16_)
  );
  sky130_fd_sc_hd__xnor2_1 _48_ (
    .A(a[7]),
    .B(b[7]),
    .Y(_17_)
  );
  sky130_fd_sc_hd__xnor2_1 _49_ (
    .A(_15_),
    .B(_17_),
    .Y(u_cla_xor7)
  );
  sky130_fd_sc_hd__o211ai_1 _50_ (
    .A1(a[7]),
    .A2(b[7]),
    .B1(a[5]),
    .C1(b[5]),
    .Y(_18_)
  );
  sky130_fd_sc_hd__o22ai_1 _51_ (
    .A1(a[5]),
    .A2(b[5]),
    .B1(a[7]),
    .B2(b[7]),
    .Y(_19_)
  );
  sky130_fd_sc_hd__o21ai_0 _52_ (
    .A1(_10_),
    .A2(_19_),
    .B1(_18_),
    .Y(_20_)
  );
  sky130_fd_sc_hd__o21ai_0 _53_ (
    .A1(a[6]),
    .A2(b[6]),
    .B1(_20_),
    .Y(_21_)
  );
  sky130_fd_sc_hd__o211ai_1 _54_ (
    .A1(a[6]),
    .A2(b[6]),
    .B1(a[4]),
    .C1(b[4]),
    .Y(_22_)
  );
  sky130_fd_sc_hd__o211ai_1 _55_ (
    .A1(a[7]),
    .A2(b[7]),
    .B1(a[6]),
    .C1(b[6]),
    .Y(_23_)
  );
  sky130_fd_sc_hd__o2111ai_1 _56_ (
    .A1(_19_),
    .A2(_22_),
    .B1(_23_),
    .C1(_21_),
    .D1(_16_),
    .Y(u_cla_or1_3_3_15)
  );
  assign u_cla_out = { u_cla_or1_3_3_15, u_cla_xor7, u_cla_xor6, u_cla_xor5, u_cla_xor4, u_cla_xor3, u_cla_xor2, u_cla_xor1, u_cla_pg_logic0_pg_logic_xor0 };
endmodule

(* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/rcs8.v:1.1-109.10" *)
module u_rcs(a, b, u_rcs_out);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/rcs8.v:1.26-1.27" *)
  input [7:0] a;
  wire [7:0] a;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/rcs8.v:1.41-1.42" *)
  input [7:0] b;
  wire [7:0] b;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/rcs8.v:10.8-10.25" *)
  wire u_rcs_fa1_fa_xor1;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/rcs8.v:16.8-16.25" *)
  wire u_rcs_fa2_fa_xor1;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/rcs8.v:22.8-22.25" *)
  wire u_rcs_fa3_fa_xor1;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/rcs8.v:28.8-28.25" *)
  wire u_rcs_fa4_fa_xor1;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/rcs8.v:34.8-34.25" *)
  wire u_rcs_fa5_fa_xor1;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/rcs8.v:40.8-40.25" *)
  wire u_rcs_fa6_fa_xor1;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/rcs8.v:46.8-46.25" *)
  wire u_rcs_fa7_fa_xor1;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/rcs8.v:5.8-5.28" *)
  wire u_rcs_ha_fa_xor1_not;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/rcs8.v:49.8-49.20" *)
  wire u_rcs_not_c7;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/rcs8.v:1.57-1.66" *)
  output [8:0] u_rcs_out;
  wire [8:0] u_rcs_out;
  sky130_fd_sc_hd__clkinv_1 _21_ (
    .A(a[1]),
    .Y(_00_)
  );
  sky130_fd_sc_hd__clkinv_1 _22_ (
    .A(a[2]),
    .Y(_01_)
  );
  sky130_fd_sc_hd__clkinv_1 _23_ (
    .A(a[3]),
    .Y(_02_)
  );
  sky130_fd_sc_hd__clkinv_1 _24_ (
    .A(a[4]),
    .Y(_03_)
  );
  sky130_fd_sc_hd__clkinv_1 _25_ (
    .A(a[5]),
    .Y(_04_)
  );
  sky130_fd_sc_hd__clkinv_1 _26_ (
    .A(a[6]),
    .Y(_05_)
  );
  sky130_fd_sc_hd__clkinv_1 _27_ (
    .A(a[7]),
    .Y(_06_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _28_ (
    .A(b[0]),
    .SLEEP(a[0]),
    .X(_07_)
  );
  sky130_fd_sc_hd__xor2_1 _29_ (
    .A(b[0]),
    .B(a[0]),
    .X(u_rcs_ha_fa_xor1_not)
  );
  sky130_fd_sc_hd__xnor2_1 _30_ (
    .A(b[1]),
    .B(a[1]),
    .Y(_08_)
  );
  sky130_fd_sc_hd__maj3_1 _31_ (
    .A(b[1]),
    .B(_00_),
    .C(_07_),
    .X(_09_)
  );
  sky130_fd_sc_hd__xnor2_1 _32_ (
    .A(b[2]),
    .B(a[2]),
    .Y(_10_)
  );
  sky130_fd_sc_hd__maj3_1 _33_ (
    .A(b[2]),
    .B(_01_),
    .C(_09_),
    .X(_11_)
  );
  sky130_fd_sc_hd__xnor2_1 _34_ (
    .A(b[3]),
    .B(a[3]),
    .Y(_12_)
  );
  sky130_fd_sc_hd__maj3_1 _35_ (
    .A(b[3]),
    .B(_02_),
    .C(_11_),
    .X(_13_)
  );
  sky130_fd_sc_hd__xnor2_1 _36_ (
    .A(b[4]),
    .B(a[4]),
    .Y(_14_)
  );
  sky130_fd_sc_hd__maj3_1 _37_ (
    .A(b[4]),
    .B(_03_),
    .C(_13_),
    .X(_15_)
  );
  sky130_fd_sc_hd__xnor2_1 _38_ (
    .A(b[5]),
    .B(a[5]),
    .Y(_16_)
  );
  sky130_fd_sc_hd__maj3_1 _39_ (
    .A(b[5]),
    .B(_04_),
    .C(_15_),
    .X(_17_)
  );
  sky130_fd_sc_hd__xnor2_1 _40_ (
    .A(b[6]),
    .B(a[6]),
    .Y(_18_)
  );
  sky130_fd_sc_hd__maj3_1 _41_ (
    .A(b[6]),
    .B(_05_),
    .C(_17_),
    .X(_19_)
  );
  sky130_fd_sc_hd__xnor2_1 _42_ (
    .A(b[7]),
    .B(a[7]),
    .Y(_20_)
  );
  sky130_fd_sc_hd__maj3_1 _43_ (
    .A(b[7]),
    .B(_06_),
    .C(_19_),
    .X(u_rcs_not_c7)
  );
  sky130_fd_sc_hd__xnor2_1 _44_ (
    .A(_07_),
    .B(_08_),
    .Y(u_rcs_fa1_fa_xor1)
  );
  sky130_fd_sc_hd__xnor2_1 _45_ (
    .A(_09_),
    .B(_10_),
    .Y(u_rcs_fa2_fa_xor1)
  );
  sky130_fd_sc_hd__xnor2_1 _46_ (
    .A(_11_),
    .B(_12_),
    .Y(u_rcs_fa3_fa_xor1)
  );
  sky130_fd_sc_hd__xnor2_1 _47_ (
    .A(_13_),
    .B(_14_),
    .Y(u_rcs_fa4_fa_xor1)
  );
  sky130_fd_sc_hd__xnor2_1 _48_ (
    .A(_15_),
    .B(_16_),
    .Y(u_rcs_fa5_fa_xor1)
  );
  sky130_fd_sc_hd__xnor2_1 _49_ (
    .A(_17_),
    .B(_18_),
    .Y(u_rcs_fa6_fa_xor1)
  );
  sky130_fd_sc_hd__xnor2_1 _50_ (
    .A(_19_),
    .B(_20_),
    .Y(u_rcs_fa7_fa_xor1)
  );
  assign u_rcs_out = { u_rcs_not_c7, u_rcs_fa7_fa_xor1, u_rcs_fa6_fa_xor1, u_rcs_fa5_fa_xor1, u_rcs_fa4_fa_xor1, u_rcs_fa3_fa_xor1, u_rcs_fa2_fa_xor1, u_rcs_fa1_fa_xor1, u_rcs_ha_fa_xor1_not };
endmodule

(* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/wmu16.v:1.1-812.10" *)
module u_wallace_cla(a, b, u_wallace_cla_out);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/wmu16.v:1.34-1.35" *)
  input [7:0] a;
  wire [7:0] a;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/wmu16.v:1.49-1.50" *)
  input [7:0] b;
  wire [7:0] b;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/wmu16.v:2.8-2.29" *)
  wire u_wallace_cla_and_0_0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/wmu16.v:66.8-66.52" *)
  wire u_wallace_cla_csa0_csa_component_fa1_fa_xor0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/wmu16.v:134.8-134.52" *)
  wire u_wallace_cla_csa2_csa_component_fa2_fa_xor0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/wmu16.v:205.8-205.52" *)
  wire u_wallace_cla_csa4_csa_component_fa3_fa_xor0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/wmu16.v:243.8-243.52" *)
  wire u_wallace_cla_csa5_csa_component_fa4_fa_xor0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/wmu16.v:1.66-1.83" *)
  output [15:0] u_wallace_cla_out;
  wire [15:0] u_wallace_cla_out;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/wmu16.v:291.8-291.53" *)
  wire u_wallace_cla_u_cla16_pg_logic5_pg_logic_xor0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/wmu16.v:328.8-328.35" *)
  wire u_wallace_cla_u_cla16_xor10;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/wmu16.v:341.8-341.35" *)
  wire u_wallace_cla_u_cla16_xor11;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/wmu16.v:359.8-359.35" *)
  wire u_wallace_cla_u_cla16_xor12;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/wmu16.v:365.8-365.35" *)
  wire u_wallace_cla_u_cla16_xor13;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/wmu16.v:374.8-374.35" *)
  wire u_wallace_cla_u_cla16_xor14;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/wmu16.v:384.8-384.35" *)
  wire u_wallace_cla_u_cla16_xor15;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/wmu16.v:295.8-295.34" *)
  wire u_wallace_cla_u_cla16_xor6;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/wmu16.v:302.8-302.34" *)
  wire u_wallace_cla_u_cla16_xor7;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/wmu16.v:313.8-313.34" *)
  wire u_wallace_cla_u_cla16_xor8;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/wmu16.v:319.8-319.34" *)
  wire u_wallace_cla_u_cla16_xor9;
  sky130_fd_sc_hd__and2_0 _212_ (
    .A(a[0]),
    .B(b[0]),
    .X(u_wallace_cla_and_0_0)
  );
  sky130_fd_sc_hd__and4_1 _213_ (
    .A(a[0]),
    .B(b[0]),
    .C(a[1]),
    .D(b[1]),
    .X(_151_)
  );
  sky130_fd_sc_hd__a22oi_1 _214_ (
    .A1(b[0]),
    .A2(a[1]),
    .B1(b[1]),
    .B2(a[0]),
    .Y(_152_)
  );
  sky130_fd_sc_hd__nor2_1 _215_ (
    .A(_151_),
    .B(_152_),
    .Y(u_wallace_cla_csa0_csa_component_fa1_fa_xor0)
  );
  sky130_fd_sc_hd__nand2_1 _216_ (
    .A(a[0]),
    .B(b[2]),
    .Y(_153_)
  );
  sky130_fd_sc_hd__and4_1 _217_ (
    .A(b[0]),
    .B(a[1]),
    .C(a[2]),
    .D(b[1]),
    .X(_154_)
  );
  sky130_fd_sc_hd__a22oi_1 _218_ (
    .A1(b[0]),
    .A2(a[2]),
    .B1(b[1]),
    .B2(a[1]),
    .Y(_155_)
  );
  sky130_fd_sc_hd__or3_1 _219_ (
    .A(_153_),
    .B(_154_),
    .C(_155_),
    .X(_156_)
  );
  sky130_fd_sc_hd__o21ai_0 _220_ (
    .A1(_154_),
    .A2(_155_),
    .B1(_153_),
    .Y(_157_)
  );
  sky130_fd_sc_hd__nand3_1 _221_ (
    .A(_151_),
    .B(_156_),
    .C(_157_),
    .Y(_158_)
  );
  sky130_fd_sc_hd__a21oi_1 _222_ (
    .A1(_156_),
    .A2(_157_),
    .B1(_151_),
    .Y(_159_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _223_ (
    .A(_158_),
    .SLEEP(_159_),
    .X(u_wallace_cla_csa2_csa_component_fa2_fa_xor0)
  );
  sky130_fd_sc_hd__nand2_1 _224_ (
    .A(a[0]),
    .B(b[3]),
    .Y(_160_)
  );
  sky130_fd_sc_hd__o21ba_1 _225_ (
    .A1(_153_),
    .A2(_155_),
    .B1_N(_154_),
    .X(_161_)
  );
  sky130_fd_sc_hd__and2_0 _226_ (
    .A(a[1]),
    .B(b[2]),
    .X(_162_)
  );
  sky130_fd_sc_hd__and2_0 _227_ (
    .A(b[0]),
    .B(a[3]),
    .X(_163_)
  );
  sky130_fd_sc_hd__and2_0 _228_ (
    .A(a[2]),
    .B(b[1]),
    .X(_164_)
  );
  sky130_fd_sc_hd__xnor3_1 _229_ (
    .A(_162_),
    .B(_163_),
    .C(_164_),
    .X(_165_)
  );
  sky130_fd_sc_hd__xor3_1 _230_ (
    .A(_160_),
    .B(_161_),
    .C(_165_),
    .X(_166_)
  );
  sky130_fd_sc_hd__nor2_1 _231_ (
    .A(_158_),
    .B(_166_),
    .Y(_167_)
  );
  sky130_fd_sc_hd__xor2_1 _232_ (
    .A(_158_),
    .B(_166_),
    .X(u_wallace_cla_csa4_csa_component_fa3_fa_xor0)
  );
  sky130_fd_sc_hd__maj3_1 _233_ (
    .A(_160_),
    .B(_161_),
    .C(_165_),
    .X(_168_)
  );
  sky130_fd_sc_hd__maj3_1 _234_ (
    .A(_162_),
    .B(_163_),
    .C(_164_),
    .X(_169_)
  );
  sky130_fd_sc_hd__nand2_1 _235_ (
    .A(a[2]),
    .B(b[2]),
    .Y(_170_)
  );
  sky130_fd_sc_hd__nand2_1 _236_ (
    .A(b[0]),
    .B(a[4]),
    .Y(_171_)
  );
  sky130_fd_sc_hd__nand2_1 _237_ (
    .A(a[3]),
    .B(b[1]),
    .Y(_172_)
  );
  sky130_fd_sc_hd__xnor3_1 _238_ (
    .A(_170_),
    .B(_171_),
    .C(_172_),
    .X(_173_)
  );
  sky130_fd_sc_hd__and4_1 _239_ (
    .A(a[0]),
    .B(a[1]),
    .C(b[3]),
    .D(b[4]),
    .X(_174_)
  );
  sky130_fd_sc_hd__a22oi_1 _240_ (
    .A1(a[1]),
    .A2(b[3]),
    .B1(b[4]),
    .B2(a[0]),
    .Y(_175_)
  );
  sky130_fd_sc_hd__nor2_1 _241_ (
    .A(_174_),
    .B(_175_),
    .Y(_176_)
  );
  sky130_fd_sc_hd__xor3_1 _242_ (
    .A(_169_),
    .B(_173_),
    .C(_176_),
    .X(_177_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _243_ (
    .A(_177_),
    .SLEEP(_168_),
    .X(_178_)
  );
  sky130_fd_sc_hd__nand2b_1 _244_ (
    .A_N(_177_),
    .B(_168_),
    .Y(_179_)
  );
  sky130_fd_sc_hd__nor2b_1 _245_ (
    .A(_178_),
    .B_N(_179_),
    .Y(_180_)
  );
  sky130_fd_sc_hd__nand2_1 _246_ (
    .A(_167_),
    .B(_180_),
    .Y(_181_)
  );
  sky130_fd_sc_hd__xor2_1 _247_ (
    .A(_167_),
    .B(_180_),
    .X(u_wallace_cla_csa5_csa_component_fa4_fa_xor0)
  );
  sky130_fd_sc_hd__maj3_1 _248_ (
    .A(_169_),
    .B(_173_),
    .C(_176_),
    .X(_182_)
  );
  sky130_fd_sc_hd__maj3_1 _249_ (
    .A(_170_),
    .B(_171_),
    .C(_172_),
    .X(_183_)
  );
  sky130_fd_sc_hd__and2_0 _250_ (
    .A(a[3]),
    .B(b[2]),
    .X(_184_)
  );
  sky130_fd_sc_hd__and2_0 _251_ (
    .A(b[0]),
    .B(a[5]),
    .X(_185_)
  );
  sky130_fd_sc_hd__and2_0 _252_ (
    .A(a[4]),
    .B(b[1]),
    .X(_186_)
  );
  sky130_fd_sc_hd__xnor3_1 _253_ (
    .A(_184_),
    .B(_185_),
    .C(_186_),
    .X(_187_)
  );
  sky130_fd_sc_hd__nand2_1 _254_ (
    .A(a[0]),
    .B(b[5]),
    .Y(_188_)
  );
  sky130_fd_sc_hd__nand2_1 _255_ (
    .A(a[2]),
    .B(b[3]),
    .Y(_189_)
  );
  sky130_fd_sc_hd__nand2_1 _256_ (
    .A(a[1]),
    .B(b[4]),
    .Y(_190_)
  );
  sky130_fd_sc_hd__xor3_1 _257_ (
    .A(_188_),
    .B(_189_),
    .C(_190_),
    .X(_191_)
  );
  sky130_fd_sc_hd__xnor3_1 _258_ (
    .A(_183_),
    .B(_187_),
    .C(_191_),
    .X(_192_)
  );
  sky130_fd_sc_hd__xor3_1 _259_ (
    .A(_174_),
    .B(_182_),
    .C(_192_),
    .X(_193_)
  );
  sky130_fd_sc_hd__nand2_1 _260_ (
    .A(_178_),
    .B(_193_),
    .Y(_194_)
  );
  sky130_fd_sc_hd__xnor2_1 _261_ (
    .A(_178_),
    .B(_193_),
    .Y(_195_)
  );
  sky130_fd_sc_hd__nand4b_1 _262_ (
    .A_N(_178_),
    .B(_179_),
    .C(_193_),
    .D(_167_),
    .Y(_196_)
  );
  sky130_fd_sc_hd__xor2_1 _263_ (
    .A(_181_),
    .B(_195_),
    .X(u_wallace_cla_u_cla16_pg_logic5_pg_logic_xor0)
  );
  sky130_fd_sc_hd__maj3_1 _264_ (
    .A(_174_),
    .B(_182_),
    .C(_192_),
    .X(_197_)
  );
  sky130_fd_sc_hd__maj3_1 _265_ (
    .A(_183_),
    .B(_187_),
    .C(_191_),
    .X(_198_)
  );
  sky130_fd_sc_hd__maj3_1 _266_ (
    .A(_184_),
    .B(_185_),
    .C(_186_),
    .X(_199_)
  );
  sky130_fd_sc_hd__nand2_1 _267_ (
    .A(a[4]),
    .B(b[2]),
    .Y(_200_)
  );
  sky130_fd_sc_hd__nand2_1 _268_ (
    .A(b[0]),
    .B(a[6]),
    .Y(_201_)
  );
  sky130_fd_sc_hd__nand2_1 _269_ (
    .A(a[5]),
    .B(b[1]),
    .Y(_202_)
  );
  sky130_fd_sc_hd__xnor3_1 _270_ (
    .A(_200_),
    .B(_201_),
    .C(_202_),
    .X(_203_)
  );
  sky130_fd_sc_hd__nand2_1 _271_ (
    .A(a[1]),
    .B(b[5]),
    .Y(_204_)
  );
  sky130_fd_sc_hd__nand2_1 _272_ (
    .A(a[3]),
    .B(b[3]),
    .Y(_205_)
  );
  sky130_fd_sc_hd__nand2_1 _273_ (
    .A(a[2]),
    .B(b[4]),
    .Y(_206_)
  );
  sky130_fd_sc_hd__xnor3_1 _274_ (
    .A(_204_),
    .B(_205_),
    .C(_206_),
    .X(_207_)
  );
  sky130_fd_sc_hd__xnor3_1 _275_ (
    .A(_199_),
    .B(_203_),
    .C(_207_),
    .X(_208_)
  );
  sky130_fd_sc_hd__maj3_1 _276_ (
    .A(_188_),
    .B(_189_),
    .C(_190_),
    .X(_209_)
  );
  sky130_fd_sc_hd__nand2_1 _277_ (
    .A(a[0]),
    .B(b[6]),
    .Y(_210_)
  );
  sky130_fd_sc_hd__nor2_1 _278_ (
    .A(_209_),
    .B(_210_),
    .Y(_211_)
  );
  sky130_fd_sc_hd__xnor2_1 _279_ (
    .A(_209_),
    .B(_210_),
    .Y(_000_)
  );
  sky130_fd_sc_hd__xnor3_1 _280_ (
    .A(_198_),
    .B(_208_),
    .C(_000_),
    .X(_001_)
  );
  sky130_fd_sc_hd__xnor2_1 _281_ (
    .A(_197_),
    .B(_001_),
    .Y(_002_)
  );
  sky130_fd_sc_hd__xor2_1 _282_ (
    .A(_194_),
    .B(_002_),
    .X(_003_)
  );
  sky130_fd_sc_hd__xnor2_1 _283_ (
    .A(_196_),
    .B(_003_),
    .Y(u_wallace_cla_u_cla16_xor6)
  );
  sky130_fd_sc_hd__maj3_1 _284_ (
    .A(_194_),
    .B(_196_),
    .C(_002_),
    .X(_004_)
  );
  sky130_fd_sc_hd__maj3_1 _285_ (
    .A(_198_),
    .B(_208_),
    .C(_000_),
    .X(_005_)
  );
  sky130_fd_sc_hd__clkinv_1 _286_ (
    .A(_005_),
    .Y(_006_)
  );
  sky130_fd_sc_hd__maj3_1 _287_ (
    .A(_199_),
    .B(_203_),
    .C(_207_),
    .X(_007_)
  );
  sky130_fd_sc_hd__maj3_1 _288_ (
    .A(_200_),
    .B(_201_),
    .C(_202_),
    .X(_008_)
  );
  sky130_fd_sc_hd__clkinv_1 _289_ (
    .A(_008_),
    .Y(_009_)
  );
  sky130_fd_sc_hd__nand2_1 _290_ (
    .A(a[5]),
    .B(b[2]),
    .Y(_010_)
  );
  sky130_fd_sc_hd__nand2_1 _291_ (
    .A(b[0]),
    .B(a[7]),
    .Y(_011_)
  );
  sky130_fd_sc_hd__nand2_1 _292_ (
    .A(a[6]),
    .B(b[1]),
    .Y(_012_)
  );
  sky130_fd_sc_hd__xnor3_1 _293_ (
    .A(_010_),
    .B(_011_),
    .C(_012_),
    .X(_013_)
  );
  sky130_fd_sc_hd__nand2_1 _294_ (
    .A(a[2]),
    .B(b[5]),
    .Y(_014_)
  );
  sky130_fd_sc_hd__nand2_1 _295_ (
    .A(a[4]),
    .B(b[3]),
    .Y(_015_)
  );
  sky130_fd_sc_hd__nand2_1 _296_ (
    .A(a[3]),
    .B(b[4]),
    .Y(_016_)
  );
  sky130_fd_sc_hd__xnor3_1 _297_ (
    .A(_014_),
    .B(_015_),
    .C(_016_),
    .X(_017_)
  );
  sky130_fd_sc_hd__xnor3_1 _298_ (
    .A(_008_),
    .B(_013_),
    .C(_017_),
    .X(_018_)
  );
  sky130_fd_sc_hd__nand2_1 _299_ (
    .A(a[0]),
    .B(b[7]),
    .Y(_019_)
  );
  sky130_fd_sc_hd__maj3_1 _300_ (
    .A(_204_),
    .B(_205_),
    .C(_206_),
    .X(_020_)
  );
  sky130_fd_sc_hd__nand2_1 _301_ (
    .A(a[1]),
    .B(b[6]),
    .Y(_021_)
  );
  sky130_fd_sc_hd__xnor3_1 _302_ (
    .A(_019_),
    .B(_020_),
    .C(_021_),
    .X(_022_)
  );
  sky130_fd_sc_hd__xor3_1 _303_ (
    .A(_007_),
    .B(_018_),
    .C(_022_),
    .X(_023_)
  );
  sky130_fd_sc_hd__xnor3_1 _304_ (
    .A(_211_),
    .B(_005_),
    .C(_023_),
    .X(_024_)
  );
  sky130_fd_sc_hd__nand3_1 _305_ (
    .A(_197_),
    .B(_001_),
    .C(_024_),
    .Y(_025_)
  );
  sky130_fd_sc_hd__a21oi_1 _306_ (
    .A1(_197_),
    .A2(_001_),
    .B1(_024_),
    .Y(_026_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _307_ (
    .A(_025_),
    .SLEEP(_026_),
    .X(_027_)
  );
  sky130_fd_sc_hd__xnor2_1 _308_ (
    .A(_004_),
    .B(_027_),
    .Y(u_wallace_cla_u_cla16_xor7)
  );
  sky130_fd_sc_hd__o21ai_0 _309_ (
    .A1(_004_),
    .A2(_026_),
    .B1(_025_),
    .Y(_028_)
  );
  sky130_fd_sc_hd__maj3_1 _310_ (
    .A(_211_),
    .B(_006_),
    .C(_023_),
    .X(_029_)
  );
  sky130_fd_sc_hd__maj3_1 _311_ (
    .A(_019_),
    .B(_020_),
    .C(_021_),
    .X(_030_)
  );
  sky130_fd_sc_hd__maj3_1 _312_ (
    .A(_007_),
    .B(_018_),
    .C(_022_),
    .X(_031_)
  );
  sky130_fd_sc_hd__maj3_1 _313_ (
    .A(_009_),
    .B(_013_),
    .C(_017_),
    .X(_032_)
  );
  sky130_fd_sc_hd__maj3_1 _314_ (
    .A(_010_),
    .B(_011_),
    .C(_012_),
    .X(_033_)
  );
  sky130_fd_sc_hd__nand4_1 _315_ (
    .A(a[6]),
    .B(a[7]),
    .C(b[1]),
    .D(b[2]),
    .Y(_034_)
  );
  sky130_fd_sc_hd__a22o_1 _316_ (
    .A1(a[7]),
    .A2(b[1]),
    .B1(b[2]),
    .B2(a[6]),
    .X(_035_)
  );
  sky130_fd_sc_hd__nand2_1 _317_ (
    .A(_034_),
    .B(_035_),
    .Y(_036_)
  );
  sky130_fd_sc_hd__xor2_1 _318_ (
    .A(_033_),
    .B(_036_),
    .X(_037_)
  );
  sky130_fd_sc_hd__nand2_1 _319_ (
    .A(a[3]),
    .B(b[5]),
    .Y(_038_)
  );
  sky130_fd_sc_hd__and4_1 _320_ (
    .A(a[4]),
    .B(a[5]),
    .C(b[3]),
    .D(b[4]),
    .X(_039_)
  );
  sky130_fd_sc_hd__a22oi_1 _321_ (
    .A1(a[5]),
    .A2(b[3]),
    .B1(b[4]),
    .B2(a[4]),
    .Y(_040_)
  );
  sky130_fd_sc_hd__nor2_1 _322_ (
    .A(_039_),
    .B(_040_),
    .Y(_041_)
  );
  sky130_fd_sc_hd__xor2_1 _323_ (
    .A(_038_),
    .B(_041_),
    .X(_042_)
  );
  sky130_fd_sc_hd__xnor2_1 _324_ (
    .A(_037_),
    .B(_042_),
    .Y(_043_)
  );
  sky130_fd_sc_hd__xor2_1 _325_ (
    .A(_032_),
    .B(_043_),
    .X(_044_)
  );
  sky130_fd_sc_hd__nand2_1 _326_ (
    .A(a[1]),
    .B(b[7]),
    .Y(_045_)
  );
  sky130_fd_sc_hd__maj3_1 _327_ (
    .A(_014_),
    .B(_015_),
    .C(_016_),
    .X(_046_)
  );
  sky130_fd_sc_hd__nand2_1 _328_ (
    .A(a[2]),
    .B(b[6]),
    .Y(_047_)
  );
  sky130_fd_sc_hd__xor2_1 _329_ (
    .A(_046_),
    .B(_047_),
    .X(_048_)
  );
  sky130_fd_sc_hd__xnor2_1 _330_ (
    .A(_045_),
    .B(_048_),
    .Y(_049_)
  );
  sky130_fd_sc_hd__xor2_1 _331_ (
    .A(_044_),
    .B(_049_),
    .X(_050_)
  );
  sky130_fd_sc_hd__and2_0 _332_ (
    .A(_031_),
    .B(_050_),
    .X(_051_)
  );
  sky130_fd_sc_hd__xnor3_1 _333_ (
    .A(_031_),
    .B(_044_),
    .C(_049_),
    .X(_052_)
  );
  sky130_fd_sc_hd__nor2_1 _334_ (
    .A(_030_),
    .B(_052_),
    .Y(_053_)
  );
  sky130_fd_sc_hd__xor2_1 _335_ (
    .A(_030_),
    .B(_052_),
    .X(_054_)
  );
  sky130_fd_sc_hd__xnor2_1 _336_ (
    .A(_029_),
    .B(_054_),
    .Y(_055_)
  );
  sky130_fd_sc_hd__xnor2_1 _337_ (
    .A(_028_),
    .B(_055_),
    .Y(u_wallace_cla_u_cla16_xor8)
  );
  sky130_fd_sc_hd__maj3_1 _338_ (
    .A(_028_),
    .B(_029_),
    .C(_054_),
    .X(_056_)
  );
  sky130_fd_sc_hd__maj3_1 _339_ (
    .A(_045_),
    .B(_046_),
    .C(_047_),
    .X(_057_)
  );
  sky130_fd_sc_hd__maj3_1 _340_ (
    .A(_032_),
    .B(_043_),
    .C(_049_),
    .X(_058_)
  );
  sky130_fd_sc_hd__maj3_1 _341_ (
    .A(_033_),
    .B(_036_),
    .C(_042_),
    .X(_059_)
  );
  sky130_fd_sc_hd__nand3_1 _342_ (
    .A(a[7]),
    .B(b[2]),
    .C(_034_),
    .Y(_060_)
  );
  sky130_fd_sc_hd__nand2_1 _343_ (
    .A(a[4]),
    .B(b[5]),
    .Y(_061_)
  );
  sky130_fd_sc_hd__and4_1 _344_ (
    .A(a[5]),
    .B(a[6]),
    .C(b[3]),
    .D(b[4]),
    .X(_062_)
  );
  sky130_fd_sc_hd__a22oi_1 _345_ (
    .A1(a[6]),
    .A2(b[3]),
    .B1(b[4]),
    .B2(a[5]),
    .Y(_063_)
  );
  sky130_fd_sc_hd__nor2_1 _346_ (
    .A(_062_),
    .B(_063_),
    .Y(_064_)
  );
  sky130_fd_sc_hd__xnor2_1 _347_ (
    .A(_061_),
    .B(_064_),
    .Y(_065_)
  );
  sky130_fd_sc_hd__nand2b_1 _348_ (
    .A_N(_060_),
    .B(_065_),
    .Y(_066_)
  );
  sky130_fd_sc_hd__xor2_1 _349_ (
    .A(_060_),
    .B(_065_),
    .X(_067_)
  );
  sky130_fd_sc_hd__xor2_1 _350_ (
    .A(_059_),
    .B(_067_),
    .X(_068_)
  );
  sky130_fd_sc_hd__nand2_1 _351_ (
    .A(a[2]),
    .B(b[7]),
    .Y(_069_)
  );
  sky130_fd_sc_hd__a31oi_1 _352_ (
    .A1(a[3]),
    .A2(b[5]),
    .A3(_041_),
    .B1(_039_),
    .Y(_070_)
  );
  sky130_fd_sc_hd__nand2_1 _353_ (
    .A(a[3]),
    .B(b[6]),
    .Y(_071_)
  );
  sky130_fd_sc_hd__xnor2_1 _354_ (
    .A(_070_),
    .B(_071_),
    .Y(_072_)
  );
  sky130_fd_sc_hd__xnor2_1 _355_ (
    .A(_069_),
    .B(_072_),
    .Y(_073_)
  );
  sky130_fd_sc_hd__xnor2_1 _356_ (
    .A(_068_),
    .B(_073_),
    .Y(_074_)
  );
  sky130_fd_sc_hd__xor3_1 _357_ (
    .A(_058_),
    .B(_068_),
    .C(_073_),
    .X(_075_)
  );
  sky130_fd_sc_hd__nor2_1 _358_ (
    .A(_057_),
    .B(_075_),
    .Y(_076_)
  );
  sky130_fd_sc_hd__xor2_1 _359_ (
    .A(_057_),
    .B(_075_),
    .X(_077_)
  );
  sky130_fd_sc_hd__o21a_1 _360_ (
    .A1(_051_),
    .A2(_053_),
    .B1(_077_),
    .X(_078_)
  );
  sky130_fd_sc_hd__or3_1 _361_ (
    .A(_051_),
    .B(_053_),
    .C(_077_),
    .X(_079_)
  );
  sky130_fd_sc_hd__nand2b_1 _362_ (
    .A_N(_078_),
    .B(_079_),
    .Y(_080_)
  );
  sky130_fd_sc_hd__xnor2_1 _363_ (
    .A(_056_),
    .B(_080_),
    .Y(u_wallace_cla_u_cla16_xor9)
  );
  sky130_fd_sc_hd__a21oi_1 _364_ (
    .A1(_056_),
    .A2(_079_),
    .B1(_078_),
    .Y(_081_)
  );
  sky130_fd_sc_hd__a21oi_1 _365_ (
    .A1(_058_),
    .A2(_074_),
    .B1(_076_),
    .Y(_082_)
  );
  sky130_fd_sc_hd__maj3_1 _366_ (
    .A(_069_),
    .B(_070_),
    .C(_071_),
    .X(_083_)
  );
  sky130_fd_sc_hd__maj3_1 _367_ (
    .A(_059_),
    .B(_067_),
    .C(_073_),
    .X(_084_)
  );
  sky130_fd_sc_hd__nand2_1 _368_ (
    .A(_034_),
    .B(_066_),
    .Y(_085_)
  );
  sky130_fd_sc_hd__nand2_1 _369_ (
    .A(a[5]),
    .B(b[5]),
    .Y(_086_)
  );
  sky130_fd_sc_hd__and4_1 _370_ (
    .A(a[6]),
    .B(a[7]),
    .C(b[3]),
    .D(b[4]),
    .X(_087_)
  );
  sky130_fd_sc_hd__a22oi_1 _371_ (
    .A1(a[7]),
    .A2(b[3]),
    .B1(b[4]),
    .B2(a[6]),
    .Y(_088_)
  );
  sky130_fd_sc_hd__nor2_1 _372_ (
    .A(_087_),
    .B(_088_),
    .Y(_089_)
  );
  sky130_fd_sc_hd__xnor2_1 _373_ (
    .A(_086_),
    .B(_089_),
    .Y(_090_)
  );
  sky130_fd_sc_hd__xnor2_1 _374_ (
    .A(_085_),
    .B(_090_),
    .Y(_091_)
  );
  sky130_fd_sc_hd__nand2_1 _375_ (
    .A(a[3]),
    .B(b[7]),
    .Y(_092_)
  );
  sky130_fd_sc_hd__a31oi_1 _376_ (
    .A1(a[4]),
    .A2(b[5]),
    .A3(_064_),
    .B1(_062_),
    .Y(_093_)
  );
  sky130_fd_sc_hd__nand2_1 _377_ (
    .A(a[4]),
    .B(b[6]),
    .Y(_094_)
  );
  sky130_fd_sc_hd__xnor2_1 _378_ (
    .A(_093_),
    .B(_094_),
    .Y(_095_)
  );
  sky130_fd_sc_hd__xnor2_1 _379_ (
    .A(_092_),
    .B(_095_),
    .Y(_096_)
  );
  sky130_fd_sc_hd__nor2_1 _380_ (
    .A(_091_),
    .B(_096_),
    .Y(_097_)
  );
  sky130_fd_sc_hd__xnor2_1 _381_ (
    .A(_091_),
    .B(_096_),
    .Y(_098_)
  );
  sky130_fd_sc_hd__xnor2_1 _382_ (
    .A(_084_),
    .B(_098_),
    .Y(_099_)
  );
  sky130_fd_sc_hd__xnor2_1 _383_ (
    .A(_083_),
    .B(_099_),
    .Y(_100_)
  );
  sky130_fd_sc_hd__xor2_1 _384_ (
    .A(_082_),
    .B(_100_),
    .X(_101_)
  );
  sky130_fd_sc_hd__xnor2_1 _385_ (
    .A(_081_),
    .B(_101_),
    .Y(u_wallace_cla_u_cla16_xor10)
  );
  sky130_fd_sc_hd__maj3_1 _386_ (
    .A(_081_),
    .B(_082_),
    .C(_100_),
    .X(_102_)
  );
  sky130_fd_sc_hd__maj3_1 _387_ (
    .A(_083_),
    .B(_084_),
    .C(_098_),
    .X(_103_)
  );
  sky130_fd_sc_hd__maj3_1 _388_ (
    .A(_092_),
    .B(_093_),
    .C(_094_),
    .X(_104_)
  );
  sky130_fd_sc_hd__a21oi_1 _389_ (
    .A1(_085_),
    .A2(_090_),
    .B1(_097_),
    .Y(_105_)
  );
  sky130_fd_sc_hd__and4_1 _390_ (
    .A(a[6]),
    .B(a[7]),
    .C(b[4]),
    .D(b[5]),
    .X(_106_)
  );
  sky130_fd_sc_hd__a22oi_1 _391_ (
    .A1(a[7]),
    .A2(b[4]),
    .B1(b[5]),
    .B2(a[6]),
    .Y(_107_)
  );
  sky130_fd_sc_hd__nand2_1 _392_ (
    .A(a[4]),
    .B(b[7]),
    .Y(_108_)
  );
  sky130_fd_sc_hd__a31oi_1 _393_ (
    .A1(a[5]),
    .A2(b[5]),
    .A3(_089_),
    .B1(_087_),
    .Y(_109_)
  );
  sky130_fd_sc_hd__nand2_1 _394_ (
    .A(a[5]),
    .B(b[6]),
    .Y(_110_)
  );
  sky130_fd_sc_hd__xnor2_1 _395_ (
    .A(_109_),
    .B(_110_),
    .Y(_111_)
  );
  sky130_fd_sc_hd__xnor2_1 _396_ (
    .A(_108_),
    .B(_111_),
    .Y(_112_)
  );
  sky130_fd_sc_hd__or3_1 _397_ (
    .A(_106_),
    .B(_107_),
    .C(_112_),
    .X(_113_)
  );
  sky130_fd_sc_hd__o21ai_0 _398_ (
    .A1(_106_),
    .A2(_107_),
    .B1(_112_),
    .Y(_114_)
  );
  sky130_fd_sc_hd__nand2_1 _399_ (
    .A(_113_),
    .B(_114_),
    .Y(_115_)
  );
  sky130_fd_sc_hd__xnor2_1 _400_ (
    .A(_105_),
    .B(_115_),
    .Y(_116_)
  );
  sky130_fd_sc_hd__xnor2_1 _401_ (
    .A(_104_),
    .B(_116_),
    .Y(_117_)
  );
  sky130_fd_sc_hd__xor2_1 _402_ (
    .A(_103_),
    .B(_117_),
    .X(_118_)
  );
  sky130_fd_sc_hd__xnor2_1 _403_ (
    .A(_102_),
    .B(_118_),
    .Y(u_wallace_cla_u_cla16_xor11)
  );
  sky130_fd_sc_hd__maj3_1 _404_ (
    .A(_102_),
    .B(_103_),
    .C(_117_),
    .X(_119_)
  );
  sky130_fd_sc_hd__maj3_1 _405_ (
    .A(_104_),
    .B(_105_),
    .C(_115_),
    .X(_120_)
  );
  sky130_fd_sc_hd__maj3_1 _406_ (
    .A(_108_),
    .B(_109_),
    .C(_110_),
    .X(_121_)
  );
  sky130_fd_sc_hd__nand3_1 _407_ (
    .A(a[6]),
    .B(b[6]),
    .C(_106_),
    .Y(_122_)
  );
  sky130_fd_sc_hd__a21oi_1 _408_ (
    .A1(a[6]),
    .A2(b[6]),
    .B1(_106_),
    .Y(_123_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _409_ (
    .A(_122_),
    .SLEEP(_123_),
    .X(_124_)
  );
  sky130_fd_sc_hd__nand3_1 _410_ (
    .A(a[5]),
    .B(b[7]),
    .C(_124_),
    .Y(_125_)
  );
  sky130_fd_sc_hd__a21oi_1 _411_ (
    .A1(a[5]),
    .A2(b[7]),
    .B1(_124_),
    .Y(_126_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _412_ (
    .A(_125_),
    .SLEEP(_126_),
    .X(_127_)
  );
  sky130_fd_sc_hd__nand3_1 _413_ (
    .A(a[7]),
    .B(b[5]),
    .C(_127_),
    .Y(_128_)
  );
  sky130_fd_sc_hd__a21oi_1 _414_ (
    .A1(a[7]),
    .A2(b[5]),
    .B1(_127_),
    .Y(_129_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _415_ (
    .A(_128_),
    .SLEEP(_129_),
    .X(_130_)
  );
  sky130_fd_sc_hd__clkinv_1 _416_ (
    .A(_130_),
    .Y(_131_)
  );
  sky130_fd_sc_hd__xnor2_1 _417_ (
    .A(_113_),
    .B(_131_),
    .Y(_132_)
  );
  sky130_fd_sc_hd__xnor2_1 _418_ (
    .A(_121_),
    .B(_132_),
    .Y(_133_)
  );
  sky130_fd_sc_hd__xnor2_1 _419_ (
    .A(_120_),
    .B(_133_),
    .Y(_134_)
  );
  sky130_fd_sc_hd__xor2_1 _420_ (
    .A(_119_),
    .B(_134_),
    .X(u_wallace_cla_u_cla16_xor12)
  );
  sky130_fd_sc_hd__maj3_1 _421_ (
    .A(_119_),
    .B(_120_),
    .C(_133_),
    .X(_135_)
  );
  sky130_fd_sc_hd__maj3_1 _422_ (
    .A(_113_),
    .B(_121_),
    .C(_131_),
    .X(_136_)
  );
  sky130_fd_sc_hd__and2_0 _423_ (
    .A(_122_),
    .B(_125_),
    .X(_137_)
  );
  sky130_fd_sc_hd__nand4_1 _424_ (
    .A(a[6]),
    .B(a[7]),
    .C(b[6]),
    .D(b[7]),
    .Y(_138_)
  );
  sky130_fd_sc_hd__a22o_1 _425_ (
    .A1(a[7]),
    .A2(b[6]),
    .B1(b[7]),
    .B2(a[6]),
    .X(_139_)
  );
  sky130_fd_sc_hd__nand2_1 _426_ (
    .A(_138_),
    .B(_139_),
    .Y(_140_)
  );
  sky130_fd_sc_hd__xnor2_1 _427_ (
    .A(_128_),
    .B(_140_),
    .Y(_141_)
  );
  sky130_fd_sc_hd__xnor2_1 _428_ (
    .A(_137_),
    .B(_141_),
    .Y(_142_)
  );
  sky130_fd_sc_hd__xnor2_1 _429_ (
    .A(_136_),
    .B(_142_),
    .Y(_143_)
  );
  sky130_fd_sc_hd__xor2_1 _430_ (
    .A(_135_),
    .B(_143_),
    .X(u_wallace_cla_u_cla16_xor13)
  );
  sky130_fd_sc_hd__maj3_1 _431_ (
    .A(_135_),
    .B(_136_),
    .C(_142_),
    .X(_144_)
  );
  sky130_fd_sc_hd__nand2_1 _432_ (
    .A(a[7]),
    .B(b[7]),
    .Y(_145_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _433_ (
    .A(_138_),
    .SLEEP(_145_),
    .X(_146_)
  );
  sky130_fd_sc_hd__maj3_1 _434_ (
    .A(_128_),
    .B(_137_),
    .C(_140_),
    .X(_147_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _435_ (
    .A(_147_),
    .SLEEP(_146_),
    .X(_148_)
  );
  sky130_fd_sc_hd__xnor2_1 _436_ (
    .A(_146_),
    .B(_147_),
    .Y(_149_)
  );
  sky130_fd_sc_hd__xnor2_1 _437_ (
    .A(_144_),
    .B(_149_),
    .Y(u_wallace_cla_u_cla16_xor14)
  );
  sky130_fd_sc_hd__o21a_1 _438_ (
    .A1(_145_),
    .A2(_147_),
    .B1(_138_),
    .X(_150_)
  );
  sky130_fd_sc_hd__o21ai_0 _439_ (
    .A1(_144_),
    .A2(_148_),
    .B1(_150_),
    .Y(u_wallace_cla_u_cla16_xor15)
  );
  assign u_wallace_cla_out = { u_wallace_cla_u_cla16_xor15, u_wallace_cla_u_cla16_xor14, u_wallace_cla_u_cla16_xor13, u_wallace_cla_u_cla16_xor12, u_wallace_cla_u_cla16_xor11, u_wallace_cla_u_cla16_xor10, u_wallace_cla_u_cla16_xor9, u_wallace_cla_u_cla16_xor8, u_wallace_cla_u_cla16_xor7, u_wallace_cla_u_cla16_xor6, u_wallace_cla_u_cla16_pg_logic5_pg_logic_xor0, u_wallace_cla_csa5_csa_component_fa4_fa_xor0, u_wallace_cla_csa4_csa_component_fa3_fa_xor0, u_wallace_cla_csa2_csa_component_fa2_fa_xor0, u_wallace_cla_csa0_csa_component_fa1_fa_xor0, u_wallace_cla_and_0_0 };
endmodule
