/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_3.v:1.1-54.10" *)
module alu_8bit(rs, rt, op, alu_out);
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_3.v:9.12-9.19" *)
  (* unused_bits = "0 1 2 3 4 5 6 7" *)
  wire [7:0] add_out;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_3.v:5.23-5.30" *)
  output [7:0] alu_out;
  wire [7:0] alu_out;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_3.v:11.12-11.19" *)
  (* unused_bits = "0 1 2 3 4 5 6 7" *)
  wire [7:0] mul_out;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_3.v:21.12-21.20" *)
  (* unused_bits = "0 1 2 3 4 5 6 7" *)
  wire [7:0] mux1_out;
  (* hdlname = "mux_layer1[0].mux_add_sub sel" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_3.v:27.17-32.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:2.16-2.19" *)
  (* unused_bits = "0" *)
  wire \mux_layer1[0].mux_add_sub.sel ;
  (* hdlname = "mux_layer1[0].mux_mul_div sel" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_3.v:33.17-38.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:2.16-2.19" *)
  (* unused_bits = "0" *)
  wire \mux_layer1[0].mux_mul_div.sel ;
  (* hdlname = "mux_layer1[1].mux_add_sub sel" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_3.v:27.17-32.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:2.16-2.19" *)
  (* unused_bits = "0" *)
  wire \mux_layer1[1].mux_add_sub.sel ;
  (* hdlname = "mux_layer1[1].mux_mul_div sel" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_3.v:33.17-38.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:2.16-2.19" *)
  (* unused_bits = "0" *)
  wire \mux_layer1[1].mux_mul_div.sel ;
  (* hdlname = "mux_layer1[2].mux_add_sub in0" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_3.v:27.17-32.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:3.16-3.19" *)
  (* unused_bits = "0" *)
  wire \mux_layer1[2].mux_add_sub.in0 ;
  (* hdlname = "mux_layer1[2].mux_add_sub out" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_3.v:27.17-32.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:5.17-5.20" *)
  (* unused_bits = "0" *)
  wire \mux_layer1[2].mux_add_sub.out ;
  (* hdlname = "mux_layer1[2].mux_add_sub sel" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_3.v:27.17-32.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:2.16-2.19" *)
  (* unused_bits = "0" *)
  wire \mux_layer1[2].mux_add_sub.sel ;
  (* hdlname = "mux_layer1[2].mux_mul_div sel" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_3.v:33.17-38.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:2.16-2.19" *)
  (* unused_bits = "0" *)
  wire \mux_layer1[2].mux_mul_div.sel ;
  (* hdlname = "mux_layer1[3].mux_add_sub in0" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_3.v:27.17-32.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:3.16-3.19" *)
  (* unused_bits = "0" *)
  wire \mux_layer1[3].mux_add_sub.in0 ;
  (* hdlname = "mux_layer1[3].mux_add_sub out" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_3.v:27.17-32.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:5.17-5.20" *)
  (* unused_bits = "0" *)
  wire \mux_layer1[3].mux_add_sub.out ;
  (* hdlname = "mux_layer1[3].mux_add_sub sel" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_3.v:27.17-32.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:2.16-2.19" *)
  (* unused_bits = "0" *)
  wire \mux_layer1[3].mux_add_sub.sel ;
  (* hdlname = "mux_layer1[3].mux_mul_div in0" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_3.v:33.17-38.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:3.16-3.19" *)
  (* unused_bits = "0" *)
  wire \mux_layer1[3].mux_mul_div.in0 ;
  (* hdlname = "mux_layer1[3].mux_mul_div sel" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_3.v:33.17-38.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:2.16-2.19" *)
  (* unused_bits = "0" *)
  wire \mux_layer1[3].mux_mul_div.sel ;
  (* hdlname = "mux_layer1[4].mux_add_sub sel" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_3.v:27.17-32.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:2.16-2.19" *)
  (* unused_bits = "0" *)
  wire \mux_layer1[4].mux_add_sub.sel ;
  (* hdlname = "mux_layer1[4].mux_mul_div sel" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_3.v:33.17-38.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:2.16-2.19" *)
  (* unused_bits = "0" *)
  wire \mux_layer1[4].mux_mul_div.sel ;
  (* hdlname = "mux_layer1[5].mux_add_sub sel" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_3.v:27.17-32.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:2.16-2.19" *)
  (* unused_bits = "0" *)
  wire \mux_layer1[5].mux_add_sub.sel ;
  (* hdlname = "mux_layer1[5].mux_mul_div sel" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_3.v:33.17-38.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:2.16-2.19" *)
  (* unused_bits = "0" *)
  wire \mux_layer1[5].mux_mul_div.sel ;
  (* hdlname = "mux_layer1[6].mux_add_sub sel" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_3.v:27.17-32.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:2.16-2.19" *)
  (* unused_bits = "0" *)
  wire \mux_layer1[6].mux_add_sub.sel ;
  (* hdlname = "mux_layer1[6].mux_mul_div sel" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_3.v:33.17-38.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:2.16-2.19" *)
  (* unused_bits = "0" *)
  wire \mux_layer1[6].mux_mul_div.sel ;
  (* hdlname = "mux_layer1[7].mux_add_sub sel" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_3.v:27.17-32.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:2.16-2.19" *)
  (* unused_bits = "0" *)
  wire \mux_layer1[7].mux_add_sub.sel ;
  (* hdlname = "mux_layer1[7].mux_mul_div sel" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_3.v:33.17-38.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:2.16-2.19" *)
  (* unused_bits = "0" *)
  wire \mux_layer1[7].mux_mul_div.sel ;
  (* hdlname = "mux_layer2[0].mux_final out" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_3.v:45.17-50.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:5.17-5.20" *)
  wire \mux_layer2[0].mux_final.out ;
  (* hdlname = "mux_layer2[0].mux_final sel" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_3.v:45.17-50.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:2.16-2.19" *)
  (* unused_bits = "0" *)
  wire \mux_layer2[0].mux_final.sel ;
  (* hdlname = "mux_layer2[1].mux_final out" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_3.v:45.17-50.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:5.17-5.20" *)
  wire \mux_layer2[1].mux_final.out ;
  (* hdlname = "mux_layer2[1].mux_final sel" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_3.v:45.17-50.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:2.16-2.19" *)
  (* unused_bits = "0" *)
  wire \mux_layer2[1].mux_final.sel ;
  (* hdlname = "mux_layer2[2].mux_final in0" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_3.v:45.17-50.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:3.16-3.19" *)
  (* unused_bits = "0" *)
  wire \mux_layer2[2].mux_final.in0 ;
  (* hdlname = "mux_layer2[2].mux_final out" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_3.v:45.17-50.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:5.17-5.20" *)
  wire \mux_layer2[2].mux_final.out ;
  (* hdlname = "mux_layer2[2].mux_final sel" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_3.v:45.17-50.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:2.16-2.19" *)
  (* unused_bits = "0" *)
  wire \mux_layer2[2].mux_final.sel ;
  (* hdlname = "mux_layer2[3].mux_final in0" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_3.v:45.17-50.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:3.16-3.19" *)
  (* unused_bits = "0" *)
  wire \mux_layer2[3].mux_final.in0 ;
  (* hdlname = "mux_layer2[3].mux_final out" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_3.v:45.17-50.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:5.17-5.20" *)
  wire \mux_layer2[3].mux_final.out ;
  (* hdlname = "mux_layer2[3].mux_final sel" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_3.v:45.17-50.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:2.16-2.19" *)
  (* unused_bits = "0" *)
  wire \mux_layer2[3].mux_final.sel ;
  (* hdlname = "mux_layer2[4].mux_final out" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_3.v:45.17-50.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:5.17-5.20" *)
  wire \mux_layer2[4].mux_final.out ;
  (* hdlname = "mux_layer2[4].mux_final sel" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_3.v:45.17-50.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:2.16-2.19" *)
  (* unused_bits = "0" *)
  wire \mux_layer2[4].mux_final.sel ;
  (* hdlname = "mux_layer2[5].mux_final out" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_3.v:45.17-50.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:5.17-5.20" *)
  wire \mux_layer2[5].mux_final.out ;
  (* hdlname = "mux_layer2[5].mux_final sel" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_3.v:45.17-50.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:2.16-2.19" *)
  (* unused_bits = "0" *)
  wire \mux_layer2[5].mux_final.sel ;
  (* hdlname = "mux_layer2[6].mux_final out" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_3.v:45.17-50.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:5.17-5.20" *)
  wire \mux_layer2[6].mux_final.out ;
  (* hdlname = "mux_layer2[6].mux_final sel" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_3.v:45.17-50.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:2.16-2.19" *)
  (* unused_bits = "0" *)
  wire \mux_layer2[6].mux_final.sel ;
  (* hdlname = "mux_layer2[7].mux_final out" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_3.v:45.17-50.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:5.17-5.20" *)
  wire \mux_layer2[7].mux_final.out ;
  (* hdlname = "mux_layer2[7].mux_final sel" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_3.v:45.17-50.10|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:2.16-2.19" *)
  (* unused_bits = "0" *)
  wire \mux_layer2[7].mux_final.sel ;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_3.v:4.22-4.24" *)
  input [1:0] op;
  wire [1:0] op;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_3.v:2.22-2.24" *)
  input [7:0] rs;
  wire [7:0] rs;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_3.v:3.22-3.24" *)
  input [7:0] rt;
  wire [7:0] rt;
  (* hdlname = "u_adder a" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_3.v:15.8-15.46|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/csa8.v:1.27-1.28" *)
  (* unused_bits = "0 1 2 3 4 5 6 7" *)
  wire [7:0] \u_adder.a ;
  (* hdlname = "u_adder b" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_3.v:15.8-15.46|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/csa8.v:1.42-1.43" *)
  (* unused_bits = "0 1 2 3 4 5 6 7" *)
  wire [7:0] \u_adder.b ;
  (* hdlname = "u_div a" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_3.v:18.8-18.49|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:1.27-1.28" *)
  (* unused_bits = "0 1 2 3 4 5 6 7" *)
  wire [7:0] \u_div.a ;
  (* hdlname = "u_div b" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_3.v:18.8-18.49|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:1.42-1.43" *)
  (* unused_bits = "0 1 2 3 4 5 6 7" *)
  wire [7:0] \u_div.b ;
  (* hdlname = "u_mul a" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_3.v:17.10-17.47|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/cmu16.v:1.29-1.30" *)
  (* unused_bits = "0 1 2 3 4 5 6 7" *)
  wire [7:0] \u_mul.a ;
  (* hdlname = "u_mul b" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_3.v:17.10-17.47|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/cmu16.v:1.44-1.45" *)
  (* unused_bits = "0 1 2 3 4 5 6 7" *)
  wire [7:0] \u_mul.b ;
  (* hdlname = "u_sub a" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_3.v:16.7-16.44|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/rcs8.v:1.26-1.27" *)
  (* unused_bits = "0 1 2 3 4 5 6 7" *)
  wire [7:0] \u_sub.a ;
  (* hdlname = "u_sub b" *)
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/ALU_3.v:16.7-16.44|/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/rcs8.v:1.41-1.42" *)
  (* unused_bits = "0 1 2 3 4 5 6 7" *)
  wire [7:0] \u_sub.b ;
  assign add_out[3:2] = { \mux_layer1[3].mux_add_sub.in0 , \mux_layer1[2].mux_add_sub.in0  };
  assign alu_out = 8'h00;
  assign mul_out[3] = \mux_layer1[3].mux_mul_div.in0 ;
  assign mux1_out[3:2] = { \mux_layer1[3].mux_add_sub.out , \mux_layer1[2].mux_add_sub.out  };
  assign \mux_layer1[0].mux_add_sub.sel  = op[0];
  assign \mux_layer1[0].mux_mul_div.sel  = op[0];
  assign \mux_layer1[1].mux_add_sub.sel  = op[0];
  assign \mux_layer1[1].mux_mul_div.sel  = op[0];
  assign \mux_layer1[2].mux_add_sub.sel  = op[0];
  assign \mux_layer1[2].mux_mul_div.sel  = op[0];
  assign \mux_layer1[3].mux_add_sub.sel  = op[0];
  assign \mux_layer1[3].mux_mul_div.sel  = op[0];
  assign \mux_layer1[4].mux_add_sub.sel  = op[0];
  assign \mux_layer1[4].mux_mul_div.sel  = op[0];
  assign \mux_layer1[5].mux_add_sub.sel  = op[0];
  assign \mux_layer1[5].mux_mul_div.sel  = op[0];
  assign \mux_layer1[6].mux_add_sub.sel  = op[0];
  assign \mux_layer1[6].mux_mul_div.sel  = op[0];
  assign \mux_layer1[7].mux_add_sub.sel  = op[0];
  assign \mux_layer1[7].mux_mul_div.sel  = op[0];
  assign \mux_layer2[0].mux_final.out  = 1'h0;
  assign \mux_layer2[0].mux_final.sel  = op[1];
  assign \mux_layer2[1].mux_final.out  = 1'h0;
  assign \mux_layer2[1].mux_final.sel  = op[1];
  assign \mux_layer2[2].mux_final.in0  = \mux_layer1[2].mux_add_sub.out ;
  assign \mux_layer2[2].mux_final.out  = 1'h0;
  assign \mux_layer2[2].mux_final.sel  = op[1];
  assign \mux_layer2[3].mux_final.in0  = \mux_layer1[3].mux_add_sub.out ;
  assign \mux_layer2[3].mux_final.out  = 1'h0;
  assign \mux_layer2[3].mux_final.sel  = op[1];
  assign \mux_layer2[4].mux_final.out  = 1'h0;
  assign \mux_layer2[4].mux_final.sel  = op[1];
  assign \mux_layer2[5].mux_final.out  = 1'h0;
  assign \mux_layer2[5].mux_final.sel  = op[1];
  assign \mux_layer2[6].mux_final.out  = 1'h0;
  assign \mux_layer2[6].mux_final.sel  = op[1];
  assign \mux_layer2[7].mux_final.out  = 1'h0;
  assign \mux_layer2[7].mux_final.sel  = op[1];
  assign \u_adder.a  = rs;
  assign \u_adder.b  = rt;
  assign \u_div.a  = rs;
  assign \u_div.b  = rt;
  assign \u_mul.a  = rs;
  assign \u_mul.b  = rt;
  assign \u_sub.a  = rs;
  assign \u_sub.b  = rt;
endmodule

(* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:1.1-1202.10" *)
module arrdiv(a, b, arrdiv_out);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:1.27-1.28" *)
  input [7:0] a;
  wire [7:0] a;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:35.8-35.36" *)
  wire arrdiv_mux2to10_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:117.8-117.37" *)
  wire arrdiv_mux2to110_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:121.8-121.37" *)
  wire arrdiv_mux2to111_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:125.8-125.37" *)
  wire arrdiv_mux2to112_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:129.8-129.37" *)
  wire arrdiv_mux2to113_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:187.8-187.37" *)
  wire arrdiv_mux2to114_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:191.8-191.37" *)
  wire arrdiv_mux2to115_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:195.8-195.37" *)
  wire arrdiv_mux2to116_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:199.8-199.37" *)
  wire arrdiv_mux2to117_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:203.8-203.37" *)
  wire arrdiv_mux2to118_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:207.8-207.37" *)
  wire arrdiv_mux2to119_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:38.8-38.36" *)
  wire arrdiv_mux2to11_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:211.8-211.37" *)
  wire arrdiv_mux2to120_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:269.8-269.37" *)
  wire arrdiv_mux2to121_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:273.8-273.37" *)
  wire arrdiv_mux2to122_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:277.8-277.37" *)
  wire arrdiv_mux2to123_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:281.8-281.37" *)
  wire arrdiv_mux2to124_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:285.8-285.37" *)
  wire arrdiv_mux2to125_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:289.8-289.37" *)
  wire arrdiv_mux2to126_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:293.8-293.37" *)
  wire arrdiv_mux2to127_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:351.8-351.37" *)
  wire arrdiv_mux2to128_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:355.8-355.37" *)
  wire arrdiv_mux2to129_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:40.8-40.36" *)
  wire arrdiv_mux2to12_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:359.8-359.37" *)
  wire arrdiv_mux2to130_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:363.8-363.37" *)
  wire arrdiv_mux2to131_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:367.8-367.37" *)
  wire arrdiv_mux2to132_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:371.8-371.37" *)
  wire arrdiv_mux2to133_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:375.8-375.37" *)
  wire arrdiv_mux2to134_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:433.8-433.37" *)
  wire arrdiv_mux2to135_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:437.8-437.37" *)
  wire arrdiv_mux2to136_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:441.8-441.37" *)
  wire arrdiv_mux2to137_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:445.8-445.37" *)
  wire arrdiv_mux2to138_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:449.8-449.37" *)
  wire arrdiv_mux2to139_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:42.8-42.36" *)
  wire arrdiv_mux2to13_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:453.8-453.37" *)
  wire arrdiv_mux2to140_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:457.8-457.37" *)
  wire arrdiv_mux2to141_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:515.8-515.37" *)
  wire arrdiv_mux2to142_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:519.8-519.37" *)
  wire arrdiv_mux2to143_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:523.8-523.37" *)
  wire arrdiv_mux2to144_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:527.8-527.37" *)
  wire arrdiv_mux2to145_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:531.8-531.37" *)
  wire arrdiv_mux2to146_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:535.8-535.37" *)
  wire arrdiv_mux2to147_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:539.8-539.37" *)
  wire arrdiv_mux2to148_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:44.8-44.36" *)
  wire arrdiv_mux2to14_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:46.8-46.36" *)
  wire arrdiv_mux2to15_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:48.8-48.36" *)
  wire arrdiv_mux2to16_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:105.8-105.36" *)
  wire arrdiv_mux2to17_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:109.8-109.36" *)
  wire arrdiv_mux2to18_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:113.8-113.36" *)
  wire arrdiv_mux2to19_mux2to1_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:50.8-50.19" *)
  wire arrdiv_not0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:132.8-132.19" *)
  wire arrdiv_not1;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:214.8-214.19" *)
  wire arrdiv_not2;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:296.8-296.19" *)
  wire arrdiv_not3;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:378.8-378.19" *)
  wire arrdiv_not4;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:460.8-460.19" *)
  wire arrdiv_not5;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:542.8-542.19" *)
  wire arrdiv_not6;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:596.8-596.19" *)
  wire arrdiv_not7;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:1.58-1.68" *)
  output [7:0] arrdiv_out;
  wire [7:0] arrdiv_out;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/div8.v:1.42-1.43" *)
  input [7:0] b;
  wire [7:0] b;
  sky130_fd_sc_hd__clkinv_1 _136_ (
    .A(b[1]),
    .Y(_066_)
  );
  sky130_fd_sc_hd__clkinv_1 _137_ (
    .A(b[3]),
    .Y(_067_)
  );
  sky130_fd_sc_hd__clkinv_1 _138_ (
    .A(b[7]),
    .Y(_068_)
  );
  sky130_fd_sc_hd__clkinv_1 _139_ (
    .A(b[0]),
    .Y(_069_)
  );
  sky130_fd_sc_hd__nor2_1 _140_ (
    .A(b[6]),
    .B(b[7]),
    .Y(_070_)
  );
  sky130_fd_sc_hd__nor3_1 _141_ (
    .A(b[5]),
    .B(b[6]),
    .C(b[7]),
    .Y(_071_)
  );
  sky130_fd_sc_hd__or4_1 _142_ (
    .A(b[4]),
    .B(b[5]),
    .C(b[6]),
    .D(b[7]),
    .X(_072_)
  );
  sky130_fd_sc_hd__or3_1 _143_ (
    .A(b[2]),
    .B(b[3]),
    .C(_072_),
    .X(_073_)
  );
  sky130_fd_sc_hd__nor4_1 _144_ (
    .A(b[1]),
    .B(b[2]),
    .C(b[3]),
    .D(_072_),
    .Y(_074_)
  );
  sky130_fd_sc_hd__o21a_1 _145_ (
    .A1(a[7]),
    .A2(_069_),
    .B1(_074_),
    .X(arrdiv_mux2to10_mux2to1_not0)
  );
  sky130_fd_sc_hd__nor2_1 _146_ (
    .A(a[6]),
    .B(_069_),
    .Y(_075_)
  );
  sky130_fd_sc_hd__nor2_1 _147_ (
    .A(b[1]),
    .B(_075_),
    .Y(_076_)
  );
  sky130_fd_sc_hd__and3_1 _148_ (
    .A(a[7]),
    .B(_069_),
    .C(_074_),
    .X(_077_)
  );
  sky130_fd_sc_hd__a21boi_0 _149_ (
    .A1(b[0]),
    .A2(_074_),
    .B1_N(a[7]),
    .Y(_078_)
  );
  sky130_fd_sc_hd__nor2_1 _150_ (
    .A(_076_),
    .B(_078_),
    .Y(_079_)
  );
  sky130_fd_sc_hd__a21o_1 _151_ (
    .A1(b[1]),
    .A2(_075_),
    .B1(_073_),
    .X(_080_)
  );
  sky130_fd_sc_hd__nor2_1 _152_ (
    .A(_079_),
    .B(_080_),
    .Y(arrdiv_mux2to110_mux2to1_not0)
  );
  sky130_fd_sc_hd__a21oi_1 _153_ (
    .A1(_078_),
    .A2(_080_),
    .B1(_077_),
    .Y(_081_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _154_ (
    .A(b[2]),
    .SLEEP(_081_),
    .X(_082_)
  );
  sky130_fd_sc_hd__o31ai_1 _155_ (
    .A1(_069_),
    .A2(_073_),
    .A3(_079_),
    .B1(a[6]),
    .Y(_083_)
  );
  sky130_fd_sc_hd__xnor2_1 _156_ (
    .A(b[1]),
    .B(_083_),
    .Y(_084_)
  );
  sky130_fd_sc_hd__nor2_1 _157_ (
    .A(a[5]),
    .B(_069_),
    .Y(_085_)
  );
  sky130_fd_sc_hd__maj3_1 _158_ (
    .A(b[1]),
    .B(_083_),
    .C(_085_),
    .X(_086_)
  );
  sky130_fd_sc_hd__a211o_1 _159_ (
    .A1(b[2]),
    .A2(_081_),
    .B1(_072_),
    .C1(b[3]),
    .X(_087_)
  );
  sky130_fd_sc_hd__a21oi_1 _160_ (
    .A1(_082_),
    .A2(_086_),
    .B1(_087_),
    .Y(arrdiv_mux2to114_mux2to1_not0)
  );
  sky130_fd_sc_hd__o21bai_1 _161_ (
    .A1(_081_),
    .A2(arrdiv_mux2to114_mux2to1_not0),
    .B1_N(_077_),
    .Y(_088_)
  );
  sky130_fd_sc_hd__nand2_1 _162_ (
    .A(_067_),
    .B(_088_),
    .Y(_089_)
  );
  sky130_fd_sc_hd__xnor2_1 _163_ (
    .A(_084_),
    .B(_085_),
    .Y(_090_)
  );
  sky130_fd_sc_hd__mux2i_1 _164_ (
    .A0(_083_),
    .A1(_090_),
    .S(arrdiv_mux2to114_mux2to1_not0),
    .Y(_091_)
  );
  sky130_fd_sc_hd__clkinv_1 _165_ (
    .A(_091_),
    .Y(_092_)
  );
  sky130_fd_sc_hd__xnor2_1 _166_ (
    .A(b[2]),
    .B(_091_),
    .Y(_093_)
  );
  sky130_fd_sc_hd__a211oi_1 _167_ (
    .A1(_082_),
    .A2(_086_),
    .B1(_087_),
    .C1(_069_),
    .Y(_094_)
  );
  sky130_fd_sc_hd__xnor2_1 _168_ (
    .A(a[5]),
    .B(_094_),
    .Y(_095_)
  );
  sky130_fd_sc_hd__xnor2_1 _169_ (
    .A(b[1]),
    .B(_095_),
    .Y(_096_)
  );
  sky130_fd_sc_hd__nor2_1 _170_ (
    .A(a[4]),
    .B(_069_),
    .Y(_097_)
  );
  sky130_fd_sc_hd__maj3_1 _171_ (
    .A(b[1]),
    .B(_095_),
    .C(_097_),
    .X(_098_)
  );
  sky130_fd_sc_hd__maj3_1 _172_ (
    .A(b[2]),
    .B(_092_),
    .C(_098_),
    .X(_099_)
  );
  sky130_fd_sc_hd__o21bai_1 _173_ (
    .A1(_067_),
    .A2(_088_),
    .B1_N(_072_),
    .Y(_100_)
  );
  sky130_fd_sc_hd__a21o_1 _174_ (
    .A1(_089_),
    .A2(_099_),
    .B1(_100_),
    .X(_101_)
  );
  sky130_fd_sc_hd__clkinv_1 _175_ (
    .A(_101_),
    .Y(arrdiv_mux2to121_mux2to1_not0)
  );
  sky130_fd_sc_hd__a21oi_1 _176_ (
    .A1(_088_),
    .A2(_101_),
    .B1(_077_),
    .Y(_102_)
  );
  sky130_fd_sc_hd__nor2_1 _177_ (
    .A(b[4]),
    .B(_102_),
    .Y(_103_)
  );
  sky130_fd_sc_hd__xnor2_1 _178_ (
    .A(_093_),
    .B(_098_),
    .Y(_104_)
  );
  sky130_fd_sc_hd__mux2i_1 _179_ (
    .A0(_091_),
    .A1(_104_),
    .S(arrdiv_mux2to121_mux2to1_not0),
    .Y(_105_)
  );
  sky130_fd_sc_hd__xnor2_1 _180_ (
    .A(b[3]),
    .B(_105_),
    .Y(_106_)
  );
  sky130_fd_sc_hd__clkinv_1 _181_ (
    .A(_106_),
    .Y(_107_)
  );
  sky130_fd_sc_hd__xnor2_1 _182_ (
    .A(_096_),
    .B(_097_),
    .Y(_108_)
  );
  sky130_fd_sc_hd__mux2i_1 _183_ (
    .A0(_095_),
    .A1(_108_),
    .S(arrdiv_mux2to121_mux2to1_not0),
    .Y(_109_)
  );
  sky130_fd_sc_hd__clkinv_1 _184_ (
    .A(_109_),
    .Y(_110_)
  );
  sky130_fd_sc_hd__xnor2_1 _185_ (
    .A(b[2]),
    .B(_109_),
    .Y(_111_)
  );
  sky130_fd_sc_hd__a211oi_1 _186_ (
    .A1(_089_),
    .A2(_099_),
    .B1(_100_),
    .C1(_069_),
    .Y(_112_)
  );
  sky130_fd_sc_hd__xnor2_1 _187_ (
    .A(a[4]),
    .B(_112_),
    .Y(_113_)
  );
  sky130_fd_sc_hd__xnor2_1 _188_ (
    .A(b[1]),
    .B(_113_),
    .Y(_114_)
  );
  sky130_fd_sc_hd__nor2_1 _189_ (
    .A(a[3]),
    .B(_069_),
    .Y(_115_)
  );
  sky130_fd_sc_hd__maj3_1 _190_ (
    .A(b[1]),
    .B(_113_),
    .C(_115_),
    .X(_116_)
  );
  sky130_fd_sc_hd__maj3_1 _191_ (
    .A(b[2]),
    .B(_110_),
    .C(_116_),
    .X(_117_)
  );
  sky130_fd_sc_hd__a22o_1 _192_ (
    .A1(b[4]),
    .A2(_102_),
    .B1(_105_),
    .B2(b[3]),
    .X(_118_)
  );
  sky130_fd_sc_hd__a21oi_1 _193_ (
    .A1(_107_),
    .A2(_117_),
    .B1(_118_),
    .Y(_119_)
  );
  sky130_fd_sc_hd__o21ai_0 _194_ (
    .A1(_103_),
    .A2(_119_),
    .B1(_071_),
    .Y(_120_)
  );
  sky130_fd_sc_hd__clkinv_1 _195_ (
    .A(_120_),
    .Y(arrdiv_mux2to128_mux2to1_not0)
  );
  sky130_fd_sc_hd__a31oi_1 _196_ (
    .A1(_088_),
    .A2(_101_),
    .A3(_120_),
    .B1(_077_),
    .Y(_121_)
  );
  sky130_fd_sc_hd__nor2_1 _197_ (
    .A(b[5]),
    .B(_121_),
    .Y(_122_)
  );
  sky130_fd_sc_hd__xnor2_1 _198_ (
    .A(_107_),
    .B(_117_),
    .Y(_123_)
  );
  sky130_fd_sc_hd__nand2_1 _199_ (
    .A(_105_),
    .B(_120_),
    .Y(_124_)
  );
  sky130_fd_sc_hd__o21ai_0 _200_ (
    .A1(_120_),
    .A2(_123_),
    .B1(_124_),
    .Y(_125_)
  );
  sky130_fd_sc_hd__xnor2_1 _201_ (
    .A(b[4]),
    .B(_125_),
    .Y(_126_)
  );
  sky130_fd_sc_hd__clkinv_1 _202_ (
    .A(_126_),
    .Y(_127_)
  );
  sky130_fd_sc_hd__xnor2_1 _203_ (
    .A(_111_),
    .B(_116_),
    .Y(_128_)
  );
  sky130_fd_sc_hd__mux2i_1 _204_ (
    .A0(_128_),
    .A1(_109_),
    .S(_120_),
    .Y(_129_)
  );
  sky130_fd_sc_hd__xnor2_1 _205_ (
    .A(_067_),
    .B(_129_),
    .Y(_130_)
  );
  sky130_fd_sc_hd__xnor2_1 _206_ (
    .A(_114_),
    .B(_115_),
    .Y(_131_)
  );
  sky130_fd_sc_hd__mux2_1 _207_ (
    .A0(_131_),
    .A1(_113_),
    .S(_120_),
    .X(_132_)
  );
  sky130_fd_sc_hd__xor2_1 _208_ (
    .A(b[2]),
    .B(_132_),
    .X(_133_)
  );
  sky130_fd_sc_hd__o211ai_1 _209_ (
    .A1(_103_),
    .A2(_119_),
    .B1(b[0]),
    .C1(_071_),
    .Y(_134_)
  );
  sky130_fd_sc_hd__xor2_1 _210_ (
    .A(a[3]),
    .B(_134_),
    .X(_135_)
  );
  sky130_fd_sc_hd__xnor2_1 _211_ (
    .A(_066_),
    .B(_135_),
    .Y(_000_)
  );
  sky130_fd_sc_hd__nor2_1 _212_ (
    .A(a[2]),
    .B(_069_),
    .Y(_001_)
  );
  sky130_fd_sc_hd__maj3_1 _213_ (
    .A(b[1]),
    .B(_135_),
    .C(_001_),
    .X(_002_)
  );
  sky130_fd_sc_hd__and2_0 _214_ (
    .A(_133_),
    .B(_002_),
    .X(_003_)
  );
  sky130_fd_sc_hd__maj3_1 _215_ (
    .A(b[2]),
    .B(_132_),
    .C(_002_),
    .X(_004_)
  );
  sky130_fd_sc_hd__maj3_1 _216_ (
    .A(b[3]),
    .B(_129_),
    .C(_004_),
    .X(_005_)
  );
  sky130_fd_sc_hd__a22o_1 _217_ (
    .A1(b[5]),
    .A2(_121_),
    .B1(_125_),
    .B2(b[4]),
    .X(_006_)
  );
  sky130_fd_sc_hd__a21oi_1 _218_ (
    .A1(_127_),
    .A2(_005_),
    .B1(_006_),
    .Y(_007_)
  );
  sky130_fd_sc_hd__o21ai_0 _219_ (
    .A1(_122_),
    .A2(_007_),
    .B1(_070_),
    .Y(_008_)
  );
  sky130_fd_sc_hd__clkinv_1 _220_ (
    .A(_008_),
    .Y(arrdiv_mux2to135_mux2to1_not0)
  );
  sky130_fd_sc_hd__nor2_1 _221_ (
    .A(_121_),
    .B(arrdiv_mux2to135_mux2to1_not0),
    .Y(_009_)
  );
  sky130_fd_sc_hd__nor2_1 _222_ (
    .A(_077_),
    .B(_009_),
    .Y(_010_)
  );
  sky130_fd_sc_hd__nor2_1 _223_ (
    .A(b[6]),
    .B(_010_),
    .Y(_011_)
  );
  sky130_fd_sc_hd__xnor2_1 _224_ (
    .A(_127_),
    .B(_005_),
    .Y(_012_)
  );
  sky130_fd_sc_hd__nand2_1 _225_ (
    .A(_125_),
    .B(_008_),
    .Y(_013_)
  );
  sky130_fd_sc_hd__o21ai_0 _226_ (
    .A1(_008_),
    .A2(_012_),
    .B1(_013_),
    .Y(_014_)
  );
  sky130_fd_sc_hd__xnor2_1 _227_ (
    .A(b[5]),
    .B(_014_),
    .Y(_015_)
  );
  sky130_fd_sc_hd__clkinv_1 _228_ (
    .A(_015_),
    .Y(_016_)
  );
  sky130_fd_sc_hd__xnor2_1 _229_ (
    .A(_130_),
    .B(_004_),
    .Y(_017_)
  );
  sky130_fd_sc_hd__nand2_1 _230_ (
    .A(_129_),
    .B(_008_),
    .Y(_018_)
  );
  sky130_fd_sc_hd__o21ai_0 _231_ (
    .A1(_008_),
    .A2(_017_),
    .B1(_018_),
    .Y(_019_)
  );
  sky130_fd_sc_hd__xor2_1 _232_ (
    .A(b[4]),
    .B(_019_),
    .X(_020_)
  );
  sky130_fd_sc_hd__nor2_1 _233_ (
    .A(_133_),
    .B(_002_),
    .Y(_021_)
  );
  sky130_fd_sc_hd__nand2_1 _234_ (
    .A(_132_),
    .B(_008_),
    .Y(_022_)
  );
  sky130_fd_sc_hd__o31ai_1 _235_ (
    .A1(_003_),
    .A2(_008_),
    .A3(_021_),
    .B1(_022_),
    .Y(_023_)
  );
  sky130_fd_sc_hd__xnor2_1 _236_ (
    .A(b[3]),
    .B(_023_),
    .Y(_024_)
  );
  sky130_fd_sc_hd__xnor2_1 _237_ (
    .A(_000_),
    .B(_001_),
    .Y(_025_)
  );
  sky130_fd_sc_hd__nand2_1 _238_ (
    .A(_135_),
    .B(_008_),
    .Y(_026_)
  );
  sky130_fd_sc_hd__o21ai_0 _239_ (
    .A1(_008_),
    .A2(_025_),
    .B1(_026_),
    .Y(_027_)
  );
  sky130_fd_sc_hd__xnor2_1 _240_ (
    .A(b[2]),
    .B(_027_),
    .Y(_028_)
  );
  sky130_fd_sc_hd__o211ai_1 _241_ (
    .A1(_122_),
    .A2(_007_),
    .B1(b[0]),
    .C1(_070_),
    .Y(_029_)
  );
  sky130_fd_sc_hd__xor2_1 _242_ (
    .A(a[2]),
    .B(_029_),
    .X(_030_)
  );
  sky130_fd_sc_hd__xnor2_1 _243_ (
    .A(b[1]),
    .B(_030_),
    .Y(_031_)
  );
  sky130_fd_sc_hd__nor2_1 _244_ (
    .A(a[1]),
    .B(_069_),
    .Y(_032_)
  );
  sky130_fd_sc_hd__nand2b_1 _245_ (
    .A_N(a[1]),
    .B(b[0]),
    .Y(_033_)
  );
  sky130_fd_sc_hd__maj3_1 _246_ (
    .A(b[1]),
    .B(_030_),
    .C(_032_),
    .X(_034_)
  );
  sky130_fd_sc_hd__maj3_1 _247_ (
    .A(b[2]),
    .B(_027_),
    .C(_034_),
    .X(_035_)
  );
  sky130_fd_sc_hd__maj3_1 _248_ (
    .A(b[3]),
    .B(_023_),
    .C(_035_),
    .X(_036_)
  );
  sky130_fd_sc_hd__maj3_1 _249_ (
    .A(b[4]),
    .B(_019_),
    .C(_036_),
    .X(_037_)
  );
  sky130_fd_sc_hd__a22o_1 _250_ (
    .A1(b[6]),
    .A2(_010_),
    .B1(_014_),
    .B2(b[5]),
    .X(_038_)
  );
  sky130_fd_sc_hd__a21oi_1 _251_ (
    .A1(_016_),
    .A2(_037_),
    .B1(_038_),
    .Y(_039_)
  );
  sky130_fd_sc_hd__o21ai_0 _252_ (
    .A1(_011_),
    .A2(_039_),
    .B1(_068_),
    .Y(_040_)
  );
  sky130_fd_sc_hd__clkinv_1 _253_ (
    .A(_040_),
    .Y(arrdiv_mux2to142_mux2to1_not0)
  );
  sky130_fd_sc_hd__a21oi_1 _254_ (
    .A1(_009_),
    .A2(_040_),
    .B1(_077_),
    .Y(_041_)
  );
  sky130_fd_sc_hd__o211ai_1 _255_ (
    .A1(_011_),
    .A2(_039_),
    .B1(_068_),
    .C1(b[0]),
    .Y(_042_)
  );
  sky130_fd_sc_hd__a2bb2oi_1 _256_ (
    .A1_N(_033_),
    .A2_N(_040_),
    .B1(_042_),
    .B2(a[1]),
    .Y(_043_)
  );
  sky130_fd_sc_hd__nor3_1 _257_ (
    .A(_066_),
    .B(a[0]),
    .C(_069_),
    .Y(_044_)
  );
  sky130_fd_sc_hd__o21ai_0 _258_ (
    .A1(a[0]),
    .A2(_069_),
    .B1(_066_),
    .Y(_045_)
  );
  sky130_fd_sc_hd__xnor2_1 _259_ (
    .A(_031_),
    .B(_032_),
    .Y(_046_)
  );
  sky130_fd_sc_hd__mux2_1 _260_ (
    .A0(_046_),
    .A1(_030_),
    .S(_040_),
    .X(_047_)
  );
  sky130_fd_sc_hd__o221ai_1 _261_ (
    .A1(_043_),
    .A2(_044_),
    .B1(_047_),
    .B2(b[2]),
    .C1(_045_),
    .Y(_048_)
  );
  sky130_fd_sc_hd__xnor2_1 _262_ (
    .A(_028_),
    .B(_034_),
    .Y(_049_)
  );
  sky130_fd_sc_hd__mux2_1 _263_ (
    .A0(_049_),
    .A1(_027_),
    .S(_040_),
    .X(_050_)
  );
  sky130_fd_sc_hd__a22oi_1 _264_ (
    .A1(b[2]),
    .A2(_047_),
    .B1(_050_),
    .B2(b[3]),
    .Y(_051_)
  );
  sky130_fd_sc_hd__xnor2_1 _265_ (
    .A(_024_),
    .B(_035_),
    .Y(_052_)
  );
  sky130_fd_sc_hd__mux2_1 _266_ (
    .A0(_052_),
    .A1(_023_),
    .S(_040_),
    .X(_053_)
  );
  sky130_fd_sc_hd__o22ai_1 _267_ (
    .A1(b[3]),
    .A2(_050_),
    .B1(_053_),
    .B2(b[4]),
    .Y(_054_)
  );
  sky130_fd_sc_hd__a21o_1 _268_ (
    .A1(_048_),
    .A2(_051_),
    .B1(_054_),
    .X(_055_)
  );
  sky130_fd_sc_hd__xnor2_1 _269_ (
    .A(_020_),
    .B(_036_),
    .Y(_056_)
  );
  sky130_fd_sc_hd__nand2_1 _270_ (
    .A(_019_),
    .B(_040_),
    .Y(_057_)
  );
  sky130_fd_sc_hd__o21ai_0 _271_ (
    .A1(_040_),
    .A2(_056_),
    .B1(_057_),
    .Y(_058_)
  );
  sky130_fd_sc_hd__a22oi_1 _272_ (
    .A1(b[4]),
    .A2(_053_),
    .B1(_058_),
    .B2(b[5]),
    .Y(_059_)
  );
  sky130_fd_sc_hd__xnor2_1 _273_ (
    .A(_016_),
    .B(_037_),
    .Y(_060_)
  );
  sky130_fd_sc_hd__nand2_1 _274_ (
    .A(_014_),
    .B(_040_),
    .Y(_061_)
  );
  sky130_fd_sc_hd__o21ai_0 _275_ (
    .A1(_040_),
    .A2(_060_),
    .B1(_061_),
    .Y(_062_)
  );
  sky130_fd_sc_hd__o22ai_1 _276_ (
    .A1(b[5]),
    .A2(_058_),
    .B1(_062_),
    .B2(b[6]),
    .Y(_063_)
  );
  sky130_fd_sc_hd__a21oi_1 _277_ (
    .A1(_055_),
    .A2(_059_),
    .B1(_063_),
    .Y(_064_)
  );
  sky130_fd_sc_hd__a22o_1 _278_ (
    .A1(b[7]),
    .A2(_041_),
    .B1(_062_),
    .B2(b[6]),
    .X(_065_)
  );
  sky130_fd_sc_hd__o22ai_1 _279_ (
    .A1(b[7]),
    .A2(_041_),
    .B1(_064_),
    .B2(_065_),
    .Y(arrdiv_not7)
  );
  assign arrdiv_mux2to111_mux2to1_not0 = arrdiv_mux2to110_mux2to1_not0;
  assign arrdiv_mux2to112_mux2to1_not0 = arrdiv_mux2to110_mux2to1_not0;
  assign arrdiv_mux2to113_mux2to1_not0 = arrdiv_mux2to110_mux2to1_not0;
  assign arrdiv_mux2to115_mux2to1_not0 = arrdiv_mux2to114_mux2to1_not0;
  assign arrdiv_mux2to116_mux2to1_not0 = arrdiv_mux2to114_mux2to1_not0;
  assign arrdiv_mux2to117_mux2to1_not0 = arrdiv_mux2to114_mux2to1_not0;
  assign arrdiv_mux2to118_mux2to1_not0 = arrdiv_mux2to114_mux2to1_not0;
  assign arrdiv_mux2to119_mux2to1_not0 = arrdiv_mux2to114_mux2to1_not0;
  assign arrdiv_mux2to11_mux2to1_not0 = arrdiv_mux2to10_mux2to1_not0;
  assign arrdiv_mux2to120_mux2to1_not0 = arrdiv_mux2to114_mux2to1_not0;
  assign arrdiv_mux2to122_mux2to1_not0 = arrdiv_mux2to121_mux2to1_not0;
  assign arrdiv_mux2to123_mux2to1_not0 = arrdiv_mux2to121_mux2to1_not0;
  assign arrdiv_mux2to124_mux2to1_not0 = arrdiv_mux2to121_mux2to1_not0;
  assign arrdiv_mux2to125_mux2to1_not0 = arrdiv_mux2to121_mux2to1_not0;
  assign arrdiv_mux2to126_mux2to1_not0 = arrdiv_mux2to121_mux2to1_not0;
  assign arrdiv_mux2to127_mux2to1_not0 = arrdiv_mux2to121_mux2to1_not0;
  assign arrdiv_mux2to129_mux2to1_not0 = arrdiv_mux2to128_mux2to1_not0;
  assign arrdiv_mux2to12_mux2to1_not0 = arrdiv_mux2to10_mux2to1_not0;
  assign arrdiv_mux2to130_mux2to1_not0 = arrdiv_mux2to128_mux2to1_not0;
  assign arrdiv_mux2to131_mux2to1_not0 = arrdiv_mux2to128_mux2to1_not0;
  assign arrdiv_mux2to132_mux2to1_not0 = arrdiv_mux2to128_mux2to1_not0;
  assign arrdiv_mux2to133_mux2to1_not0 = arrdiv_mux2to128_mux2to1_not0;
  assign arrdiv_mux2to134_mux2to1_not0 = arrdiv_mux2to128_mux2to1_not0;
  assign arrdiv_mux2to136_mux2to1_not0 = arrdiv_mux2to135_mux2to1_not0;
  assign arrdiv_mux2to137_mux2to1_not0 = arrdiv_mux2to135_mux2to1_not0;
  assign arrdiv_mux2to138_mux2to1_not0 = arrdiv_mux2to135_mux2to1_not0;
  assign arrdiv_mux2to139_mux2to1_not0 = arrdiv_mux2to135_mux2to1_not0;
  assign arrdiv_mux2to13_mux2to1_not0 = arrdiv_mux2to10_mux2to1_not0;
  assign arrdiv_mux2to140_mux2to1_not0 = arrdiv_mux2to135_mux2to1_not0;
  assign arrdiv_mux2to141_mux2to1_not0 = arrdiv_mux2to135_mux2to1_not0;
  assign arrdiv_mux2to143_mux2to1_not0 = arrdiv_mux2to142_mux2to1_not0;
  assign arrdiv_mux2to144_mux2to1_not0 = arrdiv_mux2to142_mux2to1_not0;
  assign arrdiv_mux2to145_mux2to1_not0 = arrdiv_mux2to142_mux2to1_not0;
  assign arrdiv_mux2to146_mux2to1_not0 = arrdiv_mux2to142_mux2to1_not0;
  assign arrdiv_mux2to147_mux2to1_not0 = arrdiv_mux2to142_mux2to1_not0;
  assign arrdiv_mux2to148_mux2to1_not0 = arrdiv_mux2to142_mux2to1_not0;
  assign arrdiv_mux2to14_mux2to1_not0 = arrdiv_mux2to10_mux2to1_not0;
  assign arrdiv_mux2to15_mux2to1_not0 = arrdiv_mux2to10_mux2to1_not0;
  assign arrdiv_mux2to16_mux2to1_not0 = arrdiv_mux2to10_mux2to1_not0;
  assign arrdiv_mux2to17_mux2to1_not0 = arrdiv_mux2to110_mux2to1_not0;
  assign arrdiv_mux2to18_mux2to1_not0 = arrdiv_mux2to110_mux2to1_not0;
  assign arrdiv_mux2to19_mux2to1_not0 = arrdiv_mux2to110_mux2to1_not0;
  assign arrdiv_not0 = arrdiv_mux2to10_mux2to1_not0;
  assign arrdiv_not1 = arrdiv_mux2to110_mux2to1_not0;
  assign arrdiv_not2 = arrdiv_mux2to114_mux2to1_not0;
  assign arrdiv_not3 = arrdiv_mux2to121_mux2to1_not0;
  assign arrdiv_not4 = arrdiv_mux2to128_mux2to1_not0;
  assign arrdiv_not5 = arrdiv_mux2to135_mux2to1_not0;
  assign arrdiv_not6 = arrdiv_mux2to142_mux2to1_not0;
  assign arrdiv_out = { arrdiv_mux2to10_mux2to1_not0, arrdiv_mux2to110_mux2to1_not0, arrdiv_mux2to114_mux2to1_not0, arrdiv_mux2to121_mux2to1_not0, arrdiv_mux2to128_mux2to1_not0, arrdiv_mux2to135_mux2to1_not0, arrdiv_mux2to142_mux2to1_not0, arrdiv_not7 };
endmodule

(* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:1.1-23.10" *)
module mux2to1(sel, in0, in1, out);
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:3.16-3.19" *)
  input in0;
  wire in0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:4.16-4.19" *)
  input in1;
  wire in1;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:5.17-5.20" *)
  output out;
  wire out;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/mux2to1.v:2.16-2.19" *)
  input sel;
  wire sel;
  sky130_fd_sc_hd__mux2_1 _0_ (
    .A0(in0),
    .A1(in1),
    .S(sel),
    .X(out)
  );
endmodule

(* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/csa8.v:1.1-325.10" *)
module u_cosa(a, b, u_cosa_out);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/csa8.v:1.27-1.28" *)
  input [7:0] a;
  wire [7:0] a;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/csa8.v:1.42-1.43" *)
  input [7:0] b;
  wire [7:0] b;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/csa8.v:2.8-2.26" *)
  wire u_cosa_fa0_fa_xor0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/csa8.v:13.8-13.37" *)
  wire u_cosa_mux2to1_0_mux2to1_xor0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/csa8.v:93.8-93.38" *)
  wire u_cosa_mux2to1_14_mux2to1_xor0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/csa8.v:111.8-111.38" *)
  wire u_cosa_mux2to1_17_mux2to1_xor0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/csa8.v:153.8-153.38" *)
  wire u_cosa_mux2to1_26_mux2to1_xor0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/csa8.v:157.8-157.38" *)
  wire u_cosa_mux2to1_27_mux2to1_xor0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/csa8.v:27.8-27.37" *)
  wire u_cosa_mux2to1_2_mux2to1_xor0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/csa8.v:53.8-53.37" *)
  wire u_cosa_mux2to1_7_mux2to1_xor0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/csa8.v:67.8-67.37" *)
  wire u_cosa_mux2to1_9_mux2to1_xor0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/csa8.v:1.58-1.68" *)
  output [8:0] u_cosa_out;
  wire [8:0] u_cosa_out;
  sky130_fd_sc_hd__nand2_1 _23_ (
    .A(a[0]),
    .B(b[0]),
    .Y(_00_)
  );
  sky130_fd_sc_hd__xor2_1 _24_ (
    .A(a[0]),
    .B(b[0]),
    .X(u_cosa_fa0_fa_xor0)
  );
  sky130_fd_sc_hd__nand2_1 _25_ (
    .A(a[1]),
    .B(b[1]),
    .Y(_01_)
  );
  sky130_fd_sc_hd__nor2_1 _26_ (
    .A(a[1]),
    .B(b[1]),
    .Y(_02_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _27_ (
    .A(_01_),
    .SLEEP(_02_),
    .X(_03_)
  );
  sky130_fd_sc_hd__xnor2_1 _28_ (
    .A(_00_),
    .B(_03_),
    .Y(u_cosa_mux2to1_0_mux2to1_xor0)
  );
  sky130_fd_sc_hd__o21ai_0 _29_ (
    .A1(_00_),
    .A2(_02_),
    .B1(_01_),
    .Y(_04_)
  );
  sky130_fd_sc_hd__xnor2_1 _30_ (
    .A(a[2]),
    .B(b[2]),
    .Y(_05_)
  );
  sky130_fd_sc_hd__xnor2_1 _31_ (
    .A(_04_),
    .B(_05_),
    .Y(u_cosa_mux2to1_2_mux2to1_xor0)
  );
  sky130_fd_sc_hd__xnor2_1 _32_ (
    .A(a[3]),
    .B(b[3]),
    .Y(_06_)
  );
  sky130_fd_sc_hd__maj3_1 _33_ (
    .A(a[2]),
    .B(b[2]),
    .C(_04_),
    .X(_07_)
  );
  sky130_fd_sc_hd__xnor2_1 _34_ (
    .A(_06_),
    .B(_07_),
    .Y(u_cosa_mux2to1_7_mux2to1_xor0)
  );
  sky130_fd_sc_hd__maj3_1 _35_ (
    .A(a[3]),
    .B(b[3]),
    .C(_07_),
    .X(_08_)
  );
  sky130_fd_sc_hd__nand2_1 _36_ (
    .A(a[4]),
    .B(b[4]),
    .Y(_09_)
  );
  sky130_fd_sc_hd__nor2_1 _37_ (
    .A(a[4]),
    .B(b[4]),
    .Y(_10_)
  );
  sky130_fd_sc_hd__xnor2_1 _38_ (
    .A(a[4]),
    .B(b[4]),
    .Y(_11_)
  );
  sky130_fd_sc_hd__xnor2_1 _39_ (
    .A(_08_),
    .B(_11_),
    .Y(u_cosa_mux2to1_9_mux2to1_xor0)
  );
  sky130_fd_sc_hd__maj3_1 _40_ (
    .A(a[4]),
    .B(b[4]),
    .C(_08_),
    .X(_12_)
  );
  sky130_fd_sc_hd__nand2_1 _41_ (
    .A(a[5]),
    .B(b[5]),
    .Y(_13_)
  );
  sky130_fd_sc_hd__xnor2_1 _42_ (
    .A(a[5]),
    .B(b[5]),
    .Y(_14_)
  );
  sky130_fd_sc_hd__xnor2_1 _43_ (
    .A(_12_),
    .B(_14_),
    .Y(u_cosa_mux2to1_14_mux2to1_xor0)
  );
  sky130_fd_sc_hd__o21ai_0 _44_ (
    .A1(_10_),
    .A2(_14_),
    .B1(_13_),
    .Y(_15_)
  );
  sky130_fd_sc_hd__nor2_1 _45_ (
    .A(_09_),
    .B(_14_),
    .Y(_16_)
  );
  sky130_fd_sc_hd__a221oi_1 _46_ (
    .A1(a[5]),
    .A2(b[5]),
    .B1(_08_),
    .B2(_15_),
    .C1(_16_),
    .Y(_17_)
  );
  sky130_fd_sc_hd__nand2_1 _47_ (
    .A(a[6]),
    .B(b[6]),
    .Y(_18_)
  );
  sky130_fd_sc_hd__nor2_1 _48_ (
    .A(a[6]),
    .B(b[6]),
    .Y(_19_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _49_ (
    .A(_18_),
    .SLEEP(_19_),
    .X(_20_)
  );
  sky130_fd_sc_hd__xnor2_1 _50_ (
    .A(_17_),
    .B(_20_),
    .Y(u_cosa_mux2to1_17_mux2to1_xor0)
  );
  sky130_fd_sc_hd__xor2_1 _51_ (
    .A(a[7]),
    .B(b[7]),
    .X(_21_)
  );
  sky130_fd_sc_hd__o21ai_0 _52_ (
    .A1(_17_),
    .A2(_19_),
    .B1(_18_),
    .Y(_22_)
  );
  sky130_fd_sc_hd__xor2_1 _53_ (
    .A(_21_),
    .B(_22_),
    .X(u_cosa_mux2to1_26_mux2to1_xor0)
  );
  sky130_fd_sc_hd__a22o_1 _54_ (
    .A1(a[7]),
    .A2(b[7]),
    .B1(_21_),
    .B2(_22_),
    .X(u_cosa_mux2to1_27_mux2to1_xor0)
  );
  assign u_cosa_out = { u_cosa_mux2to1_27_mux2to1_xor0, u_cosa_mux2to1_26_mux2to1_xor0, u_cosa_mux2to1_17_mux2to1_xor0, u_cosa_mux2to1_14_mux2to1_xor0, u_cosa_mux2to1_9_mux2to1_xor0, u_cosa_mux2to1_7_mux2to1_xor0, u_cosa_mux2to1_2_mux2to1_xor0, u_cosa_mux2to1_0_mux2to1_xor0, u_cosa_fa0_fa_xor0 };
endmodule

(* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/cmu16.v:1.1-722.10" *)
module u_csamul(a, b, u_csamul_out);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/cmu16.v:1.29-1.30" *)
  input [7:0] a;
  wire [7:0] a;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/cmu16.v:1.44-1.45" *)
  input [7:0] b;
  wire [7:0] b;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/cmu16.v:2.8-2.23" *)
  wire u_csamul_and0_0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/cmu16.v:35.8-35.30" *)
  wire u_csamul_fa0_2_fa_xor1;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/cmu16.v:78.8-78.30" *)
  wire u_csamul_fa0_3_fa_xor1;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/cmu16.v:121.8-121.30" *)
  wire u_csamul_fa0_4_fa_xor1;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/cmu16.v:164.8-164.30" *)
  wire u_csamul_fa0_5_fa_xor1;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/cmu16.v:207.8-207.30" *)
  wire u_csamul_fa0_6_fa_xor1;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/cmu16.v:250.8-250.30" *)
  wire u_csamul_fa0_7_fa_xor1;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/cmu16.v:11.8-11.30" *)
  wire u_csamul_ha0_1_ha_xor0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/cmu16.v:1.61-1.73" *)
  output [15:0] u_csamul_out;
  wire [15:0] u_csamul_out;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/cmu16.v:350.8-350.34" *)
  wire u_csamul_u_cla8_or1_2_2_11;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/cmu16.v:292.8-292.47" *)
  wire u_csamul_u_cla8_pg_logic0_pg_logic_xor0;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/cmu16.v:296.8-296.28" *)
  wire u_csamul_u_cla8_xor1;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/cmu16.v:302.8-302.28" *)
  wire u_csamul_u_cla8_xor2;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/cmu16.v:312.8-312.28" *)
  wire u_csamul_u_cla8_xor3;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/cmu16.v:326.8-326.28" *)
  wire u_csamul_u_cla8_xor4;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/cmu16.v:332.8-332.28" *)
  wire u_csamul_u_cla8_xor5;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/cmu16.v:341.8-341.28" *)
  wire u_csamul_u_cla8_xor6;
  sky130_fd_sc_hd__and2_0 _231_ (
    .A(a[0]),
    .B(b[0]),
    .X(u_csamul_and0_0)
  );
  sky130_fd_sc_hd__and4_1 _232_ (
    .A(a[0]),
    .B(b[0]),
    .C(a[1]),
    .D(b[1]),
    .X(_170_)
  );
  sky130_fd_sc_hd__a22oi_1 _233_ (
    .A1(b[0]),
    .A2(a[1]),
    .B1(b[1]),
    .B2(a[0]),
    .Y(_171_)
  );
  sky130_fd_sc_hd__nor2_1 _234_ (
    .A(_170_),
    .B(_171_),
    .Y(u_csamul_ha0_1_ha_xor0)
  );
  sky130_fd_sc_hd__nand2_1 _235_ (
    .A(a[0]),
    .B(b[2]),
    .Y(_172_)
  );
  sky130_fd_sc_hd__and4_1 _236_ (
    .A(b[0]),
    .B(a[1]),
    .C(a[2]),
    .D(b[1]),
    .X(_173_)
  );
  sky130_fd_sc_hd__clkinv_1 _237_ (
    .A(_173_),
    .Y(_174_)
  );
  sky130_fd_sc_hd__a22oi_1 _238_ (
    .A1(b[0]),
    .A2(a[2]),
    .B1(b[1]),
    .B2(a[1]),
    .Y(_175_)
  );
  sky130_fd_sc_hd__nor3_1 _239_ (
    .A(_172_),
    .B(_173_),
    .C(_175_),
    .Y(_176_)
  );
  sky130_fd_sc_hd__o21ai_0 _240_ (
    .A1(_173_),
    .A2(_175_),
    .B1(_172_),
    .Y(_177_)
  );
  sky130_fd_sc_hd__nor2b_1 _241_ (
    .A(_176_),
    .B_N(_177_),
    .Y(_178_)
  );
  sky130_fd_sc_hd__xor2_1 _242_ (
    .A(_170_),
    .B(_178_),
    .X(u_csamul_fa0_2_fa_xor1)
  );
  sky130_fd_sc_hd__a21oi_1 _243_ (
    .A1(_170_),
    .A2(_177_),
    .B1(_176_),
    .Y(_179_)
  );
  sky130_fd_sc_hd__nand2_1 _244_ (
    .A(a[0]),
    .B(b[3]),
    .Y(_180_)
  );
  sky130_fd_sc_hd__nand2_1 _245_ (
    .A(a[1]),
    .B(b[2]),
    .Y(_181_)
  );
  sky130_fd_sc_hd__nand4_1 _246_ (
    .A(b[0]),
    .B(a[2]),
    .C(a[3]),
    .D(b[1]),
    .Y(_182_)
  );
  sky130_fd_sc_hd__a22o_1 _247_ (
    .A1(b[0]),
    .A2(a[3]),
    .B1(b[1]),
    .B2(a[2]),
    .X(_183_)
  );
  sky130_fd_sc_hd__nand2_1 _248_ (
    .A(_182_),
    .B(_183_),
    .Y(_184_)
  );
  sky130_fd_sc_hd__xnor3_1 _249_ (
    .A(_173_),
    .B(_181_),
    .C(_184_),
    .X(_185_)
  );
  sky130_fd_sc_hd__xnor3_1 _250_ (
    .A(_179_),
    .B(_180_),
    .C(_185_),
    .X(u_csamul_fa0_3_fa_xor1)
  );
  sky130_fd_sc_hd__maj3_1 _251_ (
    .A(_179_),
    .B(_180_),
    .C(_185_),
    .X(_186_)
  );
  sky130_fd_sc_hd__nand2_1 _252_ (
    .A(a[0]),
    .B(b[4]),
    .Y(_187_)
  );
  sky130_fd_sc_hd__maj3_1 _253_ (
    .A(_174_),
    .B(_181_),
    .C(_184_),
    .X(_188_)
  );
  sky130_fd_sc_hd__nand2_1 _254_ (
    .A(a[1]),
    .B(b[3]),
    .Y(_189_)
  );
  sky130_fd_sc_hd__nand2_1 _255_ (
    .A(a[2]),
    .B(b[2]),
    .Y(_190_)
  );
  sky130_fd_sc_hd__and2_0 _256_ (
    .A(a[3]),
    .B(b[1]),
    .X(_191_)
  );
  sky130_fd_sc_hd__and2_0 _257_ (
    .A(b[0]),
    .B(a[4]),
    .X(_192_)
  );
  sky130_fd_sc_hd__nand2_1 _258_ (
    .A(_191_),
    .B(_192_),
    .Y(_193_)
  );
  sky130_fd_sc_hd__xnor2_1 _259_ (
    .A(_191_),
    .B(_192_),
    .Y(_194_)
  );
  sky130_fd_sc_hd__xnor3_1 _260_ (
    .A(_190_),
    .B(_191_),
    .C(_192_),
    .X(_195_)
  );
  sky130_fd_sc_hd__xor2_1 _261_ (
    .A(_182_),
    .B(_195_),
    .X(_196_)
  );
  sky130_fd_sc_hd__xor3_1 _262_ (
    .A(_182_),
    .B(_189_),
    .C(_195_),
    .X(_197_)
  );
  sky130_fd_sc_hd__xnor2_1 _263_ (
    .A(_188_),
    .B(_197_),
    .Y(_198_)
  );
  sky130_fd_sc_hd__nand3_1 _264_ (
    .A(a[0]),
    .B(b[4]),
    .C(_198_),
    .Y(_199_)
  );
  sky130_fd_sc_hd__xor3_1 _265_ (
    .A(_187_),
    .B(_188_),
    .C(_197_),
    .X(_200_)
  );
  sky130_fd_sc_hd__nand2b_1 _266_ (
    .A_N(_186_),
    .B(_200_),
    .Y(_201_)
  );
  sky130_fd_sc_hd__xnor2_1 _267_ (
    .A(_186_),
    .B(_200_),
    .Y(u_csamul_fa0_4_fa_xor1)
  );
  sky130_fd_sc_hd__nand2_1 _268_ (
    .A(a[0]),
    .B(b[5]),
    .Y(_202_)
  );
  sky130_fd_sc_hd__maj3_1 _269_ (
    .A(_188_),
    .B(_189_),
    .C(_196_),
    .X(_203_)
  );
  sky130_fd_sc_hd__nand2_1 _270_ (
    .A(a[1]),
    .B(b[4]),
    .Y(_204_)
  );
  sky130_fd_sc_hd__maj3_1 _271_ (
    .A(_182_),
    .B(_190_),
    .C(_194_),
    .X(_205_)
  );
  sky130_fd_sc_hd__nand2_1 _272_ (
    .A(a[2]),
    .B(b[3]),
    .Y(_206_)
  );
  sky130_fd_sc_hd__and2_0 _273_ (
    .A(a[3]),
    .B(b[2]),
    .X(_207_)
  );
  sky130_fd_sc_hd__and2_0 _274_ (
    .A(a[4]),
    .B(b[1]),
    .X(_208_)
  );
  sky130_fd_sc_hd__and2_0 _275_ (
    .A(b[0]),
    .B(a[5]),
    .X(_209_)
  );
  sky130_fd_sc_hd__nand2_1 _276_ (
    .A(_208_),
    .B(_209_),
    .Y(_210_)
  );
  sky130_fd_sc_hd__xor2_1 _277_ (
    .A(_208_),
    .B(_209_),
    .X(_211_)
  );
  sky130_fd_sc_hd__xor3_1 _278_ (
    .A(_207_),
    .B(_208_),
    .C(_209_),
    .X(_212_)
  );
  sky130_fd_sc_hd__xor2_1 _279_ (
    .A(_193_),
    .B(_212_),
    .X(_213_)
  );
  sky130_fd_sc_hd__xor3_1 _280_ (
    .A(_193_),
    .B(_206_),
    .C(_212_),
    .X(_214_)
  );
  sky130_fd_sc_hd__xor2_1 _281_ (
    .A(_205_),
    .B(_214_),
    .X(_215_)
  );
  sky130_fd_sc_hd__xor3_1 _282_ (
    .A(_204_),
    .B(_205_),
    .C(_214_),
    .X(_216_)
  );
  sky130_fd_sc_hd__xor2_1 _283_ (
    .A(_203_),
    .B(_216_),
    .X(_217_)
  );
  sky130_fd_sc_hd__nor2_1 _284_ (
    .A(_202_),
    .B(_217_),
    .Y(_218_)
  );
  sky130_fd_sc_hd__xnor3_1 _285_ (
    .A(_202_),
    .B(_203_),
    .C(_216_),
    .X(_219_)
  );
  sky130_fd_sc_hd__a21oi_1 _286_ (
    .A1(_199_),
    .A2(_201_),
    .B1(_219_),
    .Y(_220_)
  );
  sky130_fd_sc_hd__and3_1 _287_ (
    .A(_199_),
    .B(_201_),
    .C(_219_),
    .X(_221_)
  );
  sky130_fd_sc_hd__nor2_1 _288_ (
    .A(_220_),
    .B(_221_),
    .Y(u_csamul_fa0_5_fa_xor1)
  );
  sky130_fd_sc_hd__nand2_1 _289_ (
    .A(a[0]),
    .B(b[6]),
    .Y(_222_)
  );
  sky130_fd_sc_hd__maj3_1 _290_ (
    .A(_203_),
    .B(_204_),
    .C(_215_),
    .X(_223_)
  );
  sky130_fd_sc_hd__nand2_1 _291_ (
    .A(a[1]),
    .B(b[5]),
    .Y(_224_)
  );
  sky130_fd_sc_hd__maj3_1 _292_ (
    .A(_205_),
    .B(_206_),
    .C(_213_),
    .X(_225_)
  );
  sky130_fd_sc_hd__nand2_1 _293_ (
    .A(a[2]),
    .B(b[4]),
    .Y(_226_)
  );
  sky130_fd_sc_hd__a32oi_1 _294_ (
    .A1(_191_),
    .A2(_192_),
    .A3(_212_),
    .B1(_211_),
    .B2(_207_),
    .Y(_227_)
  );
  sky130_fd_sc_hd__nand2_1 _295_ (
    .A(a[3]),
    .B(b[3]),
    .Y(_228_)
  );
  sky130_fd_sc_hd__and2_0 _296_ (
    .A(a[4]),
    .B(b[2]),
    .X(_229_)
  );
  sky130_fd_sc_hd__and2_0 _297_ (
    .A(a[5]),
    .B(b[1]),
    .X(_230_)
  );
  sky130_fd_sc_hd__and2_0 _298_ (
    .A(b[0]),
    .B(a[6]),
    .X(_000_)
  );
  sky130_fd_sc_hd__nand2_1 _299_ (
    .A(_230_),
    .B(_000_),
    .Y(_001_)
  );
  sky130_fd_sc_hd__xor2_1 _300_ (
    .A(_230_),
    .B(_000_),
    .X(_002_)
  );
  sky130_fd_sc_hd__xor3_1 _301_ (
    .A(_229_),
    .B(_230_),
    .C(_000_),
    .X(_003_)
  );
  sky130_fd_sc_hd__xor2_1 _302_ (
    .A(_210_),
    .B(_003_),
    .X(_004_)
  );
  sky130_fd_sc_hd__xor3_1 _303_ (
    .A(_210_),
    .B(_228_),
    .C(_003_),
    .X(_005_)
  );
  sky130_fd_sc_hd__xor2_1 _304_ (
    .A(_227_),
    .B(_005_),
    .X(_006_)
  );
  sky130_fd_sc_hd__xor3_1 _305_ (
    .A(_226_),
    .B(_227_),
    .C(_005_),
    .X(_007_)
  );
  sky130_fd_sc_hd__xor2_1 _306_ (
    .A(_225_),
    .B(_007_),
    .X(_008_)
  );
  sky130_fd_sc_hd__xnor3_1 _307_ (
    .A(_224_),
    .B(_225_),
    .C(_007_),
    .X(_009_)
  );
  sky130_fd_sc_hd__xor2_1 _308_ (
    .A(_223_),
    .B(_009_),
    .X(_010_)
  );
  sky130_fd_sc_hd__nand3_1 _309_ (
    .A(a[0]),
    .B(b[6]),
    .C(_010_),
    .Y(_011_)
  );
  sky130_fd_sc_hd__xnor3_1 _310_ (
    .A(_222_),
    .B(_223_),
    .C(_009_),
    .X(_012_)
  );
  sky130_fd_sc_hd__o21ai_0 _311_ (
    .A1(_218_),
    .A2(_220_),
    .B1(_012_),
    .Y(_013_)
  );
  sky130_fd_sc_hd__nor3_1 _312_ (
    .A(_218_),
    .B(_220_),
    .C(_012_),
    .Y(_014_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _313_ (
    .A(_013_),
    .SLEEP(_014_),
    .X(u_csamul_fa0_6_fa_xor1)
  );
  sky130_fd_sc_hd__nand2_1 _314_ (
    .A(a[0]),
    .B(b[7]),
    .Y(_015_)
  );
  sky130_fd_sc_hd__maj3_1 _315_ (
    .A(_223_),
    .B(_224_),
    .C(_008_),
    .X(_016_)
  );
  sky130_fd_sc_hd__nand2_1 _316_ (
    .A(a[1]),
    .B(b[6]),
    .Y(_017_)
  );
  sky130_fd_sc_hd__maj3_1 _317_ (
    .A(_225_),
    .B(_226_),
    .C(_006_),
    .X(_018_)
  );
  sky130_fd_sc_hd__nand2_1 _318_ (
    .A(a[2]),
    .B(b[5]),
    .Y(_019_)
  );
  sky130_fd_sc_hd__maj3_1 _319_ (
    .A(_227_),
    .B(_228_),
    .C(_004_),
    .X(_020_)
  );
  sky130_fd_sc_hd__nand2_1 _320_ (
    .A(a[3]),
    .B(b[4]),
    .Y(_021_)
  );
  sky130_fd_sc_hd__a32oi_1 _321_ (
    .A1(_208_),
    .A2(_209_),
    .A3(_003_),
    .B1(_002_),
    .B2(_229_),
    .Y(_022_)
  );
  sky130_fd_sc_hd__nand2_1 _322_ (
    .A(a[4]),
    .B(b[3]),
    .Y(_023_)
  );
  sky130_fd_sc_hd__nand2_1 _323_ (
    .A(a[5]),
    .B(b[2]),
    .Y(_024_)
  );
  sky130_fd_sc_hd__nand2_1 _324_ (
    .A(a[6]),
    .B(b[1]),
    .Y(_025_)
  );
  sky130_fd_sc_hd__nand2_1 _325_ (
    .A(b[0]),
    .B(a[7]),
    .Y(_026_)
  );
  sky130_fd_sc_hd__and4_1 _326_ (
    .A(b[0]),
    .B(a[6]),
    .C(a[7]),
    .D(b[1]),
    .X(_027_)
  );
  sky130_fd_sc_hd__a22oi_1 _327_ (
    .A1(b[0]),
    .A2(a[7]),
    .B1(b[1]),
    .B2(a[6]),
    .Y(_028_)
  );
  sky130_fd_sc_hd__nor3_1 _328_ (
    .A(_024_),
    .B(_027_),
    .C(_028_),
    .Y(_029_)
  );
  sky130_fd_sc_hd__xnor3_1 _329_ (
    .A(_024_),
    .B(_025_),
    .C(_026_),
    .X(_030_)
  );
  sky130_fd_sc_hd__xor2_1 _330_ (
    .A(_001_),
    .B(_030_),
    .X(_031_)
  );
  sky130_fd_sc_hd__xor3_1 _331_ (
    .A(_001_),
    .B(_023_),
    .C(_030_),
    .X(_032_)
  );
  sky130_fd_sc_hd__xor2_1 _332_ (
    .A(_022_),
    .B(_032_),
    .X(_033_)
  );
  sky130_fd_sc_hd__xnor3_1 _333_ (
    .A(_021_),
    .B(_022_),
    .C(_032_),
    .X(_034_)
  );
  sky130_fd_sc_hd__xnor2_1 _334_ (
    .A(_020_),
    .B(_034_),
    .Y(_035_)
  );
  sky130_fd_sc_hd__xor3_1 _335_ (
    .A(_019_),
    .B(_020_),
    .C(_034_),
    .X(_036_)
  );
  sky130_fd_sc_hd__xnor2_1 _336_ (
    .A(_018_),
    .B(_036_),
    .Y(_037_)
  );
  sky130_fd_sc_hd__xnor3_1 _337_ (
    .A(_017_),
    .B(_018_),
    .C(_036_),
    .X(_038_)
  );
  sky130_fd_sc_hd__xor2_1 _338_ (
    .A(_016_),
    .B(_038_),
    .X(_039_)
  );
  sky130_fd_sc_hd__nor2_1 _339_ (
    .A(_015_),
    .B(_039_),
    .Y(_040_)
  );
  sky130_fd_sc_hd__xnor3_1 _340_ (
    .A(_015_),
    .B(_016_),
    .C(_038_),
    .X(_041_)
  );
  sky130_fd_sc_hd__a21oi_1 _341_ (
    .A1(_011_),
    .A2(_013_),
    .B1(_041_),
    .Y(_042_)
  );
  sky130_fd_sc_hd__nand3_1 _342_ (
    .A(_011_),
    .B(_013_),
    .C(_041_),
    .Y(_043_)
  );
  sky130_fd_sc_hd__nor2b_1 _343_ (
    .A(_042_),
    .B_N(_043_),
    .Y(u_csamul_fa0_7_fa_xor1)
  );
  sky130_fd_sc_hd__maj3_1 _344_ (
    .A(_016_),
    .B(_017_),
    .C(_037_),
    .X(_044_)
  );
  sky130_fd_sc_hd__nand2_1 _345_ (
    .A(a[1]),
    .B(b[7]),
    .Y(_045_)
  );
  sky130_fd_sc_hd__maj3_1 _346_ (
    .A(_018_),
    .B(_019_),
    .C(_035_),
    .X(_046_)
  );
  sky130_fd_sc_hd__nand2_1 _347_ (
    .A(a[2]),
    .B(b[6]),
    .Y(_047_)
  );
  sky130_fd_sc_hd__maj3_1 _348_ (
    .A(_020_),
    .B(_021_),
    .C(_033_),
    .X(_048_)
  );
  sky130_fd_sc_hd__nand2_1 _349_ (
    .A(a[3]),
    .B(b[5]),
    .Y(_049_)
  );
  sky130_fd_sc_hd__maj3_1 _350_ (
    .A(_022_),
    .B(_023_),
    .C(_031_),
    .X(_050_)
  );
  sky130_fd_sc_hd__nand2_1 _351_ (
    .A(a[4]),
    .B(b[4]),
    .Y(_051_)
  );
  sky130_fd_sc_hd__a31oi_1 _352_ (
    .A1(_230_),
    .A2(_000_),
    .A3(_030_),
    .B1(_029_),
    .Y(_052_)
  );
  sky130_fd_sc_hd__nand2_1 _353_ (
    .A(a[5]),
    .B(b[3]),
    .Y(_053_)
  );
  sky130_fd_sc_hd__nand2_1 _354_ (
    .A(a[6]),
    .B(b[2]),
    .Y(_054_)
  );
  sky130_fd_sc_hd__nand2_1 _355_ (
    .A(a[7]),
    .B(b[1]),
    .Y(_055_)
  );
  sky130_fd_sc_hd__xor2_1 _356_ (
    .A(_054_),
    .B(_055_),
    .X(_056_)
  );
  sky130_fd_sc_hd__xnor2_1 _357_ (
    .A(_027_),
    .B(_056_),
    .Y(_057_)
  );
  sky130_fd_sc_hd__xnor3_1 _358_ (
    .A(_027_),
    .B(_053_),
    .C(_056_),
    .X(_058_)
  );
  sky130_fd_sc_hd__xor2_1 _359_ (
    .A(_052_),
    .B(_058_),
    .X(_059_)
  );
  sky130_fd_sc_hd__xnor3_1 _360_ (
    .A(_051_),
    .B(_052_),
    .C(_058_),
    .X(_060_)
  );
  sky130_fd_sc_hd__xnor2_1 _361_ (
    .A(_050_),
    .B(_060_),
    .Y(_061_)
  );
  sky130_fd_sc_hd__xor3_1 _362_ (
    .A(_049_),
    .B(_050_),
    .C(_060_),
    .X(_062_)
  );
  sky130_fd_sc_hd__xnor2_1 _363_ (
    .A(_048_),
    .B(_062_),
    .Y(_063_)
  );
  sky130_fd_sc_hd__xnor3_1 _364_ (
    .A(_047_),
    .B(_048_),
    .C(_062_),
    .X(_064_)
  );
  sky130_fd_sc_hd__xor2_1 _365_ (
    .A(_046_),
    .B(_064_),
    .X(_065_)
  );
  sky130_fd_sc_hd__nor2_1 _366_ (
    .A(_045_),
    .B(_065_),
    .Y(_066_)
  );
  sky130_fd_sc_hd__xnor3_1 _367_ (
    .A(_045_),
    .B(_046_),
    .C(_064_),
    .X(_067_)
  );
  sky130_fd_sc_hd__nor2_1 _368_ (
    .A(_044_),
    .B(_067_),
    .Y(_068_)
  );
  sky130_fd_sc_hd__xor2_1 _369_ (
    .A(_044_),
    .B(_067_),
    .X(_069_)
  );
  sky130_fd_sc_hd__o21ai_0 _370_ (
    .A1(_040_),
    .A2(_042_),
    .B1(_069_),
    .Y(_070_)
  );
  sky130_fd_sc_hd__nor3_1 _371_ (
    .A(_040_),
    .B(_042_),
    .C(_069_),
    .Y(_071_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _372_ (
    .A(_070_),
    .SLEEP(_071_),
    .X(u_csamul_u_cla8_pg_logic0_pg_logic_xor0)
  );
  sky130_fd_sc_hd__maj3_1 _373_ (
    .A(_046_),
    .B(_047_),
    .C(_063_),
    .X(_072_)
  );
  sky130_fd_sc_hd__nand2_1 _374_ (
    .A(a[2]),
    .B(b[7]),
    .Y(_073_)
  );
  sky130_fd_sc_hd__maj3_1 _375_ (
    .A(_048_),
    .B(_049_),
    .C(_061_),
    .X(_074_)
  );
  sky130_fd_sc_hd__nand2_1 _376_ (
    .A(a[3]),
    .B(b[6]),
    .Y(_075_)
  );
  sky130_fd_sc_hd__maj3_1 _377_ (
    .A(_050_),
    .B(_051_),
    .C(_059_),
    .X(_076_)
  );
  sky130_fd_sc_hd__nand2_1 _378_ (
    .A(a[4]),
    .B(b[5]),
    .Y(_077_)
  );
  sky130_fd_sc_hd__maj3_1 _379_ (
    .A(_052_),
    .B(_053_),
    .C(_057_),
    .X(_078_)
  );
  sky130_fd_sc_hd__nand2_1 _380_ (
    .A(a[5]),
    .B(b[4]),
    .Y(_079_)
  );
  sky130_fd_sc_hd__o2111ai_1 _381_ (
    .A1(b[0]),
    .A2(b[2]),
    .B1(b[1]),
    .C1(a[7]),
    .D1(a[6]),
    .Y(_080_)
  );
  sky130_fd_sc_hd__and4_1 _382_ (
    .A(a[6]),
    .B(a[7]),
    .C(b[2]),
    .D(b[3]),
    .X(_081_)
  );
  sky130_fd_sc_hd__a22oi_1 _383_ (
    .A1(a[7]),
    .A2(b[2]),
    .B1(b[3]),
    .B2(a[6]),
    .Y(_082_)
  );
  sky130_fd_sc_hd__nor3_1 _384_ (
    .A(_080_),
    .B(_081_),
    .C(_082_),
    .Y(_083_)
  );
  sky130_fd_sc_hd__o21a_1 _385_ (
    .A1(_081_),
    .A2(_082_),
    .B1(_080_),
    .X(_084_)
  );
  sky130_fd_sc_hd__nor2_1 _386_ (
    .A(_083_),
    .B(_084_),
    .Y(_085_)
  );
  sky130_fd_sc_hd__clkinv_1 _387_ (
    .A(_085_),
    .Y(_086_)
  );
  sky130_fd_sc_hd__xnor2_1 _388_ (
    .A(_079_),
    .B(_085_),
    .Y(_087_)
  );
  sky130_fd_sc_hd__xor2_1 _389_ (
    .A(_078_),
    .B(_087_),
    .X(_088_)
  );
  sky130_fd_sc_hd__xor3_1 _390_ (
    .A(_077_),
    .B(_078_),
    .C(_087_),
    .X(_089_)
  );
  sky130_fd_sc_hd__xnor2_1 _391_ (
    .A(_076_),
    .B(_089_),
    .Y(_090_)
  );
  sky130_fd_sc_hd__xnor3_1 _392_ (
    .A(_075_),
    .B(_076_),
    .C(_089_),
    .X(_091_)
  );
  sky130_fd_sc_hd__nor2_1 _393_ (
    .A(_074_),
    .B(_091_),
    .Y(_092_)
  );
  sky130_fd_sc_hd__nand2_1 _394_ (
    .A(_074_),
    .B(_091_),
    .Y(_093_)
  );
  sky130_fd_sc_hd__nor3b_1 _395_ (
    .A(_073_),
    .B(_092_),
    .C_N(_093_),
    .Y(_094_)
  );
  sky130_fd_sc_hd__xor3_1 _396_ (
    .A(_073_),
    .B(_074_),
    .C(_091_),
    .X(_095_)
  );
  sky130_fd_sc_hd__nor2_1 _397_ (
    .A(_072_),
    .B(_095_),
    .Y(_096_)
  );
  sky130_fd_sc_hd__xor2_1 _398_ (
    .A(_072_),
    .B(_095_),
    .X(_097_)
  );
  sky130_fd_sc_hd__o21ai_0 _399_ (
    .A1(_066_),
    .A2(_068_),
    .B1(_097_),
    .Y(_098_)
  );
  sky130_fd_sc_hd__nor3_1 _400_ (
    .A(_066_),
    .B(_068_),
    .C(_097_),
    .Y(_099_)
  );
  sky130_fd_sc_hd__or3_1 _401_ (
    .A(_066_),
    .B(_068_),
    .C(_097_),
    .X(_100_)
  );
  sky130_fd_sc_hd__nand2_1 _402_ (
    .A(_098_),
    .B(_100_),
    .Y(_101_)
  );
  sky130_fd_sc_hd__xor2_1 _403_ (
    .A(_070_),
    .B(_101_),
    .X(u_csamul_u_cla8_xor1)
  );
  sky130_fd_sc_hd__o21ai_0 _404_ (
    .A1(_070_),
    .A2(_099_),
    .B1(_098_),
    .Y(_102_)
  );
  sky130_fd_sc_hd__a31oi_1 _405_ (
    .A1(a[3]),
    .A2(b[6]),
    .A3(_090_),
    .B1(_092_),
    .Y(_103_)
  );
  sky130_fd_sc_hd__nand2_1 _406_ (
    .A(a[3]),
    .B(b[7]),
    .Y(_104_)
  );
  sky130_fd_sc_hd__maj3_1 _407_ (
    .A(_076_),
    .B(_077_),
    .C(_088_),
    .X(_105_)
  );
  sky130_fd_sc_hd__nand2_1 _408_ (
    .A(a[4]),
    .B(b[6]),
    .Y(_106_)
  );
  sky130_fd_sc_hd__maj3_1 _409_ (
    .A(_078_),
    .B(_079_),
    .C(_086_),
    .X(_107_)
  );
  sky130_fd_sc_hd__nand2_1 _410_ (
    .A(a[5]),
    .B(b[5]),
    .Y(_108_)
  );
  sky130_fd_sc_hd__nor2_1 _411_ (
    .A(_081_),
    .B(_083_),
    .Y(_109_)
  );
  sky130_fd_sc_hd__and4_1 _412_ (
    .A(a[6]),
    .B(a[7]),
    .C(b[3]),
    .D(b[4]),
    .X(_110_)
  );
  sky130_fd_sc_hd__a22oi_1 _413_ (
    .A1(a[7]),
    .A2(b[3]),
    .B1(b[4]),
    .B2(a[6]),
    .Y(_111_)
  );
  sky130_fd_sc_hd__nor2_1 _414_ (
    .A(_110_),
    .B(_111_),
    .Y(_112_)
  );
  sky130_fd_sc_hd__xnor2_1 _415_ (
    .A(_109_),
    .B(_112_),
    .Y(_113_)
  );
  sky130_fd_sc_hd__xnor2_1 _416_ (
    .A(_108_),
    .B(_113_),
    .Y(_114_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _417_ (
    .A(_114_),
    .SLEEP(_107_),
    .X(_115_)
  );
  sky130_fd_sc_hd__xor2_1 _418_ (
    .A(_107_),
    .B(_114_),
    .X(_116_)
  );
  sky130_fd_sc_hd__xnor3_1 _419_ (
    .A(_105_),
    .B(_106_),
    .C(_116_),
    .X(_117_)
  );
  sky130_fd_sc_hd__nor2b_1 _420_ (
    .A(_104_),
    .B_N(_117_),
    .Y(_118_)
  );
  sky130_fd_sc_hd__xor2_1 _421_ (
    .A(_104_),
    .B(_117_),
    .X(_119_)
  );
  sky130_fd_sc_hd__nor2_1 _422_ (
    .A(_103_),
    .B(_119_),
    .Y(_120_)
  );
  sky130_fd_sc_hd__xor2_1 _423_ (
    .A(_103_),
    .B(_119_),
    .X(_121_)
  );
  sky130_fd_sc_hd__o21a_1 _424_ (
    .A1(_094_),
    .A2(_096_),
    .B1(_121_),
    .X(_122_)
  );
  sky130_fd_sc_hd__or3_1 _425_ (
    .A(_094_),
    .B(_096_),
    .C(_121_),
    .X(_123_)
  );
  sky130_fd_sc_hd__nor2b_1 _426_ (
    .A(_122_),
    .B_N(_123_),
    .Y(_124_)
  );
  sky130_fd_sc_hd__xor2_1 _427_ (
    .A(_102_),
    .B(_124_),
    .X(u_csamul_u_cla8_xor2)
  );
  sky130_fd_sc_hd__a21oi_1 _428_ (
    .A1(_102_),
    .A2(_123_),
    .B1(_122_),
    .Y(_125_)
  );
  sky130_fd_sc_hd__maj3_1 _429_ (
    .A(_105_),
    .B(_106_),
    .C(_116_),
    .X(_126_)
  );
  sky130_fd_sc_hd__nand2_1 _430_ (
    .A(a[4]),
    .B(b[7]),
    .Y(_127_)
  );
  sky130_fd_sc_hd__a31oi_1 _431_ (
    .A1(a[5]),
    .A2(b[5]),
    .A3(_113_),
    .B1(_115_),
    .Y(_128_)
  );
  sky130_fd_sc_hd__o21ba_1 _432_ (
    .A1(_109_),
    .A2(_111_),
    .B1_N(_110_),
    .X(_129_)
  );
  sky130_fd_sc_hd__and4_1 _433_ (
    .A(a[6]),
    .B(a[7]),
    .C(b[4]),
    .D(b[5]),
    .X(_130_)
  );
  sky130_fd_sc_hd__a22oi_1 _434_ (
    .A1(a[7]),
    .A2(b[4]),
    .B1(b[5]),
    .B2(a[6]),
    .Y(_131_)
  );
  sky130_fd_sc_hd__nor2_1 _435_ (
    .A(_130_),
    .B(_131_),
    .Y(_132_)
  );
  sky130_fd_sc_hd__nor3_1 _436_ (
    .A(_129_),
    .B(_130_),
    .C(_131_),
    .Y(_133_)
  );
  sky130_fd_sc_hd__xnor2_1 _437_ (
    .A(_129_),
    .B(_132_),
    .Y(_134_)
  );
  sky130_fd_sc_hd__nand3_1 _438_ (
    .A(a[5]),
    .B(b[6]),
    .C(_134_),
    .Y(_135_)
  );
  sky130_fd_sc_hd__a21o_1 _439_ (
    .A1(a[5]),
    .A2(b[6]),
    .B1(_134_),
    .X(_136_)
  );
  sky130_fd_sc_hd__nand2_1 _440_ (
    .A(_135_),
    .B(_136_),
    .Y(_137_)
  );
  sky130_fd_sc_hd__xnor2_1 _441_ (
    .A(_128_),
    .B(_137_),
    .Y(_138_)
  );
  sky130_fd_sc_hd__xor2_1 _442_ (
    .A(_127_),
    .B(_138_),
    .X(_139_)
  );
  sky130_fd_sc_hd__xnor2_1 _443_ (
    .A(_126_),
    .B(_139_),
    .Y(_140_)
  );
  sky130_fd_sc_hd__o21ai_0 _444_ (
    .A1(_118_),
    .A2(_120_),
    .B1(_140_),
    .Y(_141_)
  );
  sky130_fd_sc_hd__nor3_1 _445_ (
    .A(_118_),
    .B(_120_),
    .C(_140_),
    .Y(_142_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _446_ (
    .A(_141_),
    .SLEEP(_142_),
    .X(_143_)
  );
  sky130_fd_sc_hd__xnor2_1 _447_ (
    .A(_125_),
    .B(_143_),
    .Y(u_csamul_u_cla8_xor3)
  );
  sky130_fd_sc_hd__o21ai_0 _448_ (
    .A1(_125_),
    .A2(_142_),
    .B1(_141_),
    .Y(_144_)
  );
  sky130_fd_sc_hd__maj3_1 _449_ (
    .A(_126_),
    .B(_127_),
    .C(_138_),
    .X(_145_)
  );
  sky130_fd_sc_hd__o21ai_0 _450_ (
    .A1(_128_),
    .A2(_137_),
    .B1(_135_),
    .Y(_146_)
  );
  sky130_fd_sc_hd__and2_0 _451_ (
    .A(a[5]),
    .B(b[7]),
    .X(_147_)
  );
  sky130_fd_sc_hd__nor2_1 _452_ (
    .A(_130_),
    .B(_133_),
    .Y(_148_)
  );
  sky130_fd_sc_hd__and4_1 _453_ (
    .A(a[6]),
    .B(a[7]),
    .C(b[5]),
    .D(b[6]),
    .X(_149_)
  );
  sky130_fd_sc_hd__a22oi_1 _454_ (
    .A1(a[7]),
    .A2(b[5]),
    .B1(b[6]),
    .B2(a[6]),
    .Y(_150_)
  );
  sky130_fd_sc_hd__nor3_1 _455_ (
    .A(_148_),
    .B(_149_),
    .C(_150_),
    .Y(_151_)
  );
  sky130_fd_sc_hd__o21a_1 _456_ (
    .A1(_149_),
    .A2(_150_),
    .B1(_148_),
    .X(_152_)
  );
  sky130_fd_sc_hd__nor2_1 _457_ (
    .A(_151_),
    .B(_152_),
    .Y(_153_)
  );
  sky130_fd_sc_hd__xnor2_1 _458_ (
    .A(_147_),
    .B(_153_),
    .Y(_154_)
  );
  sky130_fd_sc_hd__xor2_1 _459_ (
    .A(_146_),
    .B(_154_),
    .X(_155_)
  );
  sky130_fd_sc_hd__nor2_1 _460_ (
    .A(_145_),
    .B(_155_),
    .Y(_156_)
  );
  sky130_fd_sc_hd__nand2_1 _461_ (
    .A(_145_),
    .B(_155_),
    .Y(_157_)
  );
  sky130_fd_sc_hd__nand2b_1 _462_ (
    .A_N(_156_),
    .B(_157_),
    .Y(_158_)
  );
  sky130_fd_sc_hd__xnor2_1 _463_ (
    .A(_144_),
    .B(_158_),
    .Y(u_csamul_u_cla8_xor4)
  );
  sky130_fd_sc_hd__a21o_1 _464_ (
    .A1(_144_),
    .A2(_157_),
    .B1(_156_),
    .X(_159_)
  );
  sky130_fd_sc_hd__maj3_1 _465_ (
    .A(_146_),
    .B(_147_),
    .C(_153_),
    .X(_160_)
  );
  sky130_fd_sc_hd__nor2_1 _466_ (
    .A(_149_),
    .B(_151_),
    .Y(_161_)
  );
  sky130_fd_sc_hd__and4_1 _467_ (
    .A(a[6]),
    .B(a[7]),
    .C(b[6]),
    .D(b[7]),
    .X(_162_)
  );
  sky130_fd_sc_hd__a22oi_1 _468_ (
    .A1(a[7]),
    .A2(b[6]),
    .B1(b[7]),
    .B2(a[6]),
    .Y(_163_)
  );
  sky130_fd_sc_hd__nor2_1 _469_ (
    .A(_162_),
    .B(_163_),
    .Y(_164_)
  );
  sky130_fd_sc_hd__xnor2_1 _470_ (
    .A(_161_),
    .B(_164_),
    .Y(_165_)
  );
  sky130_fd_sc_hd__xnor2_1 _471_ (
    .A(_160_),
    .B(_165_),
    .Y(_166_)
  );
  sky130_fd_sc_hd__xnor2_1 _472_ (
    .A(_159_),
    .B(_166_),
    .Y(u_csamul_u_cla8_xor5)
  );
  sky130_fd_sc_hd__maj3_1 _473_ (
    .A(_159_),
    .B(_160_),
    .C(_165_),
    .X(_167_)
  );
  sky130_fd_sc_hd__and2_0 _474_ (
    .A(a[7]),
    .B(b[7]),
    .X(_168_)
  );
  sky130_fd_sc_hd__o21bai_1 _475_ (
    .A1(_161_),
    .A2(_163_),
    .B1_N(_162_),
    .Y(_169_)
  );
  sky130_fd_sc_hd__xor3_1 _476_ (
    .A(_167_),
    .B(_168_),
    .C(_169_),
    .X(u_csamul_u_cla8_xor6)
  );
  sky130_fd_sc_hd__maj3_1 _477_ (
    .A(_167_),
    .B(_168_),
    .C(_169_),
    .X(u_csamul_u_cla8_or1_2_2_11)
  );
  assign u_csamul_out = { u_csamul_u_cla8_or1_2_2_11, u_csamul_u_cla8_xor6, u_csamul_u_cla8_xor5, u_csamul_u_cla8_xor4, u_csamul_u_cla8_xor3, u_csamul_u_cla8_xor2, u_csamul_u_cla8_xor1, u_csamul_u_cla8_pg_logic0_pg_logic_xor0, u_csamul_fa0_7_fa_xor1, u_csamul_fa0_6_fa_xor1, u_csamul_fa0_5_fa_xor1, u_csamul_fa0_4_fa_xor1, u_csamul_fa0_3_fa_xor1, u_csamul_fa0_2_fa_xor1, u_csamul_ha0_1_ha_xor0, u_csamul_and0_0 };
endmodule

(* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/rcs8.v:1.1-109.10" *)
module u_rcs(a, b, u_rcs_out);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/rcs8.v:1.26-1.27" *)
  input [7:0] a;
  wire [7:0] a;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/rcs8.v:1.41-1.42" *)
  input [7:0] b;
  wire [7:0] b;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/rcs8.v:10.8-10.25" *)
  wire u_rcs_fa1_fa_xor1;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/rcs8.v:16.8-16.25" *)
  wire u_rcs_fa2_fa_xor1;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/rcs8.v:22.8-22.25" *)
  wire u_rcs_fa3_fa_xor1;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/rcs8.v:28.8-28.25" *)
  wire u_rcs_fa4_fa_xor1;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/rcs8.v:34.8-34.25" *)
  wire u_rcs_fa5_fa_xor1;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/rcs8.v:40.8-40.25" *)
  wire u_rcs_fa6_fa_xor1;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/rcs8.v:46.8-46.25" *)
  wire u_rcs_fa7_fa_xor1;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/rcs8.v:5.8-5.28" *)
  wire u_rcs_ha_fa_xor1_not;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/rcs8.v:49.8-49.20" *)
  wire u_rcs_not_c7;
  (* src = "/home/lucky/Desktop/ASCA Project/tiny-gpu-custom-alu/src/ALUs/rcs8.v:1.57-1.66" *)
  output [8:0] u_rcs_out;
  wire [8:0] u_rcs_out;
  sky130_fd_sc_hd__clkinv_1 _21_ (
    .A(a[1]),
    .Y(_00_)
  );
  sky130_fd_sc_hd__clkinv_1 _22_ (
    .A(a[2]),
    .Y(_01_)
  );
  sky130_fd_sc_hd__clkinv_1 _23_ (
    .A(a[3]),
    .Y(_02_)
  );
  sky130_fd_sc_hd__clkinv_1 _24_ (
    .A(a[4]),
    .Y(_03_)
  );
  sky130_fd_sc_hd__clkinv_1 _25_ (
    .A(a[5]),
    .Y(_04_)
  );
  sky130_fd_sc_hd__clkinv_1 _26_ (
    .A(a[6]),
    .Y(_05_)
  );
  sky130_fd_sc_hd__clkinv_1 _27_ (
    .A(a[7]),
    .Y(_06_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _28_ (
    .A(b[0]),
    .SLEEP(a[0]),
    .X(_07_)
  );
  sky130_fd_sc_hd__xor2_1 _29_ (
    .A(b[0]),
    .B(a[0]),
    .X(u_rcs_ha_fa_xor1_not)
  );
  sky130_fd_sc_hd__xnor2_1 _30_ (
    .A(b[1]),
    .B(a[1]),
    .Y(_08_)
  );
  sky130_fd_sc_hd__maj3_1 _31_ (
    .A(b[1]),
    .B(_00_),
    .C(_07_),
    .X(_09_)
  );
  sky130_fd_sc_hd__xnor2_1 _32_ (
    .A(b[2]),
    .B(a[2]),
    .Y(_10_)
  );
  sky130_fd_sc_hd__maj3_1 _33_ (
    .A(b[2]),
    .B(_01_),
    .C(_09_),
    .X(_11_)
  );
  sky130_fd_sc_hd__xnor2_1 _34_ (
    .A(b[3]),
    .B(a[3]),
    .Y(_12_)
  );
  sky130_fd_sc_hd__maj3_1 _35_ (
    .A(b[3]),
    .B(_02_),
    .C(_11_),
    .X(_13_)
  );
  sky130_fd_sc_hd__xnor2_1 _36_ (
    .A(b[4]),
    .B(a[4]),
    .Y(_14_)
  );
  sky130_fd_sc_hd__maj3_1 _37_ (
    .A(b[4]),
    .B(_03_),
    .C(_13_),
    .X(_15_)
  );
  sky130_fd_sc_hd__xnor2_1 _38_ (
    .A(b[5]),
    .B(a[5]),
    .Y(_16_)
  );
  sky130_fd_sc_hd__maj3_1 _39_ (
    .A(b[5]),
    .B(_04_),
    .C(_15_),
    .X(_17_)
  );
  sky130_fd_sc_hd__xnor2_1 _40_ (
    .A(b[6]),
    .B(a[6]),
    .Y(_18_)
  );
  sky130_fd_sc_hd__maj3_1 _41_ (
    .A(b[6]),
    .B(_05_),
    .C(_17_),
    .X(_19_)
  );
  sky130_fd_sc_hd__xnor2_1 _42_ (
    .A(b[7]),
    .B(a[7]),
    .Y(_20_)
  );
  sky130_fd_sc_hd__maj3_1 _43_ (
    .A(b[7]),
    .B(_06_),
    .C(_19_),
    .X(u_rcs_not_c7)
  );
  sky130_fd_sc_hd__xnor2_1 _44_ (
    .A(_07_),
    .B(_08_),
    .Y(u_rcs_fa1_fa_xor1)
  );
  sky130_fd_sc_hd__xnor2_1 _45_ (
    .A(_09_),
    .B(_10_),
    .Y(u_rcs_fa2_fa_xor1)
  );
  sky130_fd_sc_hd__xnor2_1 _46_ (
    .A(_11_),
    .B(_12_),
    .Y(u_rcs_fa3_fa_xor1)
  );
  sky130_fd_sc_hd__xnor2_1 _47_ (
    .A(_13_),
    .B(_14_),
    .Y(u_rcs_fa4_fa_xor1)
  );
  sky130_fd_sc_hd__xnor2_1 _48_ (
    .A(_15_),
    .B(_16_),
    .Y(u_rcs_fa5_fa_xor1)
  );
  sky130_fd_sc_hd__xnor2_1 _49_ (
    .A(_17_),
    .B(_18_),
    .Y(u_rcs_fa6_fa_xor1)
  );
  sky130_fd_sc_hd__xnor2_1 _50_ (
    .A(_19_),
    .B(_20_),
    .Y(u_rcs_fa7_fa_xor1)
  );
  assign u_rcs_out = { u_rcs_not_c7, u_rcs_fa7_fa_xor1, u_rcs_fa6_fa_xor1, u_rcs_fa5_fa_xor1, u_rcs_fa4_fa_xor1, u_rcs_fa3_fa_xor1, u_rcs_fa2_fa_xor1, u_rcs_fa1_fa_xor1, u_rcs_ha_fa_xor1_not };
endmodule
